// Offline producer analysis. No process, filesystem, GPU or active-search port.
import {createHash} from 'node:crypto';
import {isDeepStrictEqual} from 'node:util';
import {createReferee} from './referee.mjs';
import {validateOwnerTeardown} from './teardown.mjs';
import {analyzePairedBenefit} from './paired-statistics.mjs';
import {admitTimingPolicy} from '../move-timing/policy.mjs';
import {Chess} from 'chess.js';

const studies=new WeakSet(),reports=new WeakMap(),hex=v=>typeof v==='string'&&/^[0-9a-f]{64}$/.test(v),hash=v=>createHash('sha256').update(v).digest('hex');
const fail=label=>{throw new Error('clock study: '+label);};
function closed(v,keys,label){if(!v||typeof v!=='object'||Array.isArray(v))fail(label+' fields');const descriptors=Object.getOwnPropertyDescriptors(v);if(Reflect.ownKeys(descriptors).length!==keys.length||keys.some(k=>!Object.hasOwn(descriptors,k)||!Object.hasOwn(descriptors[k],'value')))fail(label+' fields');}
function integer(v,min,max,label){if(!Number.isSafeInteger(v)||v<min||v>max)fail(label);return v;}
function finite(v,min,max,label){if(!Number.isFinite(v)||v<min||v>max)fail(label);return v;}
function token(v){if(typeof v!=='string'||!/^[A-Za-z0-9_.+-]{1,128}$/.test(v))fail('identifier');return v;}
function freeze(v){if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;}
function read(artifact,max){closed(artifact,['text','sha256'],'artifact');if(typeof artifact.text!=='string'||Buffer.byteLength(artifact.text)>max||!hex(artifact.sha256)||hash(artifact.text)!==artifact.sha256)fail('artifact digest/extent');return JSON.parse(artifact.text);}
function selected(handle){if(!studies.has(handle))fail('unadmitted study');return handle;}
function summary(handle,kind,value){const result=freeze({...value,sha256:hash(JSON.stringify(value))});reports.set(result,{handle,kind});return result;}
function owned(handle,value,kind){if(reports.get(value)?.handle!==handle||reports.get(value)?.kind!==kind)fail('report authority');}
function scopes(value){if(!Array.isArray(value)||value.length<1||value.length>32||new Set(value).size!==value.length)fail('scope extent');value.forEach(token);}
function thresholds(value,reserve){closed(value,['p99_ms','maximum_ms'],'reserve thresholds');finite(value.p99_ms,0.001,reserve,'p99 bound');finite(value.maximum_ms,value.p99_ms,reserve,'maximum bound');}
function nanoseconds(value){if(typeof value!=='string'||!/^(?:0|[1-9][0-9]{0,19})$/.test(value))fail('canonical nanosecond timestamp');const n=BigInt(value);if(n>0xffffffffffffffffn)fail('nanosecond timestamp capacity');return n;}

export function createClockStudyOrders({openings,treatments,discoverySeed,heldOutSeed}){
 if(!hex(discoverySeed)||!hex(heldOutSeed)||discoverySeed===heldOutSeed)fail('distinct order seeds');closed(openings,['discovery','held_out'],'opening splits');if(!Array.isArray(treatments)||treatments.length!==3)fail('order treatments');
 const order=(partition,seed,ids)=>{const rows=[];if(!Array.isArray(openings[partition])||openings[partition].length<8||openings[partition].length>16)fail('order population');for(const o of openings[partition])for(const treatment_id of ids)for(const candidate_color of ['white','black'])rows.push({opening_id:token(o.id),treatment_id:token(treatment_id),candidate_color});let counter=0;
  for(let i=rows.length-1;i>0;i--){const limit=Math.floor(0x100000000/(i+1))*(i+1);let n;do{if(counter>=4096)fail('order draw bound');n=createHash('sha256').update(`vector-clock-order-v1/${partition}/${seed}/${counter++}`).digest().readUInt32BE(0);}while(n>=limit);const j=n%(i+1);[rows[i],rows[j]]=[rows[j],rows[i]];}
  return{method:'sha256-counter-fisher-yates-v1',seed,trials:rows.map((r,i)=>({trial_id:`${partition}-${String(i).padStart(3,'0')}`,...r}))};};
 return freeze({discovery:order('discovery',discoverySeed,treatments.map(t=>t.id)),held_out:order('held_out',heldOutSeed,[treatments[0].id,'selected'])});
}

export function admitClockStudy(artifact,{runtimeIdentitySha256,referenceIdentitySha256,hardwareIdentitySha256}){
 const s=read(artifact,262144);closed(s,['schema','campaign_id','evidence_class','preregistered_at_ms','runtime_identity_sha256','hardware_identity_sha256','reference_identity_sha256','reference_settings','control','rules_profile','transport_reserve_ms','reserve','treatments','openings','orders'],'preregistration');
 if(s.schema!=='vector_clock_study_v1'||!['native','fixture'].includes(s.evidence_class)||s.rules_profile!=='orthodoxy-live-claims-v1')fail('unsupported preregistration');token(s.campaign_id);integer(s.preregistered_at_ms,1,Number.MAX_SAFE_INTEGER,'preregistration time');
 for(const [value,want]of [[s.runtime_identity_sha256,runtimeIdentitySha256],[s.reference_identity_sha256,referenceIdentitySha256],[s.hardware_identity_sha256,hardwareIdentitySha256]])if(!hex(want)||value!==want)fail('exact identity binding');
 if(!isDeepStrictEqual(s.control,{initial_time_ms:180000,increment_ms:3000})||!isDeepStrictEqual(s.reference_settings,{id_name:'Stockfish 15.1',movetime_ms:10,SkillLevel:0,Threads:1,Hash:16,Ponder:false,UseNNUE:true}))fail('supported control/reference settings');integer(s.transport_reserve_ms,0,10000,'transport reserve');
 closed(s.reserve,['sha256','local_publication_reserve_ms','measurement_protocol_sha256','supported_scopes','thresholds'],'reserve selection');if(!hex(s.reserve.sha256)||!hex(s.reserve.measurement_protocol_sha256))fail('reserve binding');integer(s.reserve.local_publication_reserve_ms,1,10000,'local reserve');scopes(s.reserve.supported_scopes);thresholds(s.reserve.thresholds,s.reserve.local_publication_reserve_ms);
 if(!Array.isArray(s.treatments)||s.treatments.length!==3)fail('three frozen treatments');const ids=new Set(),digests=new Set();for(const [i,t]of s.treatments.entries()){closed(t,['id','elapsed_ms','experiment_sha256'],'treatment');token(t.id);if(t.id==='selected'||ids.has(t.id)||digests.has(t.experiment_sha256)||t.elapsed_ms!==[0,500,1000][i]||!hex(t.experiment_sha256))fail('frozen treatments');ids.add(t.id);digests.add(t.experiment_sha256);}
 closed(s.openings,['discovery','held_out'],'opening splits');const openingIds=new Set(),positions=new Set();for(const group of Object.values(s.openings)){if(!Array.isArray(group)||group.length<8||group.length>16)fail('opening population8..16');for(const o of group){closed(o,['id','fen','moves'],'opening');token(o.id);if(typeof o.fen!=='string'||o.fen.length>128||!Array.isArray(o.moves)||o.moves.length>1024)fail('opening history');const ref=createReferee(o.fen,{rulesProfile:s.rules_profile});o.moves.forEach(m=>ref.play(m));const key=ref.fen().split(" ").slice(0,4).join(" ");if(ref.terminal()||openingIds.has(o.id)||positions.has(key))fail('distinct nonterminal independent opening units');openingIds.add(o.id);positions.add(key);}}
 closed(s.orders,['discovery','held_out'],'trial orders');const orders=createClockStudyOrders({openings:s.openings,treatments:s.treatments,discoverySeed:s.orders.discovery?.seed,heldOutSeed:s.orders.held_out?.seed});if(!isDeepStrictEqual(s.orders,orders))fail('preregistered seeded trial orders');
 const handle=freeze({...s,sha256:artifact.sha256});studies.add(handle);return handle;
}

function processClose(value,joined){
 if(value?.schema!=='vector_uci_process_close_observation_v1'||value.normal_close!==true||value.forced!==false||value.exit_code!==0||value.signal!==null||value.stdio_closed!==true||value.fixture===true)fail('normal process close');
 if(joined){if(value.owner_teardown_status!=='validated')fail('joined owner close');const owner=validateOwnerTeardown(value.owner_teardown,{requireJoined:true});for(const receipt of [owner,...(owner.gameTeardowns??[])])if(receipt.joined&&(receipt.semantic.fields.drainDisposition!==0||receipt.semantic.fields.stopCause!==2))fail('selected joined closure first-stop/drain disposition');}else if(value.owner_teardown!==null||value.owner_teardown_status!=='not_required')fail('reference close');
}
function clocksEqual(actual,want){closed(actual,['white','black'],'actual clocks');for(const c of ['white','black'])if(actual[c]!==want[c]||!Number.isFinite(actual[c]))fail('actual clock recurrence');}
function actualDecision(s,r,treatment,remaining){
 const decisions=r.info.filter(line=>line.startsWith('info string vector_timing_experiment ')).map(line=>JSON.parse(line.slice('info string vector_timing_experiment '.length))),phases=r.info.filter(line=>line.startsWith('info string vector_clock_phase ')).map(line=>JSON.parse(line.slice('info string vector_clock_phase '.length)));
 if(decisions.length===0){if(new Chess(r.fen).moves().length!==1)fail('missing actual timing decision');return;}
 if(decisions.length!==1)fail('duplicate actual timing decision');const d=decisions[0];closed(d,['schema','diagnostic','experiment_sha256','focusIdentity','applicability','clock','localPublicationReserveMs','transportReserveMs','safeEnvelopeFromGoMs','publicationDeadlineFromGoMs','purchasedBlocksMs','reason','usefulBlockAuthority'],'actual timing decision');
 if(d.schema!=='vector_timing_experiment_decision_v1'||d.diagnostic!==true||d.experiment_sha256!==treatment.experiment_sha256||d.usefulBlockAuthority!==false||d.applicability!=='search_derived'||d.localPublicationReserveMs!==s.reserve.local_publication_reserve_ms||d.transportReserveMs!==s.transport_reserve_ms||!isDeepStrictEqual(d.clock,{initialTimeMs:180000,remainingMs:Math.floor(remaining),incrementMs:3000,movesToGo:null}))fail('actual timing decision binding');closed(d.focusIdentity,['rootEpoch','requestId'],'decision focus');Object.values(d.focusIdentity).forEach(v=>integer(v,1,0xfffffffe,'decision focus word'));
 const safe=Math.max(0,Math.floor(remaining)-s.reserve.local_publication_reserve_ms-s.transport_reserve_ms);if(d.safeEnvelopeFromGoMs!==safe||!Array.isArray(d.purchasedBlocksMs))fail('decision clock envelope');const purchased=d.purchasedBlocksMs.reduce((a,b)=>a+b,0),admission=d.publicationDeadlineFromGoMs-purchased;finite(admission,0,r.elapsed_ms,'decision admission elapsed');if(d.publicationDeadlineFromGoMs>safe)fail('decision exceeds hard envelope');
 const affordable=admission+treatment.elapsed_ms<=safe,blocks=treatment.elapsed_ms&&affordable?[treatment.elapsed_ms]:[],reason=treatment.elapsed_ms===0?'baseline_no_discretionary_purchase':affordable?'candidate_target_reached':'no_affordable_candidate_block';if(!isDeepStrictEqual(d.purchasedBlocksMs,blocks)||d.reason!==reason)fail('frozen treatment decision');
 const own=phases.filter(p=>p.rootEpoch===d.focusIdentity.rootEpoch&&p.requestId===d.focusIdentity.requestId),get=phase=>{const rows=own.filter(p=>p.phase===phase);if(rows.length!==1||rows[0].schema!=='vector_uci_clock_phase_v1')fail('actual decision phase');return finite(rows[0].time,0,Number.MAX_SAFE_INTEGER,'decision phase time');};const go=get('goReceived'),requested=get('publicationRequested'),emitted=get('emit');if(requested<go||emitted<requested)fail('actual decision phase order');if(requested<go+d.publicationDeadlineFromGoMs)fail('publication before purchased deadline');
}
function validateGame(s,trial,opening,treatment){
 const g=trial.game;closed(g,['schema','diagnostic','rules_profile','trial_controls','opening_id','candidate_color','result','termination','complete','legal','records','clocks_ms','final_fen','pgn','failure','qualification'],'game');
 if(g.schema!=='vector_clock_experiment_game_v1'||g.diagnostic!==true||g.complete!==true||g.legal!==true||g.failure!==null||g.opening_id!==opening.id||g.rules_profile!==s.rules_profile||!['white','black'].includes(g.candidate_color)||!isDeepStrictEqual(g.qualification,{timing:false,strength:false,useful_blocks:false,publication:false}))fail('complete legal diagnostic game');
 const c=g.trial_controls;closed(c,['opening','candidateColor','initialTimeMs','incrementMs','maxPlies','responseTimeoutMs','maxDurationMs','referenceGo'],'game controls');if(!isDeepStrictEqual(c.opening,opening)||c.candidateColor!==g.candidate_color||c.initialTimeMs!==180000||c.incrementMs!==3000||!isDeepStrictEqual(c.referenceGo,{movetime:10}))fail('actual treatment controls');integer(c.maxPlies,1,2048,'ply bound');integer(c.responseTimeoutMs,100,300000,'response bound');integer(c.maxDurationMs,1000,3600000,'game duration bound');
 if(!Array.isArray(g.records)||g.records.length<1||g.records.length>c.maxPlies||typeof g.pgn!=='string'||g.pgn.length>262144)fail('game extent');const ref=createReferee(opening.fen,{rulesProfile:s.rules_profile});opening.moves.forEach(m=>ref.play(m));const clocks={white:180000,black:180000};let elapsed=0;
 for(const [i,r]of g.records.entries()){
  closed(r,['ply','owner','color','fen','move','elapsed_ms','clock_before_ms','clock_after_ms','info'],'move observation');const color=ref.turn()==='w'?'white':'black',owner=color===g.candidate_color?'candidate':'reference';
  if(ref.terminal()||r.ply!==opening.moves.length+i||r.color!==color||r.owner!==owner||r.fen!==ref.fen())fail('legal replay/focus');finite(r.elapsed_ms,0,c.maxDurationMs,'actual elapsed');elapsed+=r.elapsed_ms;if(elapsed>c.maxDurationMs)fail('duration-bound game');clocksEqual(r.clock_before_ms,clocks);clocks[color]-=r.elapsed_ms;
  if(clocks[color]<=0||owner==='candidate'&&clocks[color]<s.reserve.local_publication_reserve_ms+s.transport_reserve_ms)fail('flag/residual-clock reserve');
  if(!Array.isArray(r.info)||r.info.length>256||r.info.some(line=>typeof line!=='string'||line.length>32768))fail('bounded UCI observations');if(owner==='candidate')actualDecision(s,r,treatment,r.clock_before_ms[color]);ref.play(r.move);clocks[color]+=3000;clocksEqual(r.clock_after_ms,clocks);
 }
 const terminal=ref.terminal();if(!terminal||terminal.result!==g.result||terminal.termination!==g.termination||ref.fen()!==g.final_fen)fail('actual terminal game');clocksEqual(g.clocks_ms,clocks);processClose(trial.candidate_close,true);processClose(trial.reference_close,false);
 return g.result==='1/2-1/2'?.5:(g.result==='1-0')===(g.candidate_color==='white')?1:0;
}
function population(s,partition,trials,treatments){
 const openings=s.openings[partition],expected=openings.length*treatments.length*2;if(!Array.isArray(trials)||trials.length!==expected)fail('complete matched color/treatment population');let bytes=0;const rows=new Map(),trialDigests=[],chronology=[];
 for(const artifact of trials){const t=read(artifact,16777216);bytes+=Buffer.byteLength(artifact.text);if(bytes>134217728)fail('population byte bound');closed(t,['schema','evidence_class','study_sha256','partition','trial_id','order_index','opening_id','treatment_id','experiment_sha256','runtime_identity_sha256','reference_identity_sha256','hardware_identity_sha256','started_at_ms','completed_at_ms','reserve_scope','candidate_close','reference_close','game'],'trial');
  const opening=openings.find(o=>o.id===t.opening_id),treatment=treatments.find(v=>v.id===t.treatment_id);if(t.schema!=='vector_clock_study_trial_v1'||t.evidence_class!==s.evidence_class||t.study_sha256!==s.sha256||t.partition!==partition||!opening||!treatment||t.experiment_sha256!==treatment.experiment_sha256||t.runtime_identity_sha256!==s.runtime_identity_sha256||t.reference_identity_sha256!==s.reference_identity_sha256||t.hardware_identity_sha256!==s.hardware_identity_sha256||!s.reserve.supported_scopes.includes(t.reserve_scope))fail('trial source/treatment identity');integer(t.started_at_ms,s.preregistered_at_ms+1,Number.MAX_SAFE_INTEGER,'trial after preregistration');
  integer(t.order_index,0,expected-1,'trial order index');integer(t.completed_at_ms,t.started_at_ms+1,Number.MAX_SAFE_INTEGER,'trial completed time');const wanted=s.orders[partition].trials[t.order_index],orderTreatment=partition==='held_out'&&treatment.id!==s.treatments[0].id?'selected':treatment.id;if(!isDeepStrictEqual(wanted,{trial_id:t.trial_id,opening_id:t.opening_id,treatment_id:orderTreatment,candidate_color:t.game?.candidate_color}))fail('actual preregistered trial order');chronology.push({index:t.order_index,start:t.started_at_ms,end:t.completed_at_ms});
  const score=validateGame(s,t,opening,treatment),key=`${opening.id}/${treatment.id}/${t.game.candidate_color}`;if(rows.has(key))fail('duplicate color trial');rows.set(key,score);trialDigests.push({key,sha256:artifact.sha256});
 }
 chronology.sort((a,b)=>a.index-b.index);if(chronology.some((v,i)=>v.index!==i||i>0&&v.start<chronology[i-1].end))fail('actual trial chronology');const outcomes=treatments.map(t=>({id:t.id,values:openings.map(o=>(rows.get(`${o.id}/${t.id}/white`)+rows.get(`${o.id}/${t.id}/black`))/2)}));trialDigests.sort((a,b)=>a.key.localeCompare(b.key));return{outcomes,started_at_ms:chronology[0].start,completed_at_ms:chronology.at(-1).end,population_sha256:hash(JSON.stringify(trialDigests)),final_clock_facts:'each actual final clock retained in hash-bound game receipts'};
}
function benefit(values,baseline,alpha,correction){const stat=analyzePairedBenefit(values.map((v,i)=>v-baseline[i]));return{opening_units:stat.units,mean_score_gain:stat.mean_delta,directional_p:stat.directional_p,bonferroni_p:Math.min(1,correction*stat.directional_p),benefit_passed:stat.mean_delta>=.05&&stat.directional_p<=alpha};}
export function analyzeClockDiscovery(handle,trials){const s=selected(handle),p=population(s,'discovery',trials,s.treatments),baseline=p.outcomes[0].values,candidates=p.outcomes.slice(1).map((v,i)=>({treatment_id:v.id,elapsed_ms:s.treatments[i+1].elapsed_ms,...benefit(v.values,baseline,.025,2)}));return summary(s,'discovery',{schema:'vector_clock_discovery_analysis_v1',study_sha256:s.sha256,evidence_class:s.evidence_class,qualified:false,completed_at_ms:p.completed_at_ms,population_sha256:p.population_sha256,candidates,selected_treatment:candidates.find(c=>c.benefit_passed)?.treatment_id??null});}
export function analyzeClockHeldOut(handle,discovery,trials){const s=selected(handle);owned(s,discovery,'discovery');if(!discovery.selected_treatment)fail('no discovery-selected candidate');const treatment=s.treatments.find(t=>t.id===discovery.selected_treatment),p=population(s,'held_out',trials,[s.treatments[0],treatment]);if(p.started_at_ms<=discovery.completed_at_ms)fail('held-out chronology before discovery completion');return summary(s,'held_out',{schema:'vector_clock_held_out_analysis_v1',study_sha256:s.sha256,evidence_class:s.evidence_class,qualified:false,discovery_sha256:discovery.sha256,selected_treatment:treatment.id,population_sha256:p.population_sha256,...benefit(p.outcomes[1].values,p.outcomes[0].values,.05,1)});}

export function analyzeClockReserve(handle,artifact){
 const s=selected(handle),r=read(artifact,16777216);closed(r,['schema','evidence_class','runtime_identity_sha256','hardware_identity_sha256','measurement_protocol_sha256','clock_domain','local_publication_reserve_ms','supported_scopes','thresholds','process_closures','calibration','held_out'],'reserve measurement');
 if(artifact.sha256!==s.reserve.sha256||r.schema!=='vector_clock_reserve_measurement_v1'||r.evidence_class!==s.evidence_class||r.clock_domain!=='node26-windows-qpc-ns-v1'||r.runtime_identity_sha256!==s.runtime_identity_sha256||r.hardware_identity_sha256!==s.hardware_identity_sha256||r.measurement_protocol_sha256!==s.reserve.measurement_protocol_sha256||r.local_publication_reserve_ms!==s.reserve.local_publication_reserve_ms||!isDeepStrictEqual(r.supported_scopes,s.reserve.supported_scopes)||!isDeepStrictEqual(r.thresholds,s.reserve.thresholds))fail('reserve native identity/source binding');
 const closures=new Map();if(!Array.isArray(r.process_closures)||r.process_closures.length<1||r.process_closures.length>256)fail('reserve process closure extent');for(const c of r.process_closures){closed(c,['id','process_close'],'reserve process closure');token(c.id);if(closures.has(c.id))fail('duplicate process closure');processClose(c.process_close,true);closures.set(c.id,false);}
 const ids=new Set(),requests=new Set(),timestamps=new Set(),results={};for(const partition of ['calibration','held_out']){const samples=r[partition];if(!Array.isArray(samples)||samples.length<30||samples.length>131072)fail('reserve sample extent');const groups=new Map(r.supported_scopes.map(id=>[id,[]]));for(const row of samples){closed(row,['id','scope_id','process_id','root_epoch','request_id','publication_requested_ns','emitted_ns','received_ns'],'reserve raw observation');token(row.id);integer(row.root_epoch,1,0xfffffffe,'reserve root epoch');integer(row.request_id,1,0xfffffffe,'reserve request ID');const request=`${row.process_id}/${row.root_epoch}/${row.request_id}`,timestamp=`${row.process_id}/${row.publication_requested_ns}`;if(ids.has(row.id)||requests.has(request)||timestamps.has(timestamp)||!groups.has(row.scope_id)||!closures.has(row.process_id))fail('independent reserve scopes/samples');ids.add(row.id);requests.add(request);timestamps.add(timestamp);closures.set(row.process_id,true);const requested=nanoseconds(row.publication_requested_ns),emitted=nanoseconds(row.emitted_ns),received=nanoseconds(row.received_ns);if(emitted<requested||received<emitted)fail('literal nanosecond timestamp order');const difference=received-requested;if(difference>BigInt(r.local_publication_reserve_ms)*1000000n)fail('observed reserve threshold');groups.get(row.scope_id).push(Number(difference)/1000000);}
  results[partition]=Object.fromEntries([...groups].map(([id,values])=>{if(values.length<30||values.length>4096)fail('reserve independent scope population');values.sort((a,b)=>a-b);const p99=values[Math.ceil(values.length*.99)-1],maximum=values.at(-1);if(p99>r.thresholds.p99_ms||maximum>r.thresholds.maximum_ms||maximum>r.local_publication_reserve_ms)fail('observed reserve threshold');return[id,{samples:values.length,p99_ms:p99,maximum_ms:maximum}];}));
 }
 if([...closures.values()].some(used=>!used))fail('unbound reserve closure');return summary(s,'reserve',{schema:'vector_clock_reserve_analysis_v1',study_sha256:s.sha256,evidence_class:s.evidence_class,qualified:false,receipt_sha256:artifact.sha256,scopes:r.supported_scopes.map(id=>({id,calibration:results.calibration[id],held_out:results.held_out[id]}))});
}
export function produceTimingPolicy(handle,discovery,heldOut,reserveArtifact){
 const s=selected(handle);owned(s,discovery,'discovery');owned(s,heldOut,'held_out');if(s.evidence_class!=='native')fail('fixture cannot produce a native policy');if(!discovery.selected_treatment||heldOut.discovery_sha256!==discovery.sha256||heldOut.selected_treatment!==discovery.selected_treatment||!heldOut.benefit_passed)fail('independent selected candidate benefit');analyzeClockReserve(s,reserveArtifact);
 const d=discovery.candidates.find(c=>c.treatment_id===discovery.selected_treatment),result=v=>({opening_units:v.opening_units,mean_score_gain:v.mean_score_gain,directional_p:v.directional_p}),value={schema:'vector_timing_policy_v1',producer:'vector-evidence-runtime/clock-allocation-v1',runtime_identity_sha256:s.runtime_identity_sha256,control:s.control,strategy:{kind:'target_blocks_v1',target_blocks:1},useful_blocks_ms:[d.elapsed_ms],local_publication_reserve_ms:s.reserve.local_publication_reserve_ms,unsupported_fallback:'publish-current',qualification:{status:'qualified',study_sha256:s.sha256,discovery_sha256:discovery.sha256,held_out_sha256:heldOut.sha256,reserve_sha256:reserveArtifact.sha256,allocation:true,useful_blocks:true,clock_safety:true,discovery:result(d),held_out:result(heldOut)}};
 const text=JSON.stringify(value)+'\n',sha256=hash(text);admitTimingPolicy(text,{sha256,runtimeIdentitySha256:s.runtime_identity_sha256});return freeze({text,sha256,study_sha256:s.sha256,reference_identity_sha256:s.reference_identity_sha256,hardware_identity_sha256:s.hardware_identity_sha256,scope:'180+3 versus signed Stockfish15.1 Skill0/movetime10 only; no rating or six-control claim'});
}
