import {getAcceptedContractAuthority,normalizeDomainProfile} from 'cuda-mcgs/search-compiler';
import {buildEngineSessionDomainModule} from './domain-transition.mjs';
import {semanticCatalog,selectedContract,profileRepresentation,finiteWorkBounds,withPublicSchema} from './profile-artifacts.mjs';
const u32={type:'integer',minimum:0,maximum:4294967295},words=n=>({type:'array',minItems:n,maxItems:n,items:u32});
const failures={'invalid-input':'input','invalid-root':'input','invalid-state':'input','invalid-action-scope':'input','invalid-cursor':'input','invalid-profile':'input','capacity-required':'capacity',cancelled:'cancellation','incompatible-action-producer':'compatibility','domain-history-exhausted':'exhaustion','domain-clock-exhausted':'exhaustion','unsupported-domain-case':'unsupported','domain-internal-failure':'internal'};
export function createChessDomainProfile({authority=getAcceptedContractAuthority(),revision}={}){
  if(typeof revision!=='string'||!/^[0-9a-f]{40}$/.test(revision))throw new Error('Real product source revision is required');
  const source=buildEngineSessionDomainModule(),catalog=semanticCatalog('vector.chess-domain',source.profileVersion),value=id=>'domain.vector-chess.value-'+id;
  const layouts={action:['fixed-record',4], 'action-cursor':['fixed-record',4], 'action-key':['fixed-record',4],diagnostic:['variable-record',1024],history:['unit',0],'identity-key':['fixed-record',4],'operation-status':['tagged-union',4],'path-relation':['tagged-union',4],'random-input':['unit',0],'role-key':['fixed-record',4],'root-descriptor':['fixed-record',68892],state:['fixed-record',68892],'terminal-outcome':['fixed-record',12],'transition-input':['unit',0],'transition-metadata':['tagged-union',4],'transition-output':['fixed-record',68892],'truth-value':['scalar',1]};
  const semantics={state:{format:'vector.chess-mailbox-u32/1.2.0',wordCount:17223,headerWords:71,historyRecordWords:67,maximumHistoryRecords:256,rawEnPassantWord:70,validator:'vDomainValid',equality:'cEqual',sourceIdentity:source.sourceIdentity},history:{disposition:'embedded',records:'complete-relevant-chronological',irreversiblePrefixRemoval:['pawn-move','capture','castling-right-loss'],arbitraryTruncation:false,equality:'cEqual'},action:{fromBits:[0,5],toBits:[6,11],promotionBits:[12,14],promotion:['none','knight','bishop','rook','queen'],validator:'vDomainActionValid',originAuthorityRequired:true},'terminal-outcome':{drawProfile:'orthodox_live_claims_v1',words:['terminalReason','sideToMove','claimFlags'],reasons:['active','mate','stalemate','automatic75','fivefold','insufficient'],claimFlags:{fifty:1,threefold:2},claimOnlyRemainsActive:true},'identity-key':{algorithm:'fnv32-hint',collisionAuthority:'exact-cEqual-required'},'path-relation':{codes:{0:'none',1:'exact-semantic-state-equality'},drawProofFromRelation:false}};
  const valueSchemas=Object.entries(layouts).map(([role,[family,max]])=>({id:value(role),semanticRole:role,schema:catalog.define('value-'+role,role==='random-input'||role==='transition-input'||role==='history'?{type:'null'}:role==='truth-value'?{type:'boolean'}:words(Math.floor(max/4)),semantics[role]??{semanticRole:role,sourceIdentity:source.sourceIdentity}),family,maxEncodedBytes:String(max),alignmentBytes:max===0||max===1?'1':'4',memorySpaces:['device-search',...(['state','action','terminal-outcome'].includes(role)?['device-publication']:[])],decoding:['state','action','history','root-descriptor','transition-output'].includes(role)?'profile-semantic-equivalence':'canonical-bytes'}));
  const sourceId='domain.vector-chess.legal-actions',transition='domain.vector-chess.transition',decision='domain.vector-chess.decision',terminal='domain.vector-chess.terminal';
  const specs=[['action-key',['state','history','action'],['action-key','operation-status']],['apply-transition',['state','history','action','transition-input','random-input'],['state','history','transition-output','transition-metadata','operation-status']],['classify-path-relation',['state','history'],['path-relation','operation-status']],['classify-role',['state','history'],['role-key','operation-status']],['equal-action',['state','history','action'],['truth-value','operation-status']],['equal-state',['state','history'],['truth-value','operation-status']],['identity-key',['state','history'],['identity-key','operation-status']],['terminal-outcome',['state','history'],['terminal-outcome','operation-status']],['validate-action',['state','history','action'],['action','operation-status']],['validate-root',['root-descriptor'],['state','history','role-key','operation-status']],['produce-actions',['state','history','action-cursor','random-input'],['action','action-cursor','operation-status']]];
  const ports=specs.map(([id,inputs,outputs])=>({id,contract:catalog.define('port-'+id,{type:'object',additionalProperties:false,properties:{inputs:{type:'array'},outputs:{type:'array'}},required:['inputs','outputs']},{inputRoles:inputs,outputRoles:outputs,sourceIdentity:source.sourceIdentity,atomicSemanticCompletion:true}),inputs:inputs.map(value),outputs:outputs.map(value),failures:['invalid-state','invalid-action-scope','capacity-required','domain-history-exhausted','domain-clock-exhausted','cancelled','domain-internal-failure'],bounds:finiteWorkBounds(),completion:{kind:'bounded'}}));
  const input={schema:'cuda-mcgs.domain-profile/0.2.0',representation:profileRepresentation,status:'accepted',contract:selectedContract(authority,'SPEC-0007'),id:'domain.vector-chess',version:'1.2.0',valueSchemas,identity:{scope:'engine-incarnation',keyValue:value('identity-key'),stateEquality:'semantic-port',actionEquality:'semantic-port',actionScope:{kind:'origin-state-view-and-production-incarnation'},collisionVerification:'authoritative-equality-port',behaviorFacts:['domain.vector-chess.complete-relevant-state','domain.vector-chess.raw-enpassant-model-identity'],readyPayloads:'immutable'},history:{disposition:'embedded',valueSchema:value('history'),identityParticipation:'embedded-state',finiteRule:{kind:'none'},reuse:[{boundary:'root-advance',disposition:'valid'},{boundary:'restart',disposition:'invalid'},{boundary:'persistence',disposition:'invalid'}]},rootForms:[{id:'domain.vector-chess.root',authority:'complete-state',schema:catalog.get('value-root-descriptor'),valueSchema:value('root-descriptor')}],roles:[{id:decision,category:'decision',terminal:false,selectorAuthority:'domain.vector-chess.side-to-move',actionSources:[sourceId],transitionMode:transition,successorRoles:[decision,terminal],zeroActionDisposition:'domain.vector-chess.terminal-check'},{id:terminal,category:'terminal',terminal:true,terminalOutcomeValue:value('terminal-outcome')}],actionSources:[{id:sourceId,kind:'intrinsic',mode:'exhaustive',ordering:'semantic',multiplicity:'unique',cursorValue:value('action-cursor'),candidateValue:value('action'),maxActions:'256',bounds:finiteWorkBounds(),completion:'complete',randomness:{kind:'none',maxInputs:'0'},semantics:catalog.define('legal-actions',words(256),{source:'vDomainActions',order:'from-to-promotion',pressure:'no-partial-authority'})}],transitionModes:[{id:transition,kind:'deterministic',inputValue:value('transition-input'),outputValue:value('transition-output'),metadataValue:value('transition-metadata'),randomness:{kind:'none',maxInputs:'0'},observation:'none',numericRules:[],semantics:catalog.define('transition',words(17223),{source:'vDomainApply',irreversibleRelevantHistory:true,exactClocks:true,rawEnPassant:true})}],ports,resources:[{id:'domain.vector-chess.scratch',unit:'bytes',minimum:'284',maximum:'284',alignment:'4',memorySpaces:['device-search'],scope:'per-invocation',pressureOutcome:'capacity-required'}],failures:Object.entries(failures).map(([code,kind])=>({code,kind,diagnostic:true})),diagnostics:{authority:'non-authoritative',maxRecords:'16',maxBytes:'1024',overflow:'count'},compatibility:{crossProfileEquality:'false-unless-versioned-compatibility',persistence:{kind:'none'},hostDeviceRepresentation:{kind:'identical'}},programContribution:{language:'restricted-device-js',sourceIdentity:source.sourceIdentity,inputs:[{id:'domain.vector-chess.state-input',schema:catalog.get('value-state'),identity:source.sourceIdentity}],provenance:{origin:'first-party',revision,license:'GPL-3.0-or-later'}},productData:[]};
  // State is supplied by protected Domain admission, not immutable program data.
  input.programContribution.inputs=[];
  input.version=source.profileVersion;
  const calls={cAbs:[],cColor:[],cType:[],cStep:[],cClear:['cStep'],cAttacked:['cAbs','cColor','cType','cClear'],cKing:[],cValidBoard:['cType','cAttacked','cKing'],cSimulate:['cAbs','cColor','cType'],cLegal:['cAbs','cColor','cType','cClear','cAttacked','cKing','cSimulate'],cEffectiveEp:['cType','cLegal'],cNormalizeHistory:['cEffectiveEp'],cRepetitions:[],cInsufficient:['cType'],cApply:['cAbs','cType','cSimulate','cLegal','cEffectiveEp'],cIdentity:[],cEqual:[],vDomainValid:['cValidBoard'],vDomainActions:['cColor','cType','cLegal'],vDomainActionValid:['cLegal'],vDomainActionEqual:[],vDomainApply:['cApply'],vDomainHasAction:['cColor','cType','cLegal'],vDomainTerminal:['cAttacked','cKing','cRepetitions','cInsufficient','vDomainHasAction'],vDomainRelation:['cEqual']};
  calls.vDomainClassifyTransitionResult=[];
  calls.vDomainAdmitRoot=['vDomainValid','cNormalizeHistory'];
  const contributionFunctions=source.functions.map(f=>{if(!Object.hasOwn(calls,f.name))throw new Error(`Domain callable dependency declaration missing: ${f.name}`);return{...f,calls:calls[f.name]};});
  return{...withPublicSchema(normalizeDomainProfile(input,authority),'domain'),input,source,contributionFunctions,semanticArtifacts:catalog.artifacts};
}
