import {createHash} from 'node:crypto';
import {inspectDeviceProgram} from 'cuda-js';
import {residentDeviceSearchContract} from 'cuda-mcgs/search-compiler';
import {buildChessPolicyDeviceModule} from '../chess-policy/device.mjs';
import {buildPolicyPublicationModule} from '../chess-policy/publication.mjs';
import {buildModelInputDeviceModule} from '../chess-model-input/device.mjs';
import {buildEngineDomainModule} from './domain-device.mjs';

function member(partition,name,elements){
  if(partition?.dtype!=='f32'||!Number.isSafeInteger(partition.elementCount)||!Number.isSafeInteger(partition.perRequestElements)||partition.perRequestElements<1||partition.elementCount<partition.perRequestElements||!Array.isArray(partition.members))throw new Error('Selected Evaluator partition layout is required');
  const entry=partition.members.find(m=>m.parameterName===name);
  if(!entry||entry.perItemElements!==elements||!Number.isSafeInteger(entry.offset)||entry.offset<0||entry.offset+elements>partition.perRequestElements)throw new Error('Selected Evaluator member extent/layout mismatch');
  return entry;
}
export function buildChessPolicyHooks({evaluatorLayout}={}){
  if(!evaluatorLayout)throw new Error('Selected Evaluator layout is required');
  const {requestInputPartition:input,resultOutputPartition:result,featureParameter,policyParameter,valueParameter}=evaluatorLayout;
  const features=member(input,featureParameter,1088),policy=member(result,policyParameter,4162),value=member(result,valueParameter,1);
  if(policy.offset<value.offset+1&&value.offset<policy.offset+4162)throw new Error('Selected Evaluator result partitions overlap');
  const base=buildChessPolicyDeviceModule(),publication=buildPolicyPublicationModule(),model=buildModelInputDeviceModule(),functions=[],hooks={},evaluatorFunctions=model.functions.map(f=>({...f,calls:f.name==='mSquare'?[]:['mSquare']})),evaluatorHooks={};let source=base.source+publication.source,evaluatorSource=model.source;
  const add=(key,body)=>{const selected=residentDeviceSearchContract.hooks[key];if(!selected)throw new Error(`Public resident hook ${key} unavailable`);const name=(key==='encodeEvaluation'?'vEvaluator':'vPolicy')+key[0].toUpperCase()+key.slice(1),metadata={name,kind:'device',parameters:selected.parameters.map(p=>({...p})),returns:selected.returns,...(key==='consumeEvaluation'?{calls:['mPolicyIndex']}:{}),...(key==='encodeEvaluation'?{calls:['mWriteFeatures']}:{})},text=`\nfunction ${name}(${selected.parameters.map(p=>p.name).join(',')}) {${body}}\n`;if(key==='encodeEvaluation'){evaluatorHooks[key]=name;evaluatorFunctions.push(metadata);evaluatorSource+=text;}else{hooks[key]=name;functions.push(metadata);source+=text;}};
  add('initializeNode',`for(let j=gpu.u32(0);j<gpu.u32(6);j++){node[nodeBase+j]=gpu.u32(0);}for(let j=gpu.u32(0);j<gpu.u32(4);j++){numeric[numericBase+j]=gpu.f32(0);}`);
  add('initializeCandidate',`for(let j=gpu.u32(0);j<gpu.u32(6);j++){edge[edgeBase+j]=gpu.u32(0);}edge[edgeBase+gpu.u32(4)]=action[actionBase];for(let j=gpu.u32(0);j<gpu.u32(4);j++){numeric[numericBase+j]=gpu.f32(0);}`);
  add('select',`return vChoose(edges,edgesBase,edgeNumeric,edgeNumericBase,count,gpu.u32(1));`);
  add('reserve',`if(work===gpu.u32(4294967295)||edge[edgeBase+gpu.u32(1)]!==gpu.u32(0)){return gpu.u32(1);}edge[edgeBase+gpu.u32(1)]=work+gpu.u32(1);return gpu.u32(0);`);
  add('release',`if(work!==gpu.u32(4294967295)&&edge[edgeBase+gpu.u32(1)]===work+gpu.u32(1)){edge[edgeBase+gpu.u32(1)]=gpu.u32(0);}`);
  add('classifyFrontier',`let proof=node[nodeBase+gpu.u32(2)];if(proof>gpu.u32(3)||reason>gpu.u32(2)){return gpu.u32(4294967295);}if(proof!==gpu.u32(0)){value[valueBase]=gpu.f32(0);if(proof===gpu.u32(1)){value[valueBase]=gpu.f32(1);}if(proof===gpu.u32(2)){value[valueBase]=gpu.f32(-1);}value[valueBase+gpu.u32(1)]=gpu.f32(proof);return gpu.u32(0);}if(node[nodeBase+gpu.u32(3)]===gpu.u32(0)){return gpu.u32(2);}if(reason===gpu.u32(0)){return gpu.u32(1);}let cached=nodeNumeric[nodeNumericBase+gpu.u32(2)];if(cached!==cached||cached<gpu.f32(-1)||cached>gpu.f32(1)){return gpu.u32(4294967295);}value[valueBase]=cached;value[valueBase+gpu.u32(1)]=gpu.f32(0);return gpu.u32(0);`);
  add('encodeEvaluation',`if(count===gpu.u32(0)||count>gpu.u32(256)||stateBase>gpu.u32(4294950072)||encodedBase>gpu.u32(${input.elementCount-input.perRequestElements})){return gpu.u32(1);}return mWriteFeatures(state,stateBase,stateBase+gpu.u32(17223),encoded,encodedBase+gpu.u32(${features.offset}),gpu.u32(${input.elementCount}));`);
  add('consumeEvaluation',`if(count===gpu.u32(0)||count>gpu.u32(256)||stateBase>gpu.u32(4294950072)||resultsBase>gpu.u32(${result.elementCount-result.perRequestElements})){return gpu.u32(1);}let scalar=results[resultsBase+gpu.u32(${value.offset})];if(scalar!==scalar||scalar<gpu.f32(-1)||scalar>gpu.f32(1)){return gpu.u32(1);}let maximum=gpu.f32(-1000000);
    for(let j=gpu.u32(0);j<count;j++){let index=mPolicyIndex(state,stateBase,stateBase+gpu.u32(17223),actions[actionsBase+j]);if(index<gpu.i32(0)||index>=gpu.i32(4162)||edges[edgesBase+j*gpu.u32(6)+gpu.u32(4)]!==actions[actionsBase+j]){return gpu.u32(1);}let logit=results[resultsBase+gpu.u32(${policy.offset})+gpu.u32(index)];if(logit!==logit||logit<gpu.f32(-1000000)||logit>gpu.f32(1000000)){return gpu.u32(1);}if(logit>maximum){maximum=logit;}}
    let sum=gpu.f32(0);for(let j=gpu.u32(0);j<count;j++){let index=mPolicyIndex(state,stateBase,stateBase+gpu.u32(17223),actions[actionsBase+j]);sum=sum+gpu.math.exp(results[resultsBase+gpu.u32(${policy.offset})+gpu.u32(index)]-maximum);}if(sum!==sum||sum<gpu.f32(1)||sum>gpu.f32(256)){return gpu.u32(1);}
    for(let j=gpu.u32(0);j<count;j++){let index=mPolicyIndex(state,stateBase,stateBase+gpu.u32(17223),actions[actionsBase+j]);edgeNumeric[edgeNumericBase+j*gpu.u32(4)+gpu.u32(1)]=gpu.math.exp(results[resultsBase+gpu.u32(${policy.offset})+gpu.u32(index)]-maximum)/sum;edges[edgesBase+j*gpu.u32(6)+gpu.u32(3)]=gpu.u32(1);}nodeNumeric[nodeNumericBase+gpu.u32(2)]=scalar;node[nodeBase+gpu.u32(3)]=gpu.u32(1);value[valueBase]=scalar;value[valueBase+gpu.u32(1)]=gpu.f32(0);return gpu.u32(0);`);
  add('terminalValue',`let reason=outcome[outcomeBase];if(reason===gpu.u32(0)||reason>gpu.u32(5)||outcome[outcomeBase+gpu.u32(1)]!==state[stateBase+gpu.u32(64)]){return gpu.u32(1);}let scalar=gpu.f32(0);let proof=gpu.u32(3);if(reason===gpu.u32(1)){scalar=gpu.f32(-1);proof=gpu.u32(2);}node[nodeBase+gpu.u32(2)]=proof;node[nodeBase+gpu.u32(3)]=gpu.u32(1);numeric[numericBase+gpu.u32(2)]=scalar;value[valueBase]=scalar;value[valueBase+gpu.u32(1)]=gpu.f32(proof);return gpu.u32(0);`);
  add('valueValid',`let scalar=value[valueBase];let proof=value[valueBase+gpu.u32(1)];return scalar===scalar&&scalar>=gpu.f32(-1)&&scalar<=gpu.f32(1)&&(proof===gpu.f32(0)||proof===gpu.f32(1)||proof===gpu.f32(2)||proof===gpu.f32(3));`);
  add('prepare',`if(work===gpu.u32(4294967295)||occurrences===gpu.u32(0)||occurrences>gpu.u32(10000000)||node[nodeBase]>gpu.u32(10000000)-occurrences||node[nodeBase+gpu.u32(1)]!==gpu.u32(0)||node[nodeBase+gpu.u32(5)]===work+gpu.u32(1)){return gpu.u32(1);}node[nodeBase+gpu.u32(1)]=work+gpu.u32(1);return gpu.u32(0);`);
  add('abandon',`if(work!==gpu.u32(4294967295)&&node[nodeBase+gpu.u32(1)]===work+gpu.u32(1)){node[nodeBase+gpu.u32(1)]=gpu.u32(0);}`);
  add('retirePolicy',`if(count>gpu.u32(256)||node[nodeBase]>gpu.u32(10000000)||node[nodeBase+gpu.u32(2)]>gpu.u32(3)){return gpu.u32(2);}if(node[nodeBase+gpu.u32(1)]!==gpu.u32(0)){return gpu.u32(1);}for(let j=gpu.u32(0);j<count;j++){let base=edgesBase+j*gpu.u32(6);if(edges[base]>gpu.u32(10000000)||edges[base+gpu.u32(2)]>gpu.u32(3)){return gpu.u32(2);}if(edges[base+gpu.u32(1)]!==gpu.u32(0)){return gpu.u32(1);}}return gpu.u32(0);`);
  add('evaluateStop',`let visits=node[nodeBase];let proof=node[nodeBase+gpu.u32(2)];if(visits>gpu.u32(10000000)||proof>gpu.u32(3)){return gpu.u32(2);}if(visits===gpu.u32(10000000)||proof!==gpu.u32(0)){return gpu.u32(1);}return gpu.u32(0);`);
  add('apply',`if(count>gpu.u32(256)||work===gpu.u32(4294967295)||policy[nodeBase+gpu.u32(1)]!==work+gpu.u32(1)||!vPolicyValueValid(value,valueBase)||policy[nodeBase]>=gpu.u32(10000000)||policy[nodeBase+gpu.u32(2)]>gpu.u32(3)){return gpu.u32(1);}if(incomingBase!==gpu.u32(4294967295)&&(policy[incomingBase]>=gpu.u32(10000000)||policy[incomingBase+gpu.u32(1)]!==work+gpu.u32(1)||parentBase===gpu.u32(4294967295)||state[stateBase+gpu.u32(64)]===parent[parentBase+gpu.u32(64)])){return gpu.u32(1);}
    let win=false;let allLoss=count!==gpu.u32(0);let allKnown=count!==gpu.u32(0);let draw=false;
    for(let j=gpu.u32(0);j<count;j++){let mask=childReady[childReadyBase+j];if(mask>gpu.u32(2)){return gpu.u32(1);}let proof=edges[edgesBase+j*gpu.u32(6)+gpu.u32(2)];if(proof>gpu.u32(3)){return gpu.u32(1);}if(mask===gpu.u32(1)){let childProof=children[childrenBase+j*gpu.u32(6)+gpu.u32(2)];if(childProof>gpu.u32(3)){return gpu.u32(1);}let converted=childProof;if(childProof===gpu.u32(1)){converted=gpu.u32(2);}if(childProof===gpu.u32(2)){converted=gpu.u32(1);}if(converted!==gpu.u32(0)){if(proof!==gpu.u32(0)&&proof!==converted){return gpu.u32(1);}proof=converted;}}if(proof===gpu.u32(1)){win=true;}if(proof!==gpu.u32(2)){allLoss=false;}if(proof===gpu.u32(0)){allKnown=false;}if(proof===gpu.u32(3)){draw=true;}}
    let completedProof=policy[nodeBase+gpu.u32(2)];let recomputed=gpu.u32(0);if(complete&&count!==gpu.u32(0)&&terminalRole===gpu.u32(0)){if(win){recomputed=gpu.u32(1);}else if(allLoss){recomputed=gpu.u32(2);}else if(allKnown&&draw){recomputed=gpu.u32(3);}if(recomputed!==gpu.u32(0)){if(completedProof!==gpu.u32(0)&&completedProof!==recomputed){return gpu.u32(1);}completedProof=recomputed;}}
    let scalar=value[valueBase];if(completedProof===gpu.u32(1)){scalar=gpu.f32(1);}if(completedProof===gpu.u32(2)){scalar=gpu.f32(-1);}if(completedProof===gpu.u32(3)){scalar=gpu.f32(0);}
    for(let j=gpu.u32(0);j<count;j++){if(childReady[childReadyBase+j]===gpu.u32(1)){let childProof=children[childrenBase+j*gpu.u32(6)+gpu.u32(2)];if(childProof!==gpu.u32(0)){if(childProof===gpu.u32(1)){childProof=gpu.u32(2);}else if(childProof===gpu.u32(2)){childProof=gpu.u32(1);}edges[edgesBase+j*gpu.u32(6)+gpu.u32(2)]=childProof;}}}
    policy[nodeBase]=policy[nodeBase]+gpu.u32(1);numeric[nodeNumericBase]=numeric[nodeNumericBase]+scalar;policy[nodeBase+gpu.u32(2)]=completedProof;if(incomingBase!==gpu.u32(4294967295)){policy[incomingBase]=policy[incomingBase]+gpu.u32(1);numeric[incomingNumericBase]=numeric[incomingNumericBase]-scalar;let proof=completedProof;if(proof===gpu.u32(1)){proof=gpu.u32(2);}else if(proof===gpu.u32(2)){proof=gpu.u32(1);}policy[incomingBase+gpu.u32(2)]=proof;}value[valueBase]=-scalar;value[valueBase+gpu.u32(1)]=gpu.f32(0);return gpu.u32(0);`);
  add('complete',`if(work!==gpu.u32(4294967295)&&node[nodeBase+gpu.u32(1)]===work+gpu.u32(1)){node[nodeBase+gpu.u32(1)]=gpu.u32(0);node[nodeBase+gpu.u32(5)]=work+gpu.u32(1);}`);
  add('encodeSnapshotRow',`if(record[recordBase]===gpu.u32(0)&&record[recordBase+gpu.u32(2)]===gpu.u32(0)&&record[recordBase+gpu.u32(3)]===gpu.u32(0)){return vEncodeUnavailableRow(encoded,encodedBase);}return vEncodeSnapshotRow(record,recordBase,numeric,numericBase,encoded,encodedBase);`);
  add('encodeUnavailableRow',`return vEncodeUnavailableRow(encoded,encodedBase);`);
  add('chooseEncoded',`return vChooseEncodedRestricted(rows,rowBase,count,restriction);`);
  const calls={vChooseEncodedRestricted:['vChooseEncoded','vSnapshotBetter'],vPolicySelect:['vChoose'],vPolicyApply:['vPolicyValueValid'],vPolicyEncodeSnapshotRow:['vEncodeSnapshotRow','vEncodeUnavailableRow'],vPolicyEncodeUnavailableRow:['vEncodeUnavailableRow'],vPolicyChooseEncoded:['vChooseEncodedRestricted'],vPolicyConsumeEvaluation:['mPolicyIndex']};
  return Object.freeze({source,functions:[...base.functions,...publication.functions,...functions].map(f=>({...f,calls:calls[f.name]??[]})),hooks,evaluator:{source:evaluatorSource,functions:evaluatorFunctions,hooks:evaluatorHooks,sourceIdentity:{algorithm:'sha256',sha256:createHash('sha256').update(evaluatorSource).digest('hex')}},recordWidths:{nodeU32:6,nodeF32:4,edgeU32:6,edgeF32:4,value:2},resultLayout:{policyOffset:policy.offset,valueOffset:value.offset,perRequestElements:result.perRequestElements},sourceIdentity:{algorithm:'sha256',sha256:createHash('sha256').update(source).digest('hex')},claimLimits:['product-policy-contribution-only','selected-evaluator-ready-results','no-composed-native-search-claim']});
}
export function inspectChessPolicyHooks(options){
  const policy=buildChessPolicyHooks(options),domain=buildEngineDomainModule();
  const signatures=[...domain.functions,...policy.evaluator.functions,...policy.functions].map(({calls,...signature})=>signature);
  return inspectDeviceProgram({source:domain.source+policy.evaluator.source+policy.source+'\nfunction policyProbe(state,records,numeric){vPolicyInitializeNode(state,gpu.u32(0),records,gpu.u32(0),numeric,gpu.u32(0));}',functions:[...signatures,{name:'policyProbe',kind:'kernel',parameters:[{name:'state',type:'ptr<u32>'},{name:'records',type:'ptr<u32>'},{name:'numeric',type:'ptr<f32>'}],returns:'void'}]});
}
