import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {admitBookSnapshot,createBookGame,bookKeyForRoot,createBookProvider} from '../../components/root-knowledge/book.mjs';
import {uciToAction,START_POSITION} from '../../components/uci-protocol/index.mjs';
const key=0x463b96181691fc9cn;
const e4=uciToAction('e2e4'),d4=uciToAction('d2d4');
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const policy=`prior_games=64\ndraw_value=0.35\nconfidence_standard_errors=1\nminimum_games=32\nmaximum_lcb_gap=0.05\nquality_exponent=14\nmaximum_rarity_multiplier=4\nexit_intercept=-4.2\nexit_depth_weight=2\nexit_advantage_weight=2.4\nexit_disadvantage_weight=-3\nexit_weakness_weight=0.8\neval_deadband_cp=20\neval_scale_cp=180\ndepth_start_ply=8\ndepth_span_plies=22\n`;
function fnv(bytes){let value=0xcbf29ce484222325n;for(const byte of bytes)value=BigInt.asUintN(64,(value^BigInt(byte))*0x100000001b3n);return value.toString(16).padStart(16,'0');}
async function fixture(t,{stats=false,manifest=false}={}){
 const parent=await fs.realpath(os.tmpdir()),dir=await fs.mkdtemp(path.join(parent,'vector-book-')),initial=await fs.lstat(dir,{bigint:true});
 t.after(async()=>{const current=await fs.lstat(dir,{bigint:true});assert.ok(current.isDirectory()&&!current.isSymbolicLink());for(const key of ['dev','ino','birthtimeNs'])assert.equal(current[key],initial[key]);assert.equal(await fs.realpath(dir),dir);assert.equal(path.dirname(dir),parent);assert.ok(path.basename(dir).startsWith('vector-book-'));await fs.rm(dir,{recursive:true});});
 const book=Buffer.alloc(32);for(const [i,move,weight]of [[0,0x02db,10],[1,0x031c,30]]){book.writeBigUInt64BE(key,i*16);book.writeUInt16BE(move,i*16+8);book.writeUInt16BE(weight,i*16+10);}
 const files={bookFile:path.join(dir,'strong_rare_v1.bin'),statsFile:path.join(dir,'strong_rare_v1.stats'),policyFile:path.join(dir,'strong_rare_v1.policy')};await fs.writeFile(files.bookFile,book);
 if(stats){const text=`# uci_arena_book_stats_v1 book_fnv1a64=${fnv(book)} rows=2\n463b96181691fc9c\t02db\t100\t55\t20\t25\n463b96181691fc9c\t031c\t120\t65\t25\t30\n`;await fs.writeFile(files.statsFile,text);await fs.writeFile(files.policyFile,policy);}
 if(manifest){const artifacts={};for(const file of Object.values(files))artifacts[path.basename(file)]=sha(await fs.readFile(file));await fs.writeFile(path.join(dir,'snapshot.manifest.json'),JSON.stringify({schema:'uci_arena_book_snapshot_v2',snapshot_id:'integration-0123456789abcdef0123',channel:'integration',record_count:2,qualified:false,artifacts}));}
 return {dir,files,book};
}
const context=(legalActions=[d4,e4])=>({schema:'vector_root_knowledge_context_v1',rootEpoch:1,rootFence:[1,0,1,1],input:{originFen:START_POSITION,moves:[]},legalActions,terminal:false});

test('immutable v2 identity mismatch is rejected before first snapshot activation',async t=>{
 const {files}=await fixture(t,{stats:true,manifest:true});
 await assert.rejects(admitBookSnapshot({...files,expectedManifestSha256:'0'.repeat(64)}),/BOOK_MANIFEST_IDENTITY/);
});

test('file-only immutable selection suppresses neighboring manifest and statistics and checks exact base pin',async t=>{
 const {files,book,dir}=await fixture(t,{stats:true,manifest:true});
 await fs.writeFile(path.join(dir,'snapshot.manifest.json'),'unrelated bad neighbor');
 const selected={bookFile:files.bookFile,statsFile:'',policyFile:'',manifestFile:'',expectedBookSha256:sha(book)};
 const snapshot=await admitBookSnapshot(selected);assert.equal(snapshot.status.capability,'polyglot_base');assert.equal(snapshot.status.validationMode,'legacy_file_set');assert.equal(snapshot.status.statisticalSelection,false);assert.equal(snapshot.status.strengthQualified,false);
 await assert.rejects(admitBookSnapshot({...selected,expectedBookSha256:'0'.repeat(64)}),/BOOK_FILE_IDENTITY/);
});

test('bound live generations refresh only between games; immutable pin retains first admitted identity',async t=>{
 const {createRootKnowledgeCoordinator}=await import('../../components/root-knowledge/coordinator.mjs');
 const {BOOK_BINDING_SCHEMA}=await import('../../components/root-knowledge/book-binding.mjs');
 for(const authorityMode of ['service_managed_live_channel','immutable_pinned_snapshot']){
  const {dir,files}=await fixture(t,{stats:true,manifest:true}),manifestFile=path.join(dir,'snapshot.manifest.json'),firstBytes=await fs.readFile(manifestFile);
  const bindingFile=path.join(dir,'binding.json'),document={schema:BOOK_BINDING_SCHEMA,schemaVersion:1,authorityMode,capability:'snapshot_v2',selection:{kind:'opening_book',path:dir,source:'saved_locator',storageMode:'in_place_reference'},files:{...files,manifestFile},pin:authorityMode==='immutable_pinned_snapshot'?{manifestSha256:sha(firstBytes)}:null};
  await fs.writeFile(bindingFile,JSON.stringify(document));const provider=createBookProvider(),statuses=[],coordinator=createRootKnowledgeCoordinator({bookProvider:provider,environment:{},onStatus:row=>{if(row.provider==='opening-book')statuses.push(row);}});
  for(const [name,value] of [['BookFile',files.bookFile],['BookStatsFile',files.statsFile],['BookPolicyFile',files.policyFile],['BookSnapshotBinding',bindingFile]])await coordinator.configure({name,value});
  await coordinator.ready();await coordinator.beginGame();await coordinator.prepare({context:context(),requestId:1});
  const first=statuses.at(-1).status.snapshot;assert.equal(first.identity,sha(firstBytes));
  const next={...JSON.parse(firstBytes),snapshot_id:'integration-11111111111111111111'};await fs.writeFile(manifestFile,JSON.stringify(next));
  await coordinator.ready();await coordinator.prepare({context:context(),requestId:2});assert.equal(statuses.at(-1).status.snapshot.identity,first.identity);
  await assert.rejects(coordinator.configure({name:'BookSnapshotBinding',value:bindingFile}),/startup|game/i);
  await assert.rejects(coordinator.configure({name:'BookFile',value:path.join(dir,'other.bin')}),/fixed.*game/i);
  await coordinator.endGame();await coordinator.ready();await coordinator.beginGame();
  const current=statuses.at(-1).status.snapshot;assert.equal(current.identity,authorityMode==='immutable_pinned_snapshot'?first.identity:sha(JSON.stringify(next)));
  await coordinator.close();
 }
});
test('base book resolves only GPU legal allowed moves and preserves current focus fence',async t=>{const {files}=await fixture(t);const snapshot=await admitBookSnapshot(files);assert.equal(snapshot.status.capability,'polyglot_base');assert.equal(snapshot.status.statisticalSelection,false);const game=createBookGame({snapshot,seed:123});const result=game.resolve({context:context(),searchmoves:[e4]});assert.equal(result.action,e4);assert.deepEqual(result.rootFence,[1,0,1,1]);assert.equal(result.authority,'book-resolved');assert.equal(result.telemetry.games,0);assert.equal(game.resolve({context:context([d4]),searchmoves:[e4]}).reason,'no_eligible_move');});
test('manifest-backed full pair binds every activated artifact and refuses corruption',async t=>{const {files,dir}=await fixture(t,{stats:true,manifest:true});const snapshot=await admitBookSnapshot(files);assert.equal(snapshot.status.statisticalSelection,true);assert.equal(snapshot.status.identity,sha(await fs.readFile(path.join(dir,'snapshot.manifest.json'))));await fs.appendFile(files.policyFile,'#changed\n');await assert.rejects(admitBookSnapshot(files),/BOOK_ARTIFACT_DIGEST/);});
test('partial sidecar is integrity failure and record duplicates are rejected',async t=>{const {files,book}=await fixture(t);await fs.writeFile(files.statsFile,'partial');await assert.rejects(admitBookSnapshot(files),/BOOK_SIDECAR_PAIR/);await fs.unlink(files.statsFile);book.copy(book,16,0,16);await fs.writeFile(files.bookFile,book);await assert.rejects(admitBookSnapshot(files),/BOOK_ORDER/);});
test('declared manifest count and file bounds reject before record materialization',async t=>{const {files,dir}=await fixture(t,{stats:true,manifest:true});const file=path.join(dir,'snapshot.manifest.json'),m=JSON.parse(await fs.readFile(file));m.record_count=2000001;await fs.writeFile(file,JSON.stringify(m));await assert.rejects(admitBookSnapshot(files),/BOOK_RECORD_COUNT/);});
test('statistical selection labels admitted cp separately from fallback and rejects nonfinite evaluation',async t=>{const {files}=await fixture(t,{stats:true});const snapshot=await admitBookSnapshot(files);const game=createBookGame({snapshot,seed:42});assert.throws(()=>game.resolve({context:context(),evaluationCp:Infinity}),/BOOK_EVALUATION/);const result=game.resolve({context:context(),evaluationCp:0});assert.equal(result.authority,'book-resolved');assert.equal(result.telemetry.evaluationSource,'compatible_completed_evaluation');});
test('original latency addendum permits reported neutral cp fallback with no evaluation wait',async t=>{const {files}=await fixture(t,{stats:true});const snapshot=await admitBookSnapshot(files);const result=createBookGame({snapshot,seed:42}).resolve({context:context()});assert.equal(result.authority,'book-resolved');assert.equal(result.telemetry.evaluationSource,'neutral_latency_fallback');assert.equal(result.telemetry.evaluationCp,0);});
test('searchmoves restricts publication without upgrading an ineligible sibling',async t=>{const {files,book}=await fixture(t,{stats:true});await fs.writeFile(files.statsFile,`# uci_arena_book_stats_v1 book_fnv1a64=${fnv(book)} rows=2\n463b96181691fc9c\t02db\t100\t100\t0\t0\n463b96181691fc9c\t031c\t120\t0\t0\t120\n`);const snapshot=await admitBookSnapshot(files);assert.equal(createBookGame({snapshot,seed:1}).resolve({context:context(),searchmoves:[e4],evaluationCp:0}).reason,'no_eligible_move');});
test('seeded games repeat and dynamic exit is latched without later RNG draws',async t=>{const {files}=await fixture(t,{stats:true});const snapshot=await admitBookSnapshot(files);const a=createBookGame({snapshot,seed:123}),b=createBookGame({snapshot,seed:123});const values=Array.from({length:5},()=>a.resolve({context:context(),evaluationCp:0}));assert.deepEqual(values,Array.from({length:5},()=>b.resolve({context:context(),evaluationCp:0})));const exit=createBookGame({snapshot,random:()=>0});assert.equal(exit.resolve({context:context(),evaluationCp:0}).reason,'dynamic_exit');assert.equal(exit.resolve({context:context(),evaluationCp:0}).reason,'book_exited');});
test('public root key derives from complete external input, handles uncapturable ep, and rejects illegal replay',()=>{assert.equal(bookKeyForRoot(context()),key);const after=context();after.input={originFen:START_POSITION,moves:[e4]};after.legalActions=[uciToAction('e7e5')];assert.equal(bookKeyForRoot(after),0x823c9b50fd114196n);assert.throws(()=>bookKeyForRoot({...context(),input:{originFen:START_POSITION,moves:[uciToAction('e2e5')]}}),/BOOK_INPUT/);});
test('same configuration failed reload retains prior complete snapshot, changed configuration retires it',async t=>{const {files}=await fixture(t);const provider=createBookProvider();const first=await provider.reload(files);assert.equal(first.active,true);await fs.writeFile(files.bookFile,Buffer.from('corrupt'));const failed=await provider.reload(files);assert.equal(failed.active,true);assert.equal(failed.retained,true);assert.equal(failed.snapshot.identity,first.snapshot.identity);const game=provider.newGame({seed:123});assert.equal(game.resolve({context:context(),searchmoves:[e4]}).action,e4);game.close();const changed=await provider.reload({...files,bookFile:files.bookFile+'.missing'});assert.equal(changed.active,false);assert.equal(provider.newGame({seed:123}),null);});
test('provider serializes reconfiguration and pins game snapshot across reloads',async t=>{const old=await fixture(t),next=await fixture(t);const provider=createBookProvider();await provider.reload(old.files);const game=provider.newGame({seed:1});const record=next.book.subarray(16);await fs.writeFile(next.files.bookFile,record);const [one,two]=await Promise.all([provider.reload(next.files),provider.reload(old.files)]);assert.equal(one.snapshot.recordCount,1);assert.equal(two.snapshot.recordCount,2);assert.equal(game.resolve({context:context(),searchmoves:[d4]}).action,d4);});
test('policy line and statistics line limits fail closed',async t=>{const {files}=await fixture(t,{stats:true});await fs.appendFile(files.policyFile,'#'+'x'.repeat(300)+'\n');await assert.rejects(admitBookSnapshot(files),/BOOK_LINE_BOUNDS/);await fs.writeFile(files.policyFile,policy);await fs.appendFile(files.statsFile,'0'.repeat(129));await assert.rejects(admitBookSnapshot(files),/BOOK_LINE_BOUNDS/);});
test('Polyglot castling and underpromotion decode only against GPU legal move set',async t=>{const {files}=await fixture(t);for(const [fen,raw,uci]of [['r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1',0x0107,'e1g1'],['7k/P7/8/8/8/8/8/7K w - - 0 1',0x1c38,'a7a8n']]){const action=uciToAction(uci),c={...context([action]),input:{originFen:fen,moves:[]}},record=Buffer.alloc(16);record.writeBigUInt64BE(bookKeyForRoot(c));record.writeUInt16BE(raw,8);record.writeUInt16BE(1,10);await fs.writeFile(files.bookFile,record);const snapshot=await admitBookSnapshot(files);assert.equal(createBookGame({snapshot,seed:1}).resolve({context:c}).action,action);}});
test('different configured roles sharing a basename cannot collapse manifest identity',async t=>{const {files,dir}=await fixture(t,{stats:true});const collision={};for(const [i,role]of Object.keys(files).entries()){const target=path.join(dir,String(i),'artifact');await fs.mkdir(path.dirname(target));await fs.copyFile(files[role],target);collision[role]=target;}const manifestFile=path.join(dir,'snapshot.manifest.json');await fs.writeFile(manifestFile,JSON.stringify({schema:'uci_arena_book_snapshot_v2',snapshot_id:'integration-0123456789abcdef0123',channel:'integration',record_count:2,qualified:false,artifacts:{artifact:sha(await fs.readFile(collision.policyFile))}}));await assert.rejects(admitBookSnapshot({...collision,manifestFile}),/BOOK_ROLE_ALIAS/);});
test('cold policy admission rejects reversed exit direction and worsening cp never increases exit probability',async t=>{const {files}=await fixture(t,{stats:true});for(const [original,replacement]of [['exit_advantage_weight=2.4','exit_advantage_weight=-2.4'],['exit_disadvantage_weight=-3','exit_disadvantage_weight=3']]){await fs.writeFile(files.policyFile,policy.replace(original,replacement));await assert.rejects(admitBookSnapshot(files),/BOOK_POLICY/);}await fs.writeFile(files.policyFile,policy);const snapshot=await admitBookSnapshot(files);let previous=Infinity;for(const cp of [1000,200,0,-200,-1000]){const result=createBookGame({snapshot,random:()=>0.999999}).resolve({context:context(),evaluationCp:cp});assert.ok(result.telemetry.exitProbability<=previous);previous=result.telemetry.exitProbability;}});
test('explicit snapshot refresh preserves RNG sequence while ordinary reload keeps game pinned',async t=>{const a=await fixture(t),b=await fixture(t);b.book.writeUInt32BE(1,12);await fs.writeFile(b.files.bookFile,b.book);const provider=createBookProvider();await provider.reload(a.files);const game=provider.newGame({seed:42}),control=createBookGame({snapshot:await admitBookSnapshot(a.files),seed:42});const first=game.resolve({context:context()});assert.equal(first.action,control.resolve({context:context()}).action);await provider.reload(b.files);assert.equal(game.resolve({context:context()}).snapshotIdentity,first.snapshotIdentity);control.resolve({context:context()});await provider.refreshGame();const next=game.resolve({context:context()});assert.notEqual(next.snapshotIdentity,first.snapshotIdentity);assert.equal(next.action,control.resolve({context:context()}).action);});
test('explicit refresh preserves exited latch and failed changed configuration disables only selection',async t=>{const a=await fixture(t,{stats:true}),b=await fixture(t);const provider=createBookProvider();await provider.reload(a.files);let rolls=0;const game=provider.newGame({random:()=>{rolls++;return 0;}});assert.equal(game.resolve({context:context()}).reason,'dynamic_exit');await provider.reload(b.files);await provider.refreshGame();assert.equal(game.resolve({context:context()}).reason,'book_exited');assert.equal(rolls,2);game.close();const active=provider.newGame({seed:42});await provider.reload({...b.files,bookFile:b.files.bookFile+'.missing'});await provider.refreshGame();assert.equal(active.resolve({context:context()}).reason,'book_unavailable');});
test('game seed can be initialized before a snapshot is available and later explicitly activated',async t=>{const provider=createBookProvider(),game=provider.beginGame({seed:42});assert.equal(game.resolve({context:context()}).reason,'book_unavailable');const {files}=await fixture(t);await provider.reload(files);await provider.refreshGame();assert.equal(game.resolve({context:context(),searchmoves:[e4]}).action,e4);game.close();});
test('explicit empty sidecar pair selects base capability and never reads disabled artifacts',async t=>{const {files}=await fixture(t,{stats:true,manifest:true});await fs.writeFile(files.statsFile,'corrupt disabled stats');await fs.writeFile(files.policyFile,'corrupt disabled policy');const snapshot=await admitBookSnapshot({...files,statsFile:'',policyFile:''});assert.equal(snapshot.status.capability,'polyglot_base');assert.equal(createBookGame({snapshot,seed:42}).resolve({context:context(),searchmoves:[e4]}).action,e4);await assert.rejects(admitBookSnapshot({...files,statsFile:''}),/BOOK_SIDECAR_PAIR/);});
test('disabled empty sidecars are not the same configuration as a directory path',async t=>{const {files}=await fixture(t),provider=createBookProvider();assert.equal((await provider.reload({...files,statsFile:'',policyFile:''})).active,true);const changed=await provider.reload({...files,statsFile:process.cwd(),policyFile:process.cwd()});assert.equal(changed.active,false);assert.equal(changed.retained,false);});
test('snapshot adoption rejects unadmitted forged handles without changing game selection',async t=>{const {files}=await fixture(t),snapshot=await admitBookSnapshot(files),game=createBookGame({snapshot,seed:1});assert.throws(()=>game.adoptSnapshot({...snapshot}),/BOOK_GAME/);assert.equal(game.resolve({context:context(),searchmoves:[e4]}).action,e4);});
test('Book pin admission rejects coercible objects without invoking their code',async t=>{
 const {files}=await fixture(t,{stats:true,manifest:true});let calls=0;
 const coercible={toString(){calls++;return '0'.repeat(64);}};
 await assert.rejects(admitBookSnapshot({...files,expectedManifestSha256:coercible}),/BOOK_PIN/);assert.equal(calls,0);
});
