import path from 'node:path';
import assert from 'node:assert/strict';
import test from 'node:test';
const context={schema:'vector_root_knowledge_context_v1',claimPolicy:'orthodoxy-live-claims-v1',rootEpoch:1,rootFence:[1,2,3,4],input:{originFen:'start',moves:[]},legalActions:[577],terminal:false};
async function api(){try{return await import('../../components/root-knowledge/coordinator.mjs');}catch(e){if(e.code==='ERR_MODULE_NOT_FOUND')assert.fail('Product root knowledge lifecycle is missing');throw e;}}
const fixture=()=>{const calls=[];let handle;const provider={async reload(files){calls.push(['reload',files]);return {active:true,snapshot:{identity:'a'},reason:null};},beginGame(options){calls.push(['begin',options]);handle={resolve(input){calls.push(['resolve',input]);return {status:'resolved',authority:'book-resolved',action:577,rootEpoch:input.context.rootEpoch,rootFence:input.context.rootFence};},close(){calls.push(['close']);}};return handle;},async refreshGame(options){calls.push(['refresh',options]);}};return {calls,provider};};
test('OwnBook=false never opens unrelated default files during readiness',async()=>{const {createRootKnowledgeCoordinator}=await api(),f=fixture(),c=createRootKnowledgeCoordinator({bookProvider:f.provider,environment:{ProgramData:'C:/unrelated'}});await c.configure({name:'OwnBook',value:false});await c.ready();await c.beginGame();assert.equal((await c.prepare({context,requestId:1})).reason,'disabled');assert.equal(f.calls.filter(x=>x[0]==='reload').length,0);await c.close();});
test('root knowledge resolves only once per go with live fence and refresh preserves producer-owned game latch',async()=>{const {createRootKnowledgeCoordinator}=await api(),f=fixture(),c=createRootKnowledgeCoordinator({bookProvider:f.provider,environment:{UCI_ARENA_KNOWLEDGE_ROOT:'C:/managed'}});await c.ready();await c.beginGame();const options=Object.fromEntries(c.options.map(o=>[o.name,o.default]));const result=await c.prepare({context,requestId:1,options});assert.equal(result.action,577);assert.equal(await c.prepare({context,requestId:1,options}),result);await c.configure({name:'BookFile',value:'C:/operator/new.bin'});await c.prepare({context,requestId:2,options:{...options,BookFile:'C:/operator/new.bin'}});assert.equal(f.calls.filter(x=>x[0]==='begin').length,1);assert.equal(f.calls.filter(x=>x[0]==='refresh').length,1);assert.equal(f.calls.filter(x=>x[0]==='resolve').length,2);await c.endGame();await c.ready();await c.beginGame();assert.equal(f.calls.filter(x=>x[0]==='begin').length,2);await c.close();});
test('disabled or terminal book intent consumes no roll and rejected typed option cannot change next go',async()=>{const {createRootKnowledgeCoordinator}=await api(),f=fixture(),c=createRootKnowledgeCoordinator({bookProvider:f.provider,environment:{}});await c.ready();await c.beginGame();const options=Object.fromEntries(c.options.map(o=>[o.name,o.default]));assert.equal((await c.prepare({context,requestId:1,options:{...options,OwnBook:false}})).status,'unavailable');assert.equal((await c.prepare({context:{...context,terminal:true},requestId:2,options})).status,'unavailable');assert.equal(f.calls.filter(x=>x[0]==='resolve').length,0);await assert.rejects(c.configure({name:'BookSeed',value:-1}),/option/);await c.close();});
test('readiness preloads explicit future snapshot without changing current game until next go',async()=>{const {createRootKnowledgeCoordinator}=await api(),f=fixture(),c=createRootKnowledgeCoordinator({bookProvider:f.provider,environment:{}});await c.ready();await c.beginGame();await c.configure({name:'BookFile',value:'future.bin'});await c.ready();assert.equal(f.calls.filter(x=>x[0]==='refresh').length,0);const options=Object.fromEntries(c.options.map(o=>[o.name,o.default]));await c.prepare({context,requestId:1,options:{...options,BookFile:'future.bin'}});assert.equal(f.calls.filter(x=>x[0]==='refresh').length,1);await c.close();});

test('managed tablebase process stays prewarmed across games and late raw safety remains a fenced publication constraint',async()=>{const {createRootKnowledgeCoordinator}=await api(),f=fixture();let opens=0,closes=0,abandons=0,result;const root={...context,input:{originFen:'8/8/8/8/8/2k5/8/KQ6 w - - 0 1',moves:[]},legalActions:[577,1153]};const provider={describe(){return {status:'ready',provider_identity:{dataset:{admitted_cardinality:3}}};},probe(){return {read(){return result;},abandon(){abandons++;}};},async close(){closes++;return {provider:{status:'closed',drained:true,failed:false},process:{code:0,signal:null,forced:false},stderr:''};}};const c=createRootKnowledgeCoordinator({bookProvider:f.provider,environment:{},loadTablebaseBinding:async()=>({root:'managed'}),openTablebaseProvider:async()=>{opens++;return provider;}});await c.configure({name:'RootTablebaseBinding',value:'C:/managed/binding.json'});await c.ready();await c.beginGame();await c.onPosition(root);const options=Object.fromEntries(c.options.map(o=>[o.name,o.default]));assert.equal((await c.prepare({context:root,requestId:1,options})).status,'unavailable');result={status:'safety-only',actions:[577],exactAction:null,requestId:'root-1',requestSha256:'a'.repeat(64),providerGeneration:'b'.repeat(32)};const safety=c.publication({context:root,requestId:1});assert.equal(safety?.then,undefined);assert.equal(safety.status,'constrained');assert.deepEqual(safety.actions,[577]);assert.equal(await c.publication({context:{...root,rootFence:[1,2,3,5]},requestId:1}),null);await c.endGame();await c.ready();await c.beginGame();assert.equal(opens,1);assert.equal(closes,0);await c.close();assert.equal(closes,1);assert(abandons>=1);});
test('warming provider never blocks game readiness or grants root proof, and binding is startup-only',async()=>{const {createRootKnowledgeCoordinator}=await api(),f=fixture();let closes=0;const c=createRootKnowledgeCoordinator({bookProvider:f.provider,environment:{},loadTablebaseBinding:async()=>({root:'managed'}),openTablebaseProvider:async()=>({describe:()=>({status:'warming'}),async close(){closes++;return {provider:{status:'closed',drained:true,failed:false},process:{code:0,signal:null,forced:false},stderr:''};}})});await c.configure({name:'RootTablebaseBinding',value:'C:/managed/binding.json'});await c.ready();await c.beginGame();await assert.rejects(c.configure({name:'RootTablebaseBinding',value:'different'}),/game|startup/i);await c.close();assert.equal(closes,1);});
test('accepted exact ticket notifies the active foreground intent and replays without polling or provider poisoning',async()=>{const {createRootKnowledgeCoordinator}=await api(),f=fixture(),root={...context,input:{originFen:'8/8/8/8/8/2k5/8/KQ6 w - - 0 1',moves:[]},legalActions:[577,1153]};let result,changed;const provider={describe:()=>({status:'ready',provider_identity:{dataset:{admitted_cardinality:3}}}),probe:()=>({read:()=>result,subscribe(callback){changed=callback;callback();return()=>{changed=undefined;};},abandon(){changed=undefined;}}),async close(){return {provider:{drained:true,failed:false,status:'closed'},process:{code:0,signal:null,forced:false},stderr:''};}};const c=createRootKnowledgeCoordinator({bookProvider:f.provider,environment:{},loadTablebaseBinding:async()=>({}),openTablebaseProvider:async()=>provider});await c.configure({name:'RootTablebaseBinding',value:'C:/managed/binding.json'});await c.ready();await c.beginGame();await c.onPosition(root);await c.prepare({context:root,requestId:4});const signals=[];const unsubscribe=c.subscribeResolution({context:root,requestId:4},r=>signals.push(r));assert.equal(signals.length,0);result={status:'exact',exactAction:577,actions:[577],requestSha256:'a'.repeat(64),providerGeneration:'b'.repeat(32)};changed();assert.equal(signals[0].authority,'tablebase-exact-root');unsubscribe();const replay=[];c.subscribeResolution({context:root,requestId:4},r=>replay.push(r));assert.equal(replay.length,1);await c.endGame();assert.equal(changed,undefined);await c.close();});

const boundFixture=async(mode='service_managed_live_channel',enabled=true)=>{
 const {createRootKnowledgeCoordinator}=await api(),f=fixture();
 const root=path.resolve('selected-book'),bindingFile=path.resolve('selection.json');
 const files={bookFile:path.join(root,'strong_rare_v1.bin'),statsFile:path.join(root,'strong_rare_v1.stats'),policyFile:path.join(root,'strong_rare_v1.policy'),manifestFile:path.join(root,'snapshot.manifest.json')};
 const doc={schema:'vector_opening_book_binding_v1',schemaVersion:1,authorityMode:mode,capability:'snapshot_v2',selection:{path:root,kind:'opening_book',source:'saved_locator',storageMode:'in_place_reference'},files,pin:mode==='immutable_pinned_snapshot'?{manifestSha256:'a'.repeat(64)}:null};
 const statuses=[],c=createRootKnowledgeCoordinator({bookProvider:f.provider,environment:{},loadBookBinding:async()=>doc,onStatus:r=>{if(r.provider==='opening-book')statuses.push(r.status);}});
 for(const [name,value] of Object.entries({OwnBook:enabled,BookSnapshotBinding:bindingFile,BookFile:files.bookFile,BookStatsFile:files.statsFile,BookPolicyFile:files.policyFile}))await c.configure({name,value});
 await c.ready();await c.beginGame();const options=Object.fromEntries(c.options.map(o=>[o.name,o.default]));Object.assign(options,{OwnBook:enabled,BookSnapshotBinding:bindingFile,BookFile:files.bookFile,BookStatsFile:files.statsFile,BookPolicyFile:files.policyFile});return {...f,c,options,statuses};
};
test('bound active game can disable and reenable its admitted snapshot without reloading',async()=>{
 const f=await boundFixture();assert.equal((await f.c.prepare({context,requestId:1,options:f.options})).status,'resolved');
 assert.equal((await f.c.prepare({context,requestId:2,options:{...f.options,OwnBook:false}})).reason,'disabled');
 assert.equal((await f.c.prepare({context,requestId:3,options:f.options})).status,'resolved');
 assert.equal(f.statuses.at(-1).active,true);assert.equal(f.calls.filter(x=>x[0]==='reload').length,1);assert.equal(f.calls.filter(x=>x[0]==='refresh').length,0);await f.c.close();
});
test('go cannot drop an active game binding and load unrelated defaults',async()=>{
 const f=await boundFixture(),before=f.calls.filter(x=>x[0]==='reload').length;
 const result=await f.c.prepare({context,requestId:1,options:{...f.options,BookSnapshotBinding:'',BookMaxPly:20}});
 assert.equal(result.status,'unavailable');assert.equal(result.reason,'book_binding_unavailable');assert.equal(f.calls.filter(x=>x[0]==='reload').length,before);
 assert.equal((await f.c.prepare({context,requestId:2,options:f.options})).status,'resolved');await f.c.close();
});
test('initially disabled bound game cannot activate a new generation until next game readiness',async()=>{
 const f=await boundFixture('service_managed_live_channel',false);
 assert.equal((await f.c.prepare({context,requestId:1,options:{...f.options,OwnBook:true}})).status,'unavailable');assert.equal(f.calls.filter(x=>x[0]==='reload').length,0);
 await f.c.endGame();await f.c.configure({name:'OwnBook',value:true});await f.c.ready();await f.c.beginGame();assert.equal((await f.c.prepare({context,requestId:2,options:{...f.options,OwnBook:true}})).status,'resolved');await f.c.close();
});
