import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import {createGameSearchPort} from '../../components/engine-runtime/game-search-port.mjs';
import {openRootTablebaseProvider} from '../../components/root-knowledge/tablebase-process.mjs';
import {uciToAction} from '../../components/uci-protocol/index.mjs';
test('actual admitted GPU root consumes exact external root proof through pinned public JSONL transport',{skip:process.env.VECTOR_TB_CONSUMER_NATIVE!=='1'},async()=>{
 assert.equal(process.version,'v26.11.1');const port=createGameSearchPort({modelRoot:process.env.VECTOR_UCI_MODEL_ROOT,revision:process.env.VECTOR_UCI_SOURCE_REVISION,cacheDirectory:process.env.VECTOR_UCI_COMPILER_CACHE}),record={schema:'vector_root_tablebase_consumer_observation_v1',status:'pending',sourceRevision:process.env.VECTOR_UCI_SOURCE_REVISION,rootOnly:true,internalGpuTablebaseQualified:false,timingPolicyQualified:false};let provider,ticket;
 try{provider=await openRootTablebaseProvider({root:process.env.VECTOR_TB_PACKAGE_ROOT,manifestSha256:'4836c59f5c2f0f2f4ac2be0b6016dc951586d7d482b8b18b17dc00435444189f',contractSha256:'a7b0ec1bb92cade126316cd49751ae40bc139b6e96f73dc64183140ba4ec0b7b',configPath:process.env.VECTOR_TB_CONFIG});record.provider=provider.describe();record.identity=await port.ready();await port.admitPosition({fen:'7k/8/5KQ1/8/8/8/8/8 w - - 0 1',moves:[],rootEpoch:1});const context=port.readRootKnowledgeContext();assert(context&&!context.terminal);record.context=context;const action=uciToAction('g6g7');assert(context.legalActions.includes(action));ticket=provider.probe({context,requestId:'actual-gpu-mate-1',searchmoves:[action],limits:{max_nodes:32,max_depth:128,max_milliseconds:1000}});const start=performance.now();let proof;for(;;){proof=ticket.read(context);if(proof?.status==='exact')break;if(performance.now()-start>3000)throw new Error('Bounded exact root proof unavailable');await new Promise(r=>setTimeout(r,5));}assert.equal(proof.exactAction,action);record.proof=proof;await port.requestPublication({rootEpoch:1,requestId:1,searchmoves:proof.actions});record.publication=port.readPublication({rootEpoch:1,requestId:1});assert.equal(record.publication.action,action);assert.equal(record.publication.legalProof.legal,true);record.status='pass';}
 catch(error){record.status='fail';record.failure=error.message;record.providerFailure=error.providerFailure;throw error;}
 finally{ticket?.abandon();try{record.gpuTeardown=await port.close();record.providerTeardown=await provider?.close();if(record.identity)assert.equal(record.gpuTeardown.cleanup.runtime.driver.resourceCounts.live,0);else assert.equal(record.gpuTeardown.noActiveRuntime,true);if(provider)assert.equal(record.providerTeardown.provider.drained,true);}catch(error){record.status='fail';record.closeFailure=error.message;throw error;}finally{if(process.env.VECTOR_TB_NATIVE_RECEIPT)fs.writeFileSync(process.env.VECTOR_TB_NATIVE_RECEIPT,JSON.stringify(record,null,2)+'\n',{flag:'wx'});}}
});
