import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createHash} from 'node:crypto';
import {EventEmitter} from 'node:events';
import {PassThrough,Writable} from 'node:stream';
const sha=b=>createHash('sha256').update(b).digest('hex');
async function api(){try{return await import('../../components/root-knowledge/tablebase-process.mjs');}catch(e){if(e.code==='ERR_MODULE_NOT_FOUND')assert.fail('Inventoried public provider transport is missing');throw e;}}
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'vector-tb-admission-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const file=Buffer.from('closed provider test payload'),contract=Buffer.from(JSON.stringify({schema:'uci_arena_root_knowledge_contract_v2',version:'2.0.0',transport:{maximum_frame_bytes:262208,maximum_output_bytes:1048576},launch:{executable:'provider.exe',arguments:[],working_directory:'.'}}));await fs.mkdir(path.join(root,'contracts'));await fs.writeFile(path.join(root,'provider.exe'),file);await fs.writeFile(path.join(root,'contracts/offline-root-knowledge-v2.json'),contract);const manifest={schema:'uci_arena_root_provider_package_v1',files:[{path:'provider.exe',bytes:file.length,sha256:sha(file)},{path:'contracts/offline-root-knowledge-v2.json',bytes:contract.length,sha256:sha(contract)}]},bytes=Buffer.from(JSON.stringify(manifest));await fs.writeFile(path.join(root,'package-manifest.json'),bytes);return {root,manifest,manifestSha256:sha(bytes),contractSha256:sha(contract)};}
test('external provider cold admission hashes the complete public inventory before launch',async t=>{const {admitRootTablebasePackage}=await api(),f=await fixture(t),p=await admitRootTablebasePackage(f);assert.equal(p.manifestSha256,f.manifestSha256);assert.equal(p.contractSha256,f.contractSha256);assert.equal(p.fileCount,2);await fs.writeFile(path.join(f.root,'provider.exe'),'changed');await assert.rejects(admitRootTablebasePackage(f),/inventory|digest|extent/i);});
test('provider inventory rejects traversal duplicate roles and linked executable paths before opening process',async t=>{const {admitRootTablebasePackage}=await api(),f=await fixture(t);for(const files of [[{...f.manifest.files[0],path:'../provider.exe'}],[f.manifest.files[0],f.manifest.files[0]]]){const bytes=Buffer.from(JSON.stringify({...f.manifest,files}));await fs.writeFile(path.join(f.root,'package-manifest.json'),bytes);await assert.rejects(admitRootTablebasePackage({...f,manifestSha256:sha(bytes)}),/path|duplicate/i);}});
test('provider admission preserves requested linked ancestor evidence',async t=>{const {admitRootTablebasePackage}=await api(),f=await fixture(t);const alias=path.join(f.root,'linked-root');await fs.symlink(f.root,alias,process.platform==='win32'?'junction':'dir');await assert.rejects(admitRootTablebasePackage({...f,root:alias}),/linked/i);});
test('root provider public transport binds readiness and actual close without conflating exit zero with drained ownership',async t=>{const {openRootTablebaseProvider}=await api(),f=await fixture(t);const config=path.join(f.root,'config.json');await fs.writeFile(config,'{}');const spawnProcess=()=>{const p=new EventEmitter();p.stdout=new PassThrough();p.stderr=new PassThrough();p.kill=()=>false;p.stdin=new Writable({write(bytes,_encoding,done){const q=JSON.parse(bytes.toString());if(q.operation==='describe')p.stdout.write(JSON.stringify({schema:'uci_arena_syzygy_root_transport_v1',operation:'describe',status:'ready',provider_generation:'a'.repeat(32),provider_identity:{package:{manifest_sha256:f.manifestSha256}},profile:{root_only:true,worker_count:1,ticket_capacity:2,request_schema:'uci_arena_syzygy_root_request_v2'}})+'\n');if(q.operation==='close'){p.stdout.end(JSON.stringify({schema:'uci_arena_syzygy_root_transport_v1',operation:'close',status:'closed',drained:true,failed:false,provider_generation:'a'.repeat(32)})+'\n');setImmediate(()=>p.emit('close',0,null));}done();}});return p;};const provider=await openRootTablebaseProvider({...f,configPath:config,spawnProcess});assert.equal(provider.describe().provider_generation,'a'.repeat(32));const closed=await provider.close();assert.deepEqual(closed.process,{code:0,signal:null,forced:false});assert.equal(closed.provider.drained,true);assert.equal(await provider.close(),closed);});
test('cold provider failure preserves process exit and bounded stderr as first cause',async t=>{const {openRootTablebaseProvider}=await api(),f=await fixture(t),config=path.join(f.root,'config.json');await fs.writeFile(config,'{}');const spawnProcess=()=>{const p=new EventEmitter();p.stdout=new PassThrough();p.stderr=new PassThrough();p.kill=()=>false;p.stdin=new Writable({write(_b,_e,done){setImmediate(()=>{p.stderr.write('public-config-rejected');p.emit('close',7,null);});done();}});return p;};await assert.rejects(openRootTablebaseProvider({...f,configPath:config,spawnProcess}),e=>e.providerFailure?.process.code===7&&e.providerFailure.stderr==='public-config-rejected');});
test('a later malformed provider frame cannot silently remove already completed raw safety constraints',async t=>{const {openRootTablebaseProvider}=await api(),{canonicalJson}=await import('../../components/root-knowledge/tablebase.mjs'),f=await fixture(t),config=path.join(f.root,'config.json');await fs.writeFile(config,'{}');const identity={package:{manifest_sha256:f.manifestSha256}},generation='a'.repeat(32),spawnProcess=()=>{const p=new EventEmitter();p.stdout=new PassThrough();p.stderr=new PassThrough();p.kill=()=>false;p.stdin=new Writable({write(bytes,_encoding,done){const q=JSON.parse(bytes.toString());if(q.operation==='describe')p.stdout.write(JSON.stringify({schema:'uci_arena_syzygy_root_transport_v1',operation:'describe',status:'ready',provider_generation:generation,provider_identity:identity,profile:{root_only:true,worker_count:1,ticket_capacity:2,request_schema:'uci_arena_syzygy_root_request_v2',claim_policies:{'orthodoxy-live-claims-v1':{rule50:[true]}}}})+'\n');if(q.operation==='probe'){const r=q.request;p.stdout.write(JSON.stringify({schema:'uci_arena_syzygy_root_result_v2',request_id:r.request_id,root_fence:r.root_fence,request_sha256:sha(canonicalJson(r)),provider_generation:generation,provider_identity:identity,sequence:0,rules:r.rules,status:'safety_only',safe_moves:['b1b2'],raw:{zero_clock_abstraction:true,wdl:2,rows:[{move:'b1b2',wdl:2,result_class:1},{move:'b1c3',wdl:0,result_class:0}]},authority:{raw_wdl_safety:true,history_adjusted:false,exact_move:false},move:null,result_class:null,refinement:{status:'pending'}})+'\n');p.stdout.write('{broken}\n');setImmediate(()=>p.emit('close',7,null));}done();}});return p;};const provider=await openRootTablebaseProvider({...f,configPath:config,spawnProcess}),context={schema:'vector_root_knowledge_context_v1',claimPolicy:'orthodoxy-live-claims-v1',rootEpoch:1,rootFence:[1,2,3,4],input:{originFen:'8/8/8/8/8/2k5/8/KQ6 w - - 0 1',moves:[]},legalActions:[577,1153]},ticket=provider.probe({context,requestId:'r1'});assert.deepEqual(ticket.read(context)?.actions,[577]);assert.equal(ticket.read(context).exactAction,null);await assert.rejects(provider.close(),/JSON|broken|property|Expected/);});
