import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash} from 'node:crypto';
const context={schema:'vector_root_knowledge_context_v1',claimPolicy:'orthodoxy-live-claims-v1',rootEpoch:1,rootFence:[1,2,3,4],input:{originFen:'8/8/8/8/8/2k5/8/KQ6 w - - 0 1',moves:[]},legalActions:[577,1153]};
const identity={package:{manifest_sha256:'a'.repeat(64)},dataset:{admitted_cardinality:3,scope:'exact_selected_file_set'}};
const description={schema:'uci_arena_syzygy_root_transport_v1',operation:'describe',status:'ready',provider_generation:'b'.repeat(32),provider_identity:identity,profile:{root_only:true,worker_count:1,ticket_capacity:2,request_schema:'uci_arena_syzygy_root_request_v2',claim_policies:{'orthodoxy-live-claims-v1':{rule50:[true]}}}};
async function api(){try{return await import('../../components/root-knowledge/tablebase.mjs');}catch(e){if(e.code==='ERR_MODULE_NOT_FOUND')assert.fail('Typed root tablebase consumer is missing');throw e;}}
const raw=(ticket)=>({schema:'uci_arena_syzygy_root_result_v2',request_id:ticket.request.request_id,root_fence:ticket.request.root_fence,request_sha256:ticket.requestSha256,provider_generation:description.provider_generation,provider_identity:identity,sequence:0,rules:ticket.request.rules,status:'safety_only',safe_moves:['b1b2'],raw:{zero_clock_abstraction:true,wdl:2,rows:[{move:'b1b2',wdl:2,result_class:1},{move:'b1c3',wdl:0,result_class:0}]},authority:{raw_wdl_safety:true,history_adjusted:false,exact_move:false},move:null,result_class:null,refinement:{status:'pending'}});
test('tablebase request preserves only the admitted GPU root authority and explicit live claims',async()=>{const {createTablebaseTicket,canonicalJson}=await api(),ticket=createTablebaseTicket({context,requestId:'r1',description});assert.equal(ticket.request.root_fence,'00000001000000020000000300000004');assert.deepEqual(ticket.request.legal_moves,['b1b2','b1c3']);assert.equal(ticket.request.rules.claim_policy,'orthodoxy-live-claims-v1');assert.equal(ticket.requestSha256,createHash('sha256').update(canonicalJson(ticket.request)).digest('hex'));assert.equal(ticket.request.history_mode,'replay-from-origin');assert.throws(()=>createTablebaseTicket({context:{...context,claimPolicy:'adjudicated-claims-as-draw'},requestId:'r2',description}),/claim/);});
test('complete raw safety constrains only current GPU publication and never becomes exact move proof',async()=>{const {createTablebaseTicket}=await api(),ticket=createTablebaseTicket({context,requestId:'r1',description});ticket.accept(raw(ticket));assert.deepEqual(ticket.read(context),{status:'safety-only',actions:[577],exactAction:null,requestId:'r1',requestSha256:ticket.requestSha256,providerGeneration:description.provider_generation});assert.equal(ticket.read({...context,rootFence:[1,2,3,5]}),null);ticket.abandon();assert.equal(ticket.read(context),null);});
test('tablebase rejects stale identity, digest, broadened subset and virtual claim move authority',async()=>{const {createTablebaseTicket}=await api();for(const change of [{root_fence:'c'.repeat(32)},{request_sha256:'c'.repeat(64)},{provider_generation:'c'.repeat(32)},{provider_identity:{...identity,dataset:{admitted_cardinality:6}}}]){const t=createTablebaseTicket({context,requestId:'r1',description});assert.throws(()=>t.accept({...raw(t),...change}),/binding/);}const t=createTablebaseTicket({context,requestId:'r1',description});t.accept(raw(t));assert.throws(()=>t.accept({...raw(t),sequence:1,safe_moves:['b1b2','b1c3']}),/broaden|safety/);const virtual=createTablebaseTicket({context,requestId:'r1',description});virtual.accept(raw(virtual));virtual.accept({...raw(virtual),sequence:1,refinement:{status:'deferred',reason:'claim_action_required'}});assert.equal(virtual.read(context).exactAction,null);});
test('complete exact proof stays within raw safety and closed allowed action set',async()=>{const {createTablebaseTicket}=await api(),t=createTablebaseTicket({context,requestId:'r1',description});t.accept(raw(t));t.accept({...raw(t),sequence:1,status:'exact',authority:{raw_wdl_safety:true,history_adjusted:true,exact_move:true},move:'b1b2',result_class:1,refinement:{status:'complete',metric:'reversible-minimax-plies-to-zeroing-or-mate',rows:[{move:'b1b2',result_class:1,boundary_plies:1},{move:'b1c3',result_class:0,boundary_plies:0}]}});assert.equal(t.read(context).exactAction,577);assert.throws(()=>t.accept({...raw(t),sequence:1}),/sequence/);});
test('published tablebase request bytes cannot mutate after digest admission',async()=>{const {createTablebaseTicket}=await api(),t=createTablebaseTicket({context,requestId:'r1',description});assert.throws(()=>t.request.rules.claim_policy='adjudicated-claims-as-draw',TypeError);assert.throws(()=>t.request.position.moves.push('b1b2'),TypeError);assert.equal(t.requestSha256,createHash('sha256').update((await api()).canonicalJson(t.request)).digest('hex'));});
test('rule50 WDL mapping rejects a losing raw row falsely marked winning and rejects undeclared request punctuation',async()=>{const {createTablebaseTicket}=await api(),t=createTablebaseTicket({context,requestId:'r1',description}),bad=raw(t);bad.raw.rows[0].wdl=-2;assert.throws(()=>t.accept(bad),/class|safety/);assert.throws(()=>createTablebaseTicket({context,requestId:'r:1',description}),/identity/);});
test('exact refinement requires complete class and distance rank with canonical outcome-first tie choice',async()=>{const {createTablebaseTicket}=await api();const event=t=>({...raw(t),sequence:1,status:'exact',authority:{raw_wdl_safety:true,history_adjusted:true,exact_move:true},move:'b1b2',result_class:1,refinement:{status:'complete',metric:'reversible-minimax-plies-to-zeroing-or-mate',rows:[{move:'b1b2',result_class:1,boundary_plies:1},{move:'b1c3',result_class:0,boundary_plies:0}]}});for(const mutate of [e=>e.refinement.rows[0].result_class=2,e=>e.refinement.rows[0].boundary_plies=Infinity,e=>e.refinement.metric='rounded-dtz',e=>e.result_class=0,e=>e.refinement.rows[1].result_class=1]){const t=createTablebaseTicket({context,requestId:'r1',description});t.accept(raw(t));const bad=event(t);mutate(bad);assert.throws(()=>t.accept(bad),/proof|rank|class|metric/);assert.deepEqual(t.read(context).actions,[577]);}});
test('failure after completed raw safety retains only immutable fenced safety and cannot grant later exact proof',async()=>{const {createTablebaseTicket}=await api(),t=createTablebaseTicket({context,requestId:'r1',description});t.accept(raw(t));t.fail();assert.deepEqual(t.read(context).actions,[577]);assert.equal(t.read(context).failureDisposition,'completed-raw-safety-retained');assert.equal(t.read(context).exactAction,null);assert.equal(t.read({...context,rootFence:[1,2,3,5]}),null);t.abandon();assert.equal(t.read(context),null);});
