import assert from 'node:assert/strict';
import test from 'node:test';
import {createGameSearchPort} from '../../components/engine-runtime/game-search-port.mjs';
import {STATE_WORDS} from '../../components/chess-domain/admission.mjs';
import {createHash} from 'node:crypto';
import {preparationFailure,finishPreparedInitialization} from '../../components/engine-runtime/preparation-ownership.mjs';
const fen='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
function refreshScheduler(){const pending=new Map();let serial=0;return{schedulePublicationRefresh:fn=>{const id=++serial;pending.set(id,fn);return id;},cancelPublicationRefresh:id=>pending.delete(id),async fire(){const entry=pending.entries().next().value;assert(entry,'Background refresh not scheduled');pending.delete(entry[0]);entry[1]();for(let i=0;i<30;i++)await Promise.resolve();},size:()=>pending.size};}
const noKnowledge=()=>({options:[],hasOption:()=>false,async ready(){},async beginGame(){},async endGame(){},async close(){},async prepare(){return{status:'unavailable'};}});
function holdObserver(f){const original=f.backend.prepared.submitExternal.bind(f.backend.prepared);let hold=true,release,entered;const entering=new Promise(r=>entered=r),held=new Promise(r=>release=r);f.backend.prepared.submitExternal=async(...args)=>{const c=await original(...args);if(args[0]==='operation-5'&&hold){hold=false;return{...c,async wait(){entered();await held;return c.wait();}};}return c;};return{entering,release};}
function fixture(){
 const calls=[],commands=[],restrictions=[],command={phase:0,result:1,kind:2,expectedArena:3,expectedFocusEpoch:4,expectedRootSlot:5,expectedRootGeneration:6,idBase:8,generationBase:12,responseRootSlot:16,responseRootGeneration:17,responseFocusEpoch:18,stateWords:20,admissionActionCount:21,actionWords:22,stateBase:32,kinds:{admit:1,readyAdvance:2,cancel:3},phases:{uploading:1,pending:2,acknowledged:3},results:{accepted:0,pressure:2,advanceNotReady:6,stale:5}};
 const core={layout:{stateWords:STATE_WORDS,actionWords:1,maxAdmissionActions:4096,maxActions:256},protocol:{command,packetWords:32+STATE_WORDS+4096,bootstrap:{wordCount:4,status:0,rootSlot:1,rootGeneration:2,focusEpoch:3,acceptedStatus:0},observer:{status:0,statuses:{ready:0,invalid:1,unavailable:3},authority:{arena:2,root:3,generation:4,epoch:5},actionCount:6,terminal:7,selectedActionBase:12,rowsBase:32,rowWords:6},telemetry:{},terminal:{headerWords:32,identityWords:4,fields:{acceptedCommandIdBase:24,acceptedCommandGenerationBase:28},quiescence:{zeroFields:[12,13,14,15,16,21,22],equalPairs:[[17,18],[19,20]]}}},operationIds:{bootstrap:'boot',command:'cmd',observer:'observe'},delivery:{id:'terminal'},programResources:[{id:'gpu',materialization:'resident-storage',capacity:String((32+STATE_WORDS+4096)*4)}],buffers:[{name:'initialRootInput',source:{resource:'gpu'},byteOffset:0,byteLength:(32+STATE_WORDS+4096)*4}]};
 let epoch=1,cancel,stale=false,unavailable=0,advanceResult=0,legal=[796],selected,terminal=false;
 const prepared={async describe(){return{};},async ignite(input){assert(!Object.hasOwn(input,'resources'),'Cold full images must be preinitialized before readiness');assert(input.initializationParameters['operation-3'].initialRootInput instanceof Uint8Array);calls.push('ignite');return {initializationResults:[{bytes:new Uint8Array(new Uint32Array([0,3,4,epoch]).buffer)}]};},async submitExternal(op,input){calls.push(op);let w;
  if(op==='operation-4'){const packet=new Uint32Array(input.parameters.commandStage.buffer);commands.push({kind:packet[2],stateWords:packet[20],actions:[...packet.slice(32+STATE_WORDS,32+STATE_WORDS+packet[21])]});w=new Uint32Array(32);w[0]=3;w.set(packet.slice(8,16),8);if(packet[2]===3)cancel={id:[...packet.slice(8,12)],generation:[...packet.slice(12,16)]};else if(packet[2]===2&&advanceResult)w[1]=advanceResult;else epoch++;w[16]=3;w[17]=4;w[18]=epoch;
  }else{const r=new Uint32Array(input.parameters.restriction.buffer),allowed=[...r.slice(1,1+r[0])];restrictions.push(allowed);w=new Uint32Array(1568);if(unavailable>0){w[0]=3;unavailable--;}w[2]=input.scalars.arena;w[3]=stale?9:3;w[4]=4;w[5]=epoch;w[6]=legal.length;w[7]=terminal?1:0;w[12]=allowed.length?(allowed.includes(selected)?selected:allowed[0]):selected??legal[0];legal.forEach((a,i)=>w[32+i*6]=a);}
  return {async wait(){},async deliver(){return {bytes:new Uint8Array(w.buffer)};},async close(){calls.push('child-close');}};
 },async wait(){calls.push('join');},async deliver(){const w=new Uint32Array(32);w.set(cancel.id,24);w.set(cancel.generation,28);return {bytes:new Uint8Array(w.buffer)};},async close(){calls.push('close');return {status:'complete',failures:[],runtime:{graceful:true,driver:{resourceCounts:{live:0,orphaned:0}}}};}};
 const requirements={resourceRequirements:[{id:'resource-0',byteLength:String(core.buffers[0].byteLength)}],operationRequirements:[{bindings:[{parameter:'initialRootInput',source:{kind:'resource',resource:'resource-0',view:{dtype:'u32',byteOffset:'0',elementCount:String(core.protocol.packetWords)}}}]}],deliveryRequirements:[]};
 const backend={core,requirements,ports:{operationIds:{bootstrap:'operation-3',command:'operation-4',observer:'operation-5'},deliveryId:'delivery-0'},prepared,assets:{},selected:{artifactBindings:{}},cold:{model:{connector:{parameters:[]}}},description:{admission:{realization:'prepared'}}};
 return {calls,commands,restrictions,backend,setLegal(v){legal=v;},setSelected(v){selected=v;},setTerminal(v){terminal=v;},setAdvanceResult(v){advanceResult=v;},setUnavailable(n){unavailable=n;},setStale(){stale=true;},async prepare({modelRoot}){if(modelRoot.endsWith('bad'))throw preparationFailure(new Error('Rejected model'),'not-opened');return backend;}};
}
test('protocol adapter ignites once, observes GPU-selected rows and joins exact cancel before close',async()=>{
 const f=fixture(),p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare});await p.ready();await p.admitPosition({fen,moves:[],rootEpoch:1});assert.equal(p.readRootKnowledgeContext().rootEpoch,1);assert.equal(p.readPublication({rootEpoch:1,requestId:1}),null);await p.requestPublication({rootEpoch:1,requestId:1});assert.equal(p.readPublication({rootEpoch:1,requestId:1}).action,796);assert.equal(p.readPublication({rootEpoch:2,requestId:1}),null);assert.deepEqual(p.readRootKnowledgeContext().rootFence,[1,3,4,1]);assert.deepEqual(p.readRootKnowledgeContext().legalActions,[796]);
 await p.admitPosition({fen,moves:[],rootEpoch:2});assert.equal(p.readRootKnowledgeContext().rootEpoch,2);assert.equal(f.calls.filter(c=>c==='ignite').length,1);await p.close();assert(f.calls.indexOf('join')<f.calls.indexOf('close'));assert.equal(p.readRootKnowledgeContext(),null);await p.close();assert.equal(f.calls.filter(c=>c==='close').length,1);
});
test('rejected replacement preserves configuration and background stale authority fails closed with actual cleanup',async()=>{
 const f=fixture(),scheduler=refreshScheduler(),p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,...scheduler}),identity=await p.ready();await assert.rejects(p.configure({name:'ModelRoot',value:'bad'}),/Rejected model/);assert.equal(await p.ready(),identity);assert.equal(f.calls.includes('close'),false);await p.admitPosition({fen,moves:[],rootEpoch:1});f.setStale();await scheduler.fire();assert.throws(()=>p.requestPublication({rootEpoch:1,requestId:1}),/authority/);await assert.rejects(p.close(),/publication/i);assert(f.calls.includes('join'));assert(f.calls.includes('close'));
});
test('close waits for delayed readiness admission and disposes the returned candidate',async()=>{
 const f=fixture();let release,entered;const entering=new Promise(resolve=>entered=resolve),held=new Promise(resolve=>release=resolve);
 const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:async()=>{entered();await held;return f.backend;}});
 const readiness=p.ready();await entering;let settled=false;const closing=p.close().then(report=>{settled=true;return report;});await new Promise(resolve=>setImmediate(resolve));assert.equal(settled,false);release();await assert.rejects(readiness,/closed/);const report=await closing;assert.equal(f.calls.filter(c=>c==='close').length,1);assert.notEqual(report.noRuntimeOpened,true);await assert.rejects(p.ready(),/closed/);
});
test('close waits for delayed replacement and releases candidate without replacing closed owner',async()=>{
 const old=fixture(),next=fixture();let release,entered;const entering=new Promise(resolve=>entered=resolve),held=new Promise(resolve=>release=resolve);
 const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:async({modelRoot})=>{if(modelRoot.endsWith('replacement')){entered();await held;return next.backend;}return old.backend;}});
 await p.ready();const replacement=p.configure({name:'ModelRoot',value:'replacement'});await entering;let settled=false;const closing=p.close().then(report=>{settled=true;return report;});await new Promise(resolve=>setImmediate(resolve));assert.equal(settled,false);release();await assert.rejects(replacement,/closed/);await closing;assert.equal(next.calls.filter(c=>c==='close').length,1);assert.equal(old.calls.filter(c=>c==='close').length,1);await assert.rejects(p.ready(),/closed/);
});
test('delayed replacement cannot retire a game admitted while candidate preparation was pending',async()=>{
 const old=fixture(),next=fixture();let release,entered;const entering=new Promise(resolve=>entered=resolve),held=new Promise(resolve=>release=resolve);
 const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:async({modelRoot})=>{if(modelRoot.endsWith('replacement')){entered();await held;return next.backend;}return old.backend;}});
 await p.ready();const replacement=p.configure({name:'ModelRoot',value:'replacement'});await entering;await p.admitPosition({fen,moves:[],rootEpoch:1});release();await assert.rejects(replacement,/game/);assert.equal(old.calls.includes('close'),false);assert.equal(next.calls.filter(c=>c==='close').length,1);await p.close();assert.equal(old.calls.filter(c=>c==='ignite').length,1);
});

test('quit after a joined game retirement declares no active runtime and retains the proved close',async()=>{
 const f=fixture(),p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare});await p.ready();await p.admitPosition({fen,moves:[],rootEpoch:1});const retired=await p.endGame();assert.equal(retired.joined,true);const report=await p.close();assert.equal(report.noActiveRuntime,true);assert.equal(report.noRuntimeOpened,false);assert.equal(report.gameTeardowns.length,1);assert.equal(report.gameTeardowns[0],retired);assert.equal(f.calls.filter(c=>c==='close').length,1);
});

test('closure journal retains bounded recent proof after seventy games with finite historical disposition',async()=>{
 const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:async()=>fixture().backend});for(let i=0;i<70;i++){await p.ready();await p.admitPosition({fen,moves:[],rootEpoch:i+1});await p.endGame();}const report=await p.close();assert.equal(report.gameTeardowns.length,8);assert.equal(report.closureJournal.capacity,8);assert.equal(report.closureJournal.totalRetirements,70);assert.equal(report.closureJournal.totalJoined,70);assert.equal(report.closureJournal.evictedRetirements,62);assert.equal(report.closureJournal.evictedJoined,62);assert.match(report.closureJournal.chainSha256,/^[0-9a-f]{64}$/);assert.equal(report.noActiveRuntime,true);assert(JSON.stringify(report).length<32768);
});

test('temporary protected-slot unavailability preserves completed cache after finite read-only retry bound',async()=>{
 const f=fixture(),scheduler=refreshScheduler(),p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,...scheduler});await p.admitPosition({fen,moves:[],rootEpoch:1});f.setUnavailable(2);await scheduler.fire();p.requestPublication({rootEpoch:1,requestId:1});const complete=p.readPublication({rootEpoch:1,requestId:1});assert.equal(complete.timing.attempts,3);f.setUnavailable(3);await scheduler.fire();p.requestPublication({rootEpoch:1,requestId:2});assert.equal(p.readPublication({rootEpoch:1,requestId:2}).sourceObservation.sequence,complete.sourceObservation.sequence);assert.equal(f.calls.filter(c=>c==='ignite').length,1);await p.close();
});

test('retained closure chain independently recomputes from the declared predecessor anchor',async()=>{
 const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:async()=>fixture().backend});for(let i=0;i<10;i++){await p.ready();await p.admitPosition({fen,moves:[],rootEpoch:i+1});await p.endGame();}const r=await p.close();assert.match(r.closureJournal.retainedPredecessorSha256,/^[0-9a-f]{64}$/);assert.notEqual(r.closureJournal.retainedPredecessorSha256,'0'.repeat(64));let hash=r.closureJournal.retainedPredecessorSha256;for(const receipt of r.gameTeardowns)hash=createHash('sha256').update(hash).update(JSON.stringify(receipt)).digest('hex');assert.equal(hash,r.closureJournal.chainSha256);
});
test('root knowledge resolves one fenced move against existing canonical GPU legal proof',async()=>{
 const f=fixture(),knowledge={options:[{name:'OwnBook',type:'check',default:true,apply:'next-go'}],hasOption:n=>n==='OwnBook',async ready(){},async beginGame(){},async endGame(){},async close(){},async configure(){},async prepare({context}){return {status:'resolved',authority:'book-resolved',action:796,rootEpoch:context.rootEpoch,rootFence:context.rootFence};}},p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,knowledge});await p.admitPosition({fen,moves:[],rootEpoch:1});assert.equal((await p.preparePublicationIntent({rootEpoch:1,requestId:1,options:{OwnBook:true}})).bypassPublicationWait,true);await p.requestPublication({rootEpoch:1,requestId:1});assert.equal(p.readPublication({rootEpoch:1,requestId:1}).action,796);await p.close();
});
test('cached GPU readiness still admits pending provider configuration before readyok',async()=>{
 const f=fixture();let reads=0;const knowledge={options:[{name:'OwnBook',type:'check',default:true,apply:'next-go'}],hasOption:n=>n==='OwnBook',async ready(){reads++;},async endGame(){},async close(){},async configure(){}};const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,knowledge});await p.ready();await p.configure({name:'OwnBook',value:false});await p.ready();assert.equal(reads,2);assert.equal(f.calls.includes('close'),false);await p.close();
});
test('observer timing separates only public submit wait delivery and close phases without inventing polling facts',async()=>{const f=fixture(),p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare});await p.admitPosition({fen,moves:[],rootEpoch:1});await p.requestPublication({rootEpoch:1,requestId:1});const t=p.readPublication({rootEpoch:1,requestId:1}).timing;assert.equal(t.schema,'vector_public_observer_timing_v1');for(const field of ['submitMilliseconds','waitMilliseconds','deliveryMilliseconds','closeMilliseconds'])assert(t[field]>=0&&Number.isFinite(t[field]));assert.deepEqual(t.pollCount,{status:'not-published'});await p.close();});

test('neutral applicability preserves resolved and constrained authority classes',async()=>{
 const f=fixture(),p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare});try{await p.admitPosition({fen,moves:[],rootEpoch:1});const intent=await p.preparePublicationIntent({rootEpoch:1,requestId:1});assert.equal(intent.applicability,'resolved_without_search_time');assert.equal(intent.resolutionKind,'objective-no-choice');}finally{await p.close();}
 const g=fixture();g.setLegal([796,577]);const knowledge={options:[],async ready(){},async beginGame(){},async endGame(){},async close(){},async prepare({context}){return{status:'constrained',authority:'tablebase-raw-wdl-root',actions:[577],rootEpoch:context.rootEpoch,rootFence:context.rootFence};}};
 const q=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:g.prepare,knowledge});try{await q.admitPosition({fen,moves:[],rootEpoch:1});const intent=await q.preparePublicationIntent({rootEpoch:1,requestId:1});assert.equal(intent.applicability,'constrained_search');assert.equal(intent.bypassPublicationWait,false);}finally{await q.close();}
});

test('canonical sole legal action resolves immediately without consulting Book or allocating search wait',async()=>{const f=fixture();let consulted=0;const knowledge={options:[],async ready(){},async beginGame(){},async endGame(){},async close(){},async prepare(){consulted++;return {status:'unavailable'};}};const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,knowledge});await p.admitPosition({fen,moves:[],rootEpoch:1});assert.equal((await p.preparePublicationIntent({rootEpoch:1,requestId:1})).bypassPublicationWait,true);assert.equal(consulted,0);await p.requestPublication({rootEpoch:1,requestId:1});assert.equal(p.readPublication({rootEpoch:1,requestId:1}).action,796);await assert.rejects(p.preparePublicationIntent({rootEpoch:1,requestId:2,searchmoves:[577]}),/restriction|legal/);await p.close();});
test('a single WDL-safe candidate from a larger legal set is not objective no-choice resolution',async()=>{const f=fixture();f.setLegal([796,577]);const knowledge={options:[],async ready(){},async beginGame(){},async endGame(){},async close(){},async prepare(){return {status:'safety-only',actions:[796]};}};const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,knowledge});await p.admitPosition({fen,moves:[],rootEpoch:1});assert.equal((await p.preparePublicationIntent({rootEpoch:1,requestId:1})).bypassPublicationWait,false);await p.close();});
test('one exact origin-prefix successor uses only public readyAdvance and one packed action',async()=>{const f=fixture(),p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare});await p.admitPosition({fen,moves:[],rootEpoch:1});const admitted=await p.admitPosition({fen,moves:[796],rootEpoch:2});assert.deepEqual(f.commands,[{kind:2,stateWords:0,actions:[796]}]);assert.equal(admitted.observation.admission.route,'ready-advance');assert.equal(f.calls.filter(c=>c==='ignite').length,1);await p.close();});
test('only typed advance-not-ready falls back to general GPU replay; stale rejection remains fatal',async()=>{const f=fixture(),p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare});await p.admitPosition({fen,moves:[],rootEpoch:1});f.setAdvanceResult(6);await p.admitPosition({fen,moves:[796],rootEpoch:2});assert.deepEqual(f.commands.map(c=>c.kind),[2,1]);f.setAdvanceResult(5);await assert.rejects(p.admitPosition({fen,moves:[796,577],rootEpoch:3}),/rejected/);assert.deepEqual(f.commands.map(c=>c.kind),[2,1,2]);await p.close();});
test('changed origin or non-prefix moves use general admission without assumed exact-position reuse',async()=>{const f=fixture(),p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare});await p.admitPosition({fen,moves:[796],rootEpoch:1});await p.admitPosition({fen,moves:[577,796],rootEpoch:2});await p.admitPosition({fen:fen.replace('0 1','0 2'),moves:[577,796,796],rootEpoch:3});assert.deepEqual(f.commands.map(c=>c.kind),[1,1]);await p.close();});
test('late completed raw safety invalidates an incompatible sample until background restricted output completes',async()=>{const f=fixture(),scheduler=refreshScheduler();f.setLegal([796,577]);let context,result,onPosition=0;const knowledge={...noKnowledge(),async close(){return {schema:'proved-provider-close'};},async onPosition(c){context=c;onPosition++;},publication(){return result;}};const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,knowledge,...scheduler});await p.admitPosition({fen,moves:[],rootEpoch:1});assert.equal(onPosition,1);await p.preparePublicationIntent({rootEpoch:1,requestId:1});result={status:'constrained',authority:'tablebase-raw-wdl-root',actions:[577],rootEpoch:context.rootEpoch,rootFence:context.rootFence};assert.equal(p.requestPublication({rootEpoch:1,requestId:1}).ready,false);assert.equal(p.readPublication({rootEpoch:1,requestId:1}),null);await scheduler.fire();assert.deepEqual(f.restrictions.at(-1),[577]);p.requestPublication({rootEpoch:1,requestId:1});assert.equal(p.readPublication({rootEpoch:1,requestId:1}).action,577);result={...result,rootFence:[1,3,4,99]};assert.throws(()=>p.requestPublication({rootEpoch:1,requestId:1}),/authority|fence/);const report=await p.close();assert.equal(report.knowledge.schema,'proved-provider-close');});
test('unavailable late knowledge cannot discard completed same-go raw safety or broaden cached publication',async()=>{const f=fixture(),scheduler=refreshScheduler();f.setLegal([796,577]);const knowledge={...noKnowledge(),async prepare({context}){return {status:'constrained',authority:'tablebase-raw-wdl-root',actions:[577],rootEpoch:context.rootEpoch,rootFence:context.rootFence};},publication(){return {status:'unavailable',reason:'provider-failed'};}};const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,knowledge,...scheduler});await p.admitPosition({fen,moves:[],rootEpoch:1});await p.preparePublicationIntent({rootEpoch:1,requestId:1});assert.equal(p.requestPublication({rootEpoch:1,requestId:1}).ready,false);await scheduler.fire();p.requestPublication({rootEpoch:1,requestId:1});assert.deepEqual(f.restrictions.at(-1),[577]);assert.equal(p.readPublication({rootEpoch:1,requestId:1}).action,577);await p.close();});
test('unknown failed preparation prevents an invented no-runtime-opened successful close',async()=>{const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:async()=>{throw new Error('factory failed without ownership report');}});await assert.rejects(p.ready(),/factory failed/);await assert.rejects(p.close(),/preparation|cleanup|ownership/i);});
test('retired failed preparation records the actual close and never reports no runtime opened',async()=>{const f=fixture(),p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:async()=>finishPreparedInitialization(f.backend.prepared,async()=>{throw new Error('initialization rejected');})});await assert.rejects(p.ready(),/initialization rejected/);const report=await p.close();assert.equal(report.noRuntimeOpened,false);assert.equal(report.gameTeardowns.length,1);assert.equal(report.gameTeardowns[0].disposition,'failed-preparation-retired');assert.equal(report.gameTeardowns[0].cleanup.runtime.graceful,true);assert.equal(f.calls.filter(c=>c==='close').length,1);});
test('claimed retirement with incomplete actual cleanup remains failed on final close',async()=>{const cleanup={status:'complete',failures:[],runtime:{graceful:false,driver:{resourceCounts:{live:1,orphaned:0}}}},p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:async()=>{throw preparationFailure(new Error('model rejected'),'retired',[{owner:'model-compiler',cleanup}]);}});await assert.rejects(p.ready(),/model rejected/);await assert.rejects(p.close(),/preparation|cleanup|ownership/i);});
test('neutral resolution subscription observes one accepted exact result without launching GPU publication and ignores replaced request',async()=>{const f=fixture();f.setLegal([796,577]);const listeners=[];let detached=0;const knowledge={options:[],async ready(){},async beginGame(){},async endGame(){},async close(){},async prepare(){return {status:'unavailable'};},subscribeResolution(args,callback){listeners.push({args,callback});return()=>detached++;}};const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,knowledge});await p.admitPosition({fen,moves:[],rootEpoch:1});await p.preparePublicationIntent({rootEpoch:1,requestId:1});const signals=[];p.subscribePublicationResolution({rootEpoch:1,requestId:1},signal=>signals.push(signal));const listener=listeners[0],resolved={status:'resolved',authority:'tablebase-exact-root',action:577,rootEpoch:1,rootFence:[1,3,4,1]};listener.callback({...resolved,rootFence:[1,3,4,9]});assert.equal(signals.length,0);listener.callback(resolved);listener.callback(resolved);assert.deepEqual(signals,[{rootEpoch:1,requestId:1,resolved:true}]);assert.equal(f.calls.filter(c=>c==='operation-5').length,1);await p.preparePublicationIntent({rootEpoch:1,requestId:2});listener.callback(resolved);assert.equal(signals.length,1);assert.equal(detached,1);await p.close();});
test('resolution subscription immediately replays already resolved intent and subscriber failure cannot change search',async()=>{const f=fixture(),p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare});await p.admitPosition({fen,moves:[],rootEpoch:1});await p.preparePublicationIntent({rootEpoch:1,requestId:1});const signals=[];const unsubscribe=p.subscribePublicationResolution({rootEpoch:1,requestId:1},s=>{signals.push(s);throw new Error('observer fault');});assert.deepEqual(signals,[{rootEpoch:1,requestId:1,resolved:true}]);unsubscribe();unsubscribe();await p.requestPublication({rootEpoch:1,requestId:1});assert.equal(p.readPublication({rootEpoch:1,requestId:1}).action,796);await p.close();});
test('failed resolution detach still joins actual GPU owner and makes final closure fail',async()=>{const f=fixture();f.setLegal([796,577]);const knowledge={options:[],async ready(){},async beginGame(){},async endGame(){},async close(){},async prepare(){return {status:'unavailable'};},subscribeResolution(){return()=>{throw new Error('detach failed');};}};const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,knowledge});await p.admitPosition({fen,moves:[],rootEpoch:1});await p.preparePublicationIntent({rootEpoch:1,requestId:1});const unsubscribe=p.subscribePublicationResolution({rootEpoch:1,requestId:1},()=>{});assert.throws(unsubscribe,/detach failed/);await assert.rejects(p.close(),/resolution|detach/i);assert(f.calls.includes('join'));assert(f.calls.includes('close'));});
test('synchronous resolution replay followed by close still records failure of the late returned detach handle',async()=>{const f=fixture();f.setLegal([796,577]);const knowledge={options:[],async ready(){},async beginGame(){},async endGame(){},async close(){},async prepare(){return {status:'unavailable'};},subscribeResolution({context},callback){callback({status:'resolved',authority:'tablebase-exact-root',action:577,rootEpoch:context.rootEpoch,rootFence:context.rootFence});return()=>{throw new Error('late detach failed');};}};const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,knowledge});await p.admitPosition({fen,moves:[],rootEpoch:1});await p.preparePublicationIntent({rootEpoch:1,requestId:1});let closing;assert.throws(()=>p.subscribePublicationResolution({rootEpoch:1,requestId:1},()=>{closing=p.close();}),/late detach/);await assert.rejects(closing,/resolution|detach/i);assert(f.calls.includes('join'));});

test('deadline read returns completed immutable GPU result while newer refresh is held without queue or GPU work',async()=>{
 const f=fixture(),scheduler=refreshScheduler();f.setLegal([796,577]);const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,knowledge:noKnowledge(),...scheduler});await p.admitPosition({fen,moves:[],rootEpoch:1});const held=holdObserver(f);await scheduler.fire();await held.entering;const before=f.calls.length;
 const requested=p.requestPublication({rootEpoch:1,requestId:10});assert.equal(requested?.then,undefined);assert.equal(requested.ready,true);const r=p.readPublication({rootEpoch:1,requestId:10});assert.equal(r.action,796);assert.equal(f.calls.length,before);assert.equal(r.publicationIntent.requestId,10);assert(Object.isFrozen(r));assert(Object.isFrozen(r.sourceObservation));
 let closed=false;const closing=p.close().then(()=>closed=true);for(let i=0;i<10;i++)await Promise.resolve();assert.equal(closed,false);held.release();await closing;assert(f.calls.includes('join'));assert.equal(scheduler.size(),0);
});
test('newly completed background result replaces one coherent sample without pretending its source is the publication request',async()=>{
 const f=fixture(),scheduler=refreshScheduler();f.setLegal([796,577]);const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,knowledge:noKnowledge(),...scheduler});await p.admitPosition({fen,moves:[],rootEpoch:1});p.requestPublication({rootEpoch:1,requestId:1});const old=p.readPublication({rootEpoch:1,requestId:1});f.setSelected(577);await scheduler.fire();p.requestPublication({rootEpoch:1,requestId:2});const next=p.readPublication({rootEpoch:1,requestId:2});assert.equal(next.action,577);assert(next.sourceObservation.sequence>old.sourceObservation.sequence);assert.equal(next.sourceObservation.selectedAction,577);assert.equal(next.sourceObservation.publicationIntent,undefined);assert.deepEqual(next.authority,old.authority);assert.equal(old.action,796);await p.close();
});
test('new focus invalidates old cache immediately and discards its late refresh before authentic new-focus seed acknowledgement',async()=>{
 const f=fixture(),scheduler=refreshScheduler();f.setLegal([796,577]);const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,knowledge:noKnowledge(),...scheduler});await p.admitPosition({fen,moves:[],rootEpoch:1});p.requestPublication({rootEpoch:1,requestId:1});const held=holdObserver(f);await scheduler.fire();await held.entering;const admission=p.admitPosition({fen,moves:[796],rootEpoch:2});assert.equal(p.readPublication({rootEpoch:1,requestId:1}),null);f.setLegal([577]);held.release();await admission;assert.deepEqual(p.readRootKnowledgeContext().legalActions,[577]);p.requestPublication({rootEpoch:2,requestId:2});const r=p.readPublication({rootEpoch:2,requestId:2});assert.equal(r.action,577);assert.equal(r.sourceObservation.rootEpoch,2);assert.equal(r.authority.epoch,2);await p.close();
});
test('compatible tighter scope reuses a GPU maximum while incompatible scope returns pending instead of hiding a GPU wait',async()=>{
 const f=fixture(),scheduler=refreshScheduler();f.setLegal([796,577]);const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,knowledge:noKnowledge(),...scheduler});await p.admitPosition({fen,moves:[],rootEpoch:1});const held=holdObserver(f);await scheduler.fire();await held.entering;const count=f.calls.length;
 const compatible=await p.preparePublicationIntent({rootEpoch:1,requestId:1,searchmoves:[796]});assert.equal(compatible.publicationReady,true);p.requestPublication({rootEpoch:1,requestId:1,searchmoves:[796]});assert.equal(p.readPublication({rootEpoch:1,requestId:1}).action,796);assert.equal(f.calls.length,count);
 const pending=await p.preparePublicationIntent({rootEpoch:1,requestId:2,searchmoves:[577]});assert.equal(pending.publicationReady,false);assert.equal(pending.preparationDisposition,'constraint-seed-pending');assert.equal(p.requestPublication({rootEpoch:1,requestId:2,searchmoves:[577]}).ready,false);assert.equal(p.readPublication({rootEpoch:1,requestId:2}),null);held.release();for(let i=0;i<30;i++)await Promise.resolve();await scheduler.fire();p.requestPublication({rootEpoch:1,requestId:2,searchmoves:[577]});assert.equal(p.readPublication({rootEpoch:1,requestId:2}).action,577);await p.close();
});
test('resolved non-search authority uses existing canonical GPU legal proof without fresh observer approval',async()=>{
 const f=fixture(),scheduler=refreshScheduler();f.setLegal([796,577]);const knowledge={...noKnowledge(),async prepare({context}){return{status:'resolved',authority:'book-resolved',action:577,rootEpoch:context.rootEpoch,rootFence:context.rootFence};}};const p=createGameSearchPort({modelRoot:'good',revision:'a'.repeat(40),prepare:f.prepare,knowledge,...scheduler});await p.admitPosition({fen,moves:[],rootEpoch:1});const held=holdObserver(f);await scheduler.fire();await held.entering;const before=f.calls.length;const intent=await p.preparePublicationIntent({rootEpoch:1,requestId:1});assert.equal(intent.bypassPublicationWait,true);assert.equal(intent.publicationReady,true);p.requestPublication({rootEpoch:1,requestId:1});const r=p.readPublication({rootEpoch:1,requestId:1});assert.equal(r.action,577);assert.equal(r.decisionAuthority,'book-resolved');assert.equal(r.sourceObservation.selectedAction,796);assert.equal(f.calls.length,before);held.release();await p.close();
});

test('a late completed observer for a replaced constraint cannot become that new scope seed',async()=>{
 const f=fixture(),scheduler=refreshScheduler();f.setLegal([796,577]);const p=createGameSearchPort({prepare:f.prepare,knowledge:noKnowledge(),revision:'a'.repeat(40),...scheduler});await p.admitPosition({fen,rootEpoch:1});await p.preparePublicationIntent({rootEpoch:1,requestId:1,searchmoves:[577]});const held=holdObserver(f);await scheduler.fire();await held.entering;await p.preparePublicationIntent({rootEpoch:1,requestId:2,searchmoves:[796]});held.release();for(let i=0;i<30;i++)await Promise.resolve();p.requestPublication({rootEpoch:1,requestId:2,searchmoves:[796]});assert.equal(p.readPublication({rootEpoch:1,requestId:2}).action,796);assert.equal((await p.preparePublicationIntent({rootEpoch:1,requestId:3,searchmoves:[577]})).publicationReady,false);await p.close();
});

test('failed background child cleanup quarantines owner and never closes beneath an unresolved child',async()=>{
 const f=fixture(),scheduler=refreshScheduler(),p=createGameSearchPort({prepare:f.prepare,knowledge:noKnowledge(),revision:'a'.repeat(40),...scheduler});await p.admitPosition({fen,rootEpoch:1});const original=f.backend.prepared.submitExternal.bind(f.backend.prepared);f.backend.prepared.submitExternal=async(...args)=>{const c=await original(...args);return{...c,async close(){throw new Error('child cleanup unknown');}};};await scheduler.fire();assert.throws(()=>p.requestPublication({rootEpoch:1,requestId:1}),/cleanup unknown/);await assert.rejects(p.close(),/quarantined/i);assert.equal(f.calls.includes('close'),false);assert.equal(f.calls.includes('join'),false);assert.equal(scheduler.size(),0);
});

test('failed background delivery closes child then joins actual owner and retains failed disposition',async()=>{
 const f=fixture(),scheduler=refreshScheduler(),p=createGameSearchPort({prepare:f.prepare,knowledge:noKnowledge(),revision:'a'.repeat(40),...scheduler});await p.admitPosition({fen,rootEpoch:1});const original=f.backend.prepared.submitExternal.bind(f.backend.prepared);f.backend.prepared.submitExternal=async(...args)=>{const c=await original(...args);return args[0]==='operation-5'?{...c,async deliver(){throw new Error('delivery failed');}}:c;};await scheduler.fire();assert.throws(()=>p.requestPublication({rootEpoch:1,requestId:1}),/delivery failed/);await assert.rejects(p.close(),/publication/i);assert(f.calls.includes('child-close'));assert(f.calls.includes('join'));assert(f.calls.includes('close'));
});

test('canonical terminal no-action seed is distinct from an unavailable nonterminal legal seed',async()=>{
 const f=fixture(),scheduler=refreshScheduler();f.setLegal([]);f.setTerminal(true);const p=createGameSearchPort({prepare:f.prepare,knowledge:noKnowledge(),revision:'a'.repeat(40),...scheduler});await p.admitPosition({fen,rootEpoch:1});assert.equal(p.requestPublication({rootEpoch:1,requestId:1}).ready,true);const r=p.readPublication({rootEpoch:1,requestId:1});assert.equal(r.action,null);assert.equal(r.terminal,true);assert.equal(r.sourceObservation.selectedAction,null);await p.close();
 const g=fixture();g.setLegal([]);const q=createGameSearchPort({prepare:g.prepare,knowledge:noKnowledge(),revision:'a'.repeat(40),...refreshScheduler()});await assert.rejects(q.admitPosition({fen,rootEpoch:1}),/legal candidate/);assert.equal(q.readPublication({rootEpoch:1,requestId:1}),null);await q.close();
});

test('admission acknowledgment waits for an authentic GPU seed without exposing a fabricated ready result',async()=>{
 const f=fixture(),scheduler=refreshScheduler(),held=holdObserver(f),p=createGameSearchPort({prepare:f.prepare,knowledge:noKnowledge(),revision:'a'.repeat(40),...scheduler});let settled=false;const admission=p.admitPosition({fen,rootEpoch:1}).then(r=>{settled=true;return r;});await held.entering;assert.equal(settled,false);assert.equal(p.readRootKnowledgeContext(),null);assert.equal(p.readPublication({rootEpoch:1,requestId:1}),null);held.release();await admission;assert.equal(p.requestPublication({rootEpoch:1,requestId:1}).ready,true);await p.close();
});

test('slow replaced intent preparation cannot overwrite the newer current request',async()=>{
 const f=fixture(),scheduler=refreshScheduler();f.setLegal([796,577]);let release,entered;const held=new Promise(r=>release=r),entering=new Promise(r=>entered=r);const knowledge={...noKnowledge(),async prepare({requestId}){if(requestId===1){entered();await held;}return {status:'unavailable'};}};const p=createGameSearchPort({prepare:f.prepare,knowledge,revision:'a'.repeat(40),...scheduler});await p.admitPosition({fen,rootEpoch:1});const old=p.preparePublicationIntent({rootEpoch:1,requestId:1,searchmoves:[577]});await entering;await p.preparePublicationIntent({rootEpoch:1,requestId:2,searchmoves:[796]});release();await assert.rejects(old,/superseded/);p.requestPublication({rootEpoch:1,requestId:2,searchmoves:[796]});assert.equal(p.readPublication({rootEpoch:1,requestId:2}).action,796);await p.close();
});

test('retirement asks knowledge owner to abandon before joining its pending intent preparation',async()=>{
 const f=fixture(),scheduler=refreshScheduler();f.setLegal([796,577]);let release,entered;const held=new Promise(r=>release=r),entering=new Promise(r=>entered=r);const knowledge={...noKnowledge(),async prepare(){entered();await held;return {status:'unavailable'};},async endGame(){release();}};const p=createGameSearchPort({prepare:f.prepare,knowledge,revision:'a'.repeat(40),...scheduler});await p.admitPosition({fen,rootEpoch:1});const intent=p.preparePublicationIntent({rootEpoch:1,requestId:1});await entering;const closing=p.close();const settled=await Promise.race([closing.then(()=>true),new Promise(r=>setTimeout(()=>r(false),40))]);if(!settled)release();await assert.rejects(intent,/superseded/);await closing;assert.equal(settled,true);assert(f.calls.includes('join'));assert(f.calls.includes('close'));
});
