import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
async function api(){try{return await import('../../components/engine-runtime/model-artifacts.mjs');}catch(e){if(e.code==='ERR_MODULE_NOT_FOUND')assert.fail('Qualified public model artifact loader is missing');throw e;}}
test('model artifact admission rejects unqualified or mixed cohorts before file access',async()=>{const {loadModelArtifacts}=await api();const q={schema:'vector-real-successor-block32-model-observation-v1',modelNumericalParityPassed:false};assert.throws(()=>loadModelArtifacts({directory:'nonexistent',qualification:q,expectedCohort:{tensor:'0.1.0-alpha.9',cudaJs:'0.1.0-alpha.21'}}),/qualified|qualification/i);q.modelNumericalParityPassed=true;q.node='v26.11.1';q.tensorCompatibility={package:{version:'0.1.0-alpha.9'},cudaJs:{version:'0.1.0-alpha.21'}};assert.throws(()=>loadModelArtifacts({directory:'nonexistent',qualification:q,expectedCohort:{tensor:'0.1.0-alpha.10',cudaJs:'0.1.0-alpha.22'}}),/cohort/i);});
test('public library rehydration rejects malformed ABI and tampered opaque bytes',async()=>{const {rehydrateModelLibrary}=await api();const d=fs.mkdtempSync(path.join(os.tmpdir(),'vector-library-admission-'));try{fs.writeFileSync(path.join(d,'tensor-model-library.bin'),new Uint8Array([1,2,3]));assert.throws(()=>rehydrateModelLibrary(d,{exports:[],artifact:{bytesFile:'tensor-model-library.bin'}},{artifactSha256:'0'.repeat(64)}),/ABI|identity/i);const types=['u32',...Array(6).fill('ptr<f32>')];const descriptor={sha256:'0'.repeat(64),exports:[{name:'tensorRunItem',parameters:types.map(type=>({type})),returns:'u32'}],artifact:{bytesFile:'../outside.bin',sha256:'0'.repeat(64),byteLength:3}};assert.throws(()=>rehydrateModelLibrary(d,descriptor,{librarySha256:'0'.repeat(64),artifactSha256:'0'.repeat(64)}),/path/i);descriptor.artifact.bytesFile='tensor-model-library.bin';assert.throws(()=>rehydrateModelLibrary(d,descriptor,{librarySha256:'0'.repeat(64),artifactSha256:'0'.repeat(64)}),/identity/i);}finally{assert.equal(path.dirname(path.resolve(d)),path.resolve(os.tmpdir()));fs.rmSync(d,{recursive:true,force:true});}});
test('self-asserted numerical receipt cannot substitute a different typed model artifact',async()=>{const {loadModelArtifacts,MODEL_IDENTITY}=await api();const cohort={tensor:'0.1.0-alpha.10',cudaJs:'0.1.0-alpha.22',cudaJsRevision:'dc2924657bb900cdce3fba4c9def62934419db03'},q={...MODEL_IDENTITY,schema:'vector-real-successor-block32-model-observation-v1',modelNumericalParityPassed:true,node:'v26.11.1',tensorCompatibility:{package:{version:cohort.tensor},cudaJs:{version:cohort.cudaJs,protectedMainRevision:cohort.cudaJsRevision}},status:'device_closed_inference_math_and_exact_latency_qualified',profile:'SPEC-0009-block32-v1',semanticNodeCount:2216,cleanup:{session:{graceful:true},runtime:{graceful:true,driver:{resourceCounts:{live:0,orphaned:0}}}},batches:[1,2].map(itemCount=>({itemCount,itemCapacity:2,inputOutputWorkspaceGuardsPassed:true,inactiveItemNoWritePassed:true,observed:{policy:{pass:true,maximumAbsoluteError:0},value:{pass:true,maximumAbsoluteError:0}}})),libraryArtifact:{librarySha256:'0'.repeat(64),artifactSha256:'0'.repeat(64)}};assert.throws(()=>loadModelArtifacts({directory:'nonexistent',qualification:q,expectedCohort:cohort}),/selected.*library|selected.*artifact/i);});
