import assert from 'node:assert/strict';
import test from 'node:test';
export const evaluatorLayout={requestInputPartition:{dtype:'f32',perRequestElements:1088,elementCount:1088,members:[{parameterName:'input0',offset:0,perItemElements:1088}]},resultOutputPartition:{dtype:'f32',perRequestElements:4163,elementCount:4163,members:[{parameterName:'output0',offset:0,perItemElements:4162},{parameterName:'output1',offset:4162,perItemElements:1}]},featureParameter:'input0',policyParameter:'output0',valueParameter:'output1'};
async function api(){try{return await import('../../components/engine-runtime/policy-hooks.mjs');}catch(e){if(e.code==='ERR_MODULE_NOT_FOUND')assert.fail('Public resident Policy hook contribution is missing');throw e;}}
test('product hooks bind selected Evaluator ready-result ABI instead of calling Tensor from Policy',async()=>{const {buildChessPolicyHooks}=await api();const m=buildChessPolicyHooks({evaluatorLayout});assert.equal(m.functions.find(f=>f.name===m.hooks.classifyFrontier).parameters.length,11);assert.equal(m.functions.find(f=>f.name===m.hooks.consumeEvaluation).parameters.length,17);assert.equal(m.functions.find(f=>f.name===m.hooks.apply).parameters.length,30);assert.equal(m.functions.find(f=>f.name===m.hooks.initializeCandidate).parameters.length,8);assert.equal(m.recordWidths.nodeU32,6);assert.equal(m.recordWidths.edgeF32,4);assert.equal(m.recordWidths.value,2);assert(!/tensorRunItem|evaluateItem|mcgsTensorEvaluate/.test(m.source));});
test('Policy derives result partition offsets from the selected public Evaluator layout and rejects missing extents',async()=>{const {buildChessPolicyHooks}=await api();assert.throws(()=>buildChessPolicyHooks(),/layout|partition/i);const shifted=structuredClone(evaluatorLayout);shifted.resultOutputPartition.perRequestElements=4166;shifted.resultOutputPartition.elementCount=4166;shifted.resultOutputPartition.members[0].offset=3;shifted.resultOutputPartition.members[1].offset=4165;const m=buildChessPolicyHooks({evaluatorLayout:shifted});assert.equal(m.resultLayout.policyOffset,3);assert.equal(m.resultLayout.valueOffset,4165);const malformed=structuredClone(evaluatorLayout);malformed.resultOutputPartition.members[1].offset=5000;assert.throws(()=>buildChessPolicyHooks({evaluatorLayout:malformed}),/extent|partition|layout/i);});
test('complete Domain/Policy source validates through public Device-JS without neural callable imports',async()=>{const {inspectChessPolicyHooks}=await api();const r=inspectChessPolicyHooks({evaluatorLayout});assert.equal(r.deviceProgram.kernels.length,1);assert.equal(r.deviceProgram.imports?.length??0,0);});
test('input encoding belongs to Evaluator and Policy references its explicit model projection helper',async()=>{const {buildChessPolicyHooks}=await api();const m=buildChessPolicyHooks({evaluatorLayout});assert(!m.functions.some(f=>f.name==='mWriteFeatures'));assert.equal(m.hooks.encodeEvaluation,undefined);const encoder=m.evaluator.functions.find(f=>f.name===m.evaluator.hooks.encodeEvaluation);assert.equal(encoder.parameters.length,7);assert(m.evaluator.functions.some(f=>f.name==='mPolicyIndex'));assert(m.functions.find(f=>f.name===m.hooks.consumeEvaluation).calls.includes('mPolicyIndex'));});
test('Policy exposes aggregate backup preflight, abandonment and lease-aware retirement through canonical ports',async()=>{const {buildChessPolicyHooks}=await api();const m=buildChessPolicyHooks({evaluatorLayout});assert.equal(m.functions.find(f=>f.name===m.hooks.prepare).parameters.length,4);assert.equal(m.functions.find(f=>f.name===m.hooks.retirePolicy)?.parameters.length,9);assert.equal(m.functions.find(f=>f.name===m.hooks.abandon)?.parameters.length,4);});
test('Policy selects finite parking through the public stop hook without a clock input',async()=>{const {buildChessPolicyHooks}=await api();const m=buildChessPolicyHooks({evaluatorLayout}),fn=m.functions.find(f=>f.name===m.hooks.evaluateStop);assert.equal(fn?.parameters.length,4);assert.equal(fn.parameters[0].type,'ptr<u32>');assert.equal(fn.parameters[2].type,'ptr<f32>');assert(!fn.parameters.some(p=>/clock|deadline|movetime/i.test(p.name)));});
test('physical Policy consumes ready evaluations transactionally and preserves proof through child reclamation',{skip:process.env.VECTOR_POLICY_HOOK_NATIVE!=='1'},async()=>{let qualify;try{({qualifyPolicyHooks:qualify}=await import('../../components/engine-runtime/policy-qualification.mjs'));}catch(e){if(e.code==='ERR_MODULE_NOT_FOUND')assert.fail('Policy hook physical qualifier is missing');throw e;}const r=await qualify({evaluatorLayout});assert.equal(r.readyResultPassed,true);assert.equal(r.invalidResultNoWritePassed,true);assert.equal(r.lifecyclePassed,true);assert.equal(r.staleChildProofRetained,true);assert.equal(r.invalidReadyChildNoWritePassed,true);assert.equal(r.aggregatePreflightPassed,true);assert.equal(r.abandonPreservesEvidence,true);assert.equal(r.retirementLeasePassed,true);assert.equal(r.stopDispositionPassed,true);assert.equal(r.terminal.graceful,true);assert.equal(r.terminal.driver.resourceCounts.live,0);assert.equal(r.terminal.driver.resourceCounts.orphaned,0);});
