import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
test('actual original model admits source-bound Domain Graph Evaluator and Policy profiles',{skip:process.env.VECTOR_MODEL_PROFILE_ADMISSION_NATIVE!=='1'},async()=>{
  const {compileAdmittedModelProgram}=await import('../../components/engine-runtime/model-program.mjs');
  const {createChessColdSelection,admitChessOwnerProfiles,createChessResidentCore,composeChessResidentCore}=await import('../../components/engine-runtime/cold-selection.mjs');
  const admitted=await compileAdmittedModelProgram({cacheDirectory:process.env.VECTOR_MODEL_COMPILER_CACHE});
  const cold=createChessColdSelection({deviceProgram:admitted.deviceProgram,revision:'56eebdaa33195c824ebf424629f15d765fb478a4'});
  const selected=admitChessOwnerProfiles(cold),{source,graph,evaluator,policy,resource,progress,output,session,resourceClasses,evaluatorProgramBinding,evaluatorResourceBinding,externalResourceClasses,artifactBindings}=selected;
  assert.equal(policy.normalized.value.coordinates.length,2,'Actual value ABI carries utility and finite proof code');
  if(process.env.VECTOR_MODEL_PROFILE_DIAGNOSTICS==='1')console.log(JSON.stringify({sourceFunctionCounts:[...source.sourceBundles.map(b=>[b.ownerProfile,b.functions.length]),...Object.entries(source.contributions).map(([role,b])=>[role,b.functions.length])],sourceBytes:[...source.sourceBundles,...Object.values(source.contributions)].reduce((n,b)=>n+Buffer.byteLength(b.source),0)}));
  const core=createChessResidentCore(selected);if(process.env.VECTOR_MODEL_PROFILE_DIAGNOSTICS==='1')console.log('Actual normalized resident constructor admission passed');
  if(process.env.VECTOR_RESIDENT_CONTEXT)fs.writeFileSync(process.env.VECTOR_RESIDENT_CONTEXT,JSON.stringify({schema:'vector_resident_context_candidate_v1',context:{authority:cold.authority,domain:cold.domain,graph,policy,evaluator,resource,progress,output,session,evaluatorRuntime:cold.evaluatorRuntime,sourceDescriptor:source},constructorOptions:{resourceClasses,externalResourceClasses,artifactBindings},core,composedSearchClaimed:false},null,2)+'\n',{flag:'wx'});
  const composition=composeChessResidentCore(selected,core);assert.equal(composition.publication.executionPackage.normalized.cudaJsAdapter.continuation.nodes.length,3);if(process.env.VECTOR_MODEL_PROFILE_DIAGNOSTICS==='1')console.log('Actual canonical resident Composer assembly passed');
  assert(core.deviceSourcePartition,'Actual full source requires canonical lower-cap partition');assert.equal(core.continuation.nodes.length,3);assert.equal(core.continuation.initializationOperations.length,1);assert.equal(core.continuation.externalOperations.length,2);
  for(const op of core.operations)assert(op.bindings.length<=64);assert.equal(core.operations.find(op=>op.id===core.operationIds.body).block[0],'32');
  assert.equal(evaluator.normalized.mode,'evaluation-only');assert.equal(policy.normalized.evaluatorMode,'evaluation-only');
  assert.equal(graph.normalized.mode,'materialized');assert.equal(source.protocol.rootEstablishment,'pre-ignition-validate-admit-materialize');
  assert.equal(evaluator.normalized.batching.maximumItems,'1');assert.equal(policy.normalized.resources.find(r=>r.unit==='bytes').maximum,'357428');
  assert(evaluator.normalized.capabilities.every(c=>c.kind!=='proposal'));
  assert.equal(evaluatorProgramBinding.ownerProfile,evaluator.normalized.id);assert.equal(evaluatorResourceBinding.ownerProfile,evaluator.normalized.id);assert.equal(evaluatorResourceBinding.externalTensorParameters.length,2);assert.equal(Object.keys(artifactBindings).length,2);
  for(const binding of Object.values(artifactBindings)){const artifact=evaluator.normalized.artifacts.find(a=>a.id===binding.artifactId);assert.deepEqual(binding.artifactIdentity,artifact.identity);assert.equal(binding.contentSha256,artifact.identity.sha256);}
  for(const parameter of source.externalParameters)assert(externalResourceClasses[parameter.name],`Actual external ${parameter.name} capability requires selected class`);
  for(const [owner,role]of [[resource,'resource'],[progress,'progress'],[output,'output'],[session,'session']])assert.equal(owner.normalized.schema,`cuda-mcgs.${role}-profile/0.2.0`);
  const demandByClass=new Map();for(const buffer of source.buffers){const classId=resourceClasses[buffer.name];assert(classId,`Actual resident ${buffer.name} must have a selected Resource class`);demandByClass.set(classId,(demandByClass.get(classId)??0)+buffer.byteLength);}
  for(const [classId,bytes]of demandByClass){const selected=resource.normalized.classes.find(c=>c.id===classId);assert(selected&&selected.unit==='bytes');assert(BigInt(bytes)<=BigInt(selected.formula.maximumUnits),`Actual resident byte demand exceeds ${classId}`);}
  const badDomain={...cold,domain:{...cold.domain,identity:{...cold.domain.identity,sha256:'0'.repeat(64)}}};assert.throws(()=>admitChessOwnerProfiles(badDomain),e=>e.code==='RESIDENT_SOURCE_DOMAIN');
  const badSource={...cold,sourceBundles:cold.sourceBundles.map(bundle=>bundle.ownerProfile===cold.policy.id?{...bundle,source:bundle.source+'\n// changed source\n'}:bundle)};assert.throws(()=>admitChessOwnerProfiles(badSource),e=>e.code==='RESIDENT_SOURCE_IDENTITY');
  const badHook={...cold,hooks:{...cold.hooks,consumeEvaluation:{...cold.hooks.consumeEvaluation,ownerProfile:cold.domain.normalized.id}}};assert.throws(()=>admitChessOwnerProfiles(badHook),e=>e.code==='RESIDENT_SOURCE_HOOK');
  const {createChessPolicyProfile}=await import('../../components/engine-runtime/selected-profiles.mjs');
  assert.throws(()=>createChessPolicyProfile({authority:cold.authority,domain:cold.domain,graph,evaluator,source:cold.model.policy,layout:{...source.layout,maxActions:257},revision:cold.sourceProvenance.revision}),/action extent/);
  for(const artifact of [...cold.domain.semanticArtifacts,...evaluator.semanticArtifacts,...policy.semanticArtifacts])assert.equal(createHash('sha256').update(artifact.bytes).digest('hex'),artifact.reference.sha256);
  if(process.env.VECTOR_MODEL_PROFILE_ADMISSION_RECEIPT)fs.writeFileSync(process.env.VECTOR_MODEL_PROFILE_ADMISSION_RECEIPT,JSON.stringify({schema:'vector_current_owner_profile_admission_v1',node:process.version,status:'pass',sourceRevision:cold.sourceProvenance.revision,modelCompiler:admitted.record,cohort:{cudaJs:'0.1.0-alpha.22',cudaJsRevision:'dc2924657bb900cdce3fba4c9def62934419db03',tensor:'0.1.0-alpha.10',mcgsCandidateSha256:'ba983ba3a50d7d10e66d6905c5c075af3c53e1833bd32a260be6cabbcecbd3d8'},sourceDescriptorIdentity:source.identity,sourceContributions:Object.fromEntries(Object.entries(source.contributions).map(([owner,c])=>[owner,c.sourceIdentity])),profiles:Object.fromEntries(Object.entries({domain:cold.domain,graph,evaluator,policy,resource,progress,output,session}).map(([owner,p])=>[owner,{identity:p.identity,normalized:p.normalized}])),publicRequirementArtifacts:cold.requirementSelection.artifacts,buffers:source.buffers,resourceClasses,externalResourceClasses,artifactBindings,evaluatorProgramBindingIdentity:evaluatorProgramBinding.sourceUnit.sourceIdentity,evaluatorResourceBindings:evaluatorResourceBinding.resourceBindings,falsifiers:['Domain-identity','Policy-source-bytes','cross-owner-hook','action-extent'],composedSearchClaimed:false,gpuKernelLaunched:false},null,2)+'\n',{flag:'wx'});
});
