import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const require=createRequire(new URL('../../components/chess-domain/package.json',import.meta.url)),{Chess}=require('chess.js');
const root=fileURLToPath(new URL('../../',import.meta.url));
class NativeUci {
 constructor(){this.lines=[];this.all=[];this.stderr='';this.waiter=null;this.child=spawn(process.execPath,['--experimental-ffi','dist/uci.mjs'],{cwd:root,env:{...process.env,VECTOR_CANDIDATE_SOURCE_REVISION:process.env.VECTOR_UCI_SOURCE_REVISION,VECTOR_CANDIDATE_COMPILER_CACHE:process.env.VECTOR_UCI_COMPILER_CACHE},stdio:['pipe','pipe','pipe'],windowsHide:true});this.closed=new Promise(resolve=>this.child.once('close',(code,signal)=>{this.exit={code,signal};resolve(this.exit);this.wake();}));let buffer='';this.child.stdout.on('data',bytes=>{buffer+=bytes.toString();if(buffer.length>65536)throw new Error('Native UCI line extent');for(let i;(i=buffer.indexOf('\n'))>=0;){const line=buffer.slice(0,i).replace(/\r$/,'');buffer=buffer.slice(i+1);this.lines.push(line);this.all.push(line);}this.wake();});this.child.stderr.on('data',b=>{this.stderr=(this.stderr+b).slice(-65536);});this.child.once('error',error=>{this.error=error;this.wake();});}
 wake(){this.waiter?.();}
 send(line){this.child.stdin.write(line+'\n');}
 async until(predicate,timeout=30000){const deadline=performance.now()+timeout,seen=[];for(;;){while(this.lines.length){const line=this.lines.shift();seen.push(line);if(line.startsWith('info string error '))throw new Error(line);if(predicate(line))return seen;}if(this.error)throw this.error;if(this.exit)throw new Error('Native UCI exited before response');const remaining=deadline-performance.now();if(remaining<=0)throw new Error('Native UCI response timeout');await new Promise(resolve=>{const t=setTimeout(()=>{this.waiter=null;resolve();},remaining);this.waiter=()=>{clearTimeout(t);this.waiter=null;resolve();};});}}
 async ready(){this.send('uci');await this.until(l=>l==='uciok');this.send('setoption name ModelRoot value '+process.env.VECTOR_UCI_MODEL_ROOT);if(process.env.VECTOR_UCI_DISABLE_BOOK==='1')this.send('setoption name OwnBook value false');this.send('isready');const lines=await this.until(l=>l==='readyok',300000);return JSON.parse(lines.find(l=>l.startsWith('info string vector_identity ')).slice('info string vector_identity '.length));}
 async move(position,movetime){this.send(position);const t=performance.now();this.send('go movetime '+movetime);const lines=await this.until(l=>l.startsWith('bestmove '),movetime+30000);return {move:lines.at(-1).split(' ')[1],elapsedMilliseconds:performance.now()-t,movetime};}
 async close(){this.send('quit');let t;const exit=await Promise.race([this.closed,new Promise((_,reject)=>{t=setTimeout(()=>reject(new Error('Native UCI failed joined process closure')),30000);})]).finally(()=>clearTimeout(t));assert.deepEqual(exit,{code:0,signal:null});const lines=this.all.filter(l=>l.startsWith('info string vector_teardown '));assert.equal(lines.length,1);return JSON.parse(lines[0].slice('info string vector_teardown '.length));}
}
test('actual UCI returns GPU legal moves, retains game across go/position and emits joined teardown',{skip:process.env.VECTOR_UCI_NATIVE!=='1'},async()=>{
 assert.equal(process.version,'v26.11.1');assert(process.env.VECTOR_UCI_MODEL_ROOT&&process.env.VECTOR_UCI_COMPILER_CACHE&&/^[0-9a-f]{40}$/.test(process.env.VECTOR_UCI_SOURCE_REVISION??''));
 const uci=new NativeUci(),record={schema:'vector_uci_native_diagnostic_v1',status:'pending',node:process.version,sourceRevision:process.env.VECTOR_UCI_SOURCE_REVISION,referee:'chess.js@1.4.0',measurements:[],timingPolicyQualified:false};
 try{record.identity=await uci.ready();const ref=new Chess(),first=await uci.move('position startpos',2000);assert(ref.moves({verbose:true}).some(m=>m.from+m.to+(m.promotion??'')===first.move));ref.move({from:first.move.slice(0,2),to:first.move.slice(2,4)});record.measurements.push(first);const second=await uci.move('position startpos moves '+first.move,1000);assert(ref.moves({verbose:true}).some(m=>m.from+m.to+(m.promotion??'')===second.move));record.measurements.push(second);record.status='pass';}
 catch(error){record.status='fail';record.failure={message:error.message,stack:error.stack};throw error;}
 finally{try{record.teardown=await uci.close();assert.equal(record.teardown.joined,true);assert.equal(record.teardown.semantic.quiescent,true);assert.equal(record.teardown.cleanup.runtime.driver.resourceCounts.live,0);assert.equal(record.teardown.cleanup.runtime.driver.resourceCounts.orphaned,0);}catch(error){record.status='fail';record.closeFailure=error.message;throw error;}finally{record.lines=uci.all;record.stderr=uci.stderr;if(process.env.VECTOR_UCI_NATIVE_RECEIPT)fs.writeFileSync(process.env.VECTOR_UCI_NATIVE_RECEIPT,JSON.stringify(record,null,2)+'\n',{flag:'wx'});}}
});
test('actual GPU UCI finds mate, makes forced escape and avoids immediate mate when an escape exists',{skip:process.env.VECTOR_UCI_TACTICS_NATIVE!=='1'},async()=>{
 assert.equal(process.version,'v26.11.1');const uci=new NativeUci(),record={schema:'vector_uci_tactical_diagnostic_v1',status:'pending',node:process.version,sourceRevision:process.env.VECTOR_UCI_SOURCE_REVISION,referee:'chess.js@1.4.0',cases:[],timingPolicyQualified:false};
 const cases=[{name:'mate-in-one',fen:'7k/5Q2/6K1/8/8/8/8/8 w - - 0 1',kind:'mate'},{name:'forced-legal-escape',fen:'6rk/8/8/8/8/8/7r/7K w - - 0 1',kind:'escape'},{name:'avoid-immediate-mate',fen:'6k1/8/3b4/8/7q/8/5PPP/6K1 w - - 0 1',kind:'safe'}];
 const coordinate=m=>m.from+m.to+(m.promotion??'');
 try{record.identity=await uci.ready();for(const c of cases){const ref=new Chess(c.fen),legal=ref.moves({verbose:true}),mateMoves=[],dangerous=[];for(const move of legal){ref.move(move);if(ref.isCheckmate())mateMoves.push(coordinate(move));for(const reply of ref.moves({verbose:true})){ref.move(reply);const mate=ref.isCheckmate();ref.undo();if(mate){dangerous.push(coordinate(move));break;}}ref.undo();}
  if(c.kind==='mate')assert(mateMoves.length>0);if(c.kind==='escape')assert.equal(legal.length,1);if(c.kind==='safe')assert(dangerous.length>0&&dangerous.length<legal.length);
  const result=await uci.move('position fen '+c.fen,10000),observation={...c,...result,legal:legal.map(coordinate),mateMoves,dangerous};record.cases.push(observation);assert(observation.legal.includes(result.move),c.name+' legal');if(c.kind==='mate')assert(mateMoves.includes(result.move),'GPU failed mate-in-one');if(c.kind==='escape')assert.equal(result.move,coordinate(legal[0]));if(c.kind==='safe')assert(!dangerous.includes(result.move),'GPU chose immediate mate despite escape');console.log(JSON.stringify({case:c.name,move:result.move,elapsedMilliseconds:result.elapsedMilliseconds}));}record.status='pass';}
 catch(error){record.status='fail';record.failure={message:error.message,stack:error.stack};throw error;}
 finally{try{record.teardown=await uci.close();assert.equal(record.teardown.joined,true);assert.equal(record.teardown.semantic.quiescent,true);assert.equal(record.teardown.cleanup.runtime.driver.resourceCounts.live,0);}catch(error){record.status='fail';record.closeFailure=error.message;throw error;}finally{record.lines=uci.all;record.stderr=uci.stderr;if(process.env.VECTOR_UCI_NATIVE_RECEIPT)fs.writeFileSync(process.env.VECTOR_UCI_NATIVE_RECEIPT,JSON.stringify(record,null,2)+'\n',{flag:'wx'});}}
});
test('actual GPU UCI plays a complete orthodox game against an independent deterministic legal opponent',{skip:process.env.VECTOR_UCI_GAME_NATIVE!=='1'},async()=>{
 assert.equal(process.version,'v26.11.1');const uci=new NativeUci(),opening=process.env.VECTOR_UCI_GAME_FEN,ref=opening?new Chess(opening):new Chess(),history=[],occurrences=new Map(),record={schema:'vector_uci_complete_game_diagnostic_v1',status:'pending',node:process.version,sourceRevision:process.env.VECTOR_UCI_SOURCE_REVISION,referee:'chess.js@1.4.0',opponent:'independent external deterministic first legal coordinate move',opening:opening??'startpos',moves:[],timingPolicyQualified:false};
 const coordinate=m=>m.from+m.to+(m.promotion??''),key=()=>ref.fen().split(' ').slice(0,4).join(' ');occurrences.set(key(),1);
 const terminal=()=>ref.isCheckmate()?{reason:'checkmate',winner:ref.turn()==='w'?'black':'white'}:ref.isStalemate()?{reason:'stalemate'}:ref.isInsufficientMaterial()?{reason:'insufficient-material'}:Number(ref.fen().split(' ')[4])>=150?{reason:'automatic-seventy-five-moves'}:(occurrences.get(key())??0)>=5?{reason:'automatic-fivefold-repetition'}:null;
 try{record.identity=await uci.ready();for(let ply=0;ply<256&&!terminal();ply++){const legal=ref.moves({verbose:true}),before=ref.fen();let move,result;if(ref.turn()==='w'){result=await uci.move((opening?'position fen '+opening:'position startpos')+(history.length?' moves '+history.join(' '):''),1000);move=result.move;assert(legal.some(m=>coordinate(m)===move),'GPU produced illegal whole-game move');}else move=legal.map(coordinate).sort()[0];ref.move({from:move.slice(0,2),to:move.slice(2,4),...(move.length===5?{promotion:move[4]}:{})});history.push(move);occurrences.set(key(),(occurrences.get(key())??0)+1);record.moves.push({ply,before,move,owner:ply%2===0?'GPU-engine':'external-opponent',...(result??{})});if(ply%10===0)console.log(JSON.stringify({ply,move,fen:ref.fen()}));}
  record.termination=terminal();record.finalFen=ref.fen();record.pgn=ref.pgn();assert(record.termination,'Bounded game did not reach an actual automatic terminal result');record.status='pass';console.log(JSON.stringify({termination:record.termination,plies:history.length}));}
 catch(error){record.status='fail';record.failure={message:error.message,stack:error.stack};throw error;}
 finally{try{record.teardown=await uci.close();assert.equal(record.teardown.joined,true);assert.equal(record.teardown.semantic.quiescent,true);assert.equal(record.teardown.cleanup.runtime.driver.resourceCounts.live,0);}catch(error){record.status='fail';record.closeFailure=error.message;throw error;}finally{record.lines=uci.all;record.stderr=uci.stderr;if(process.env.VECTOR_UCI_NATIVE_RECEIPT)fs.writeFileSync(process.env.VECTOR_UCI_NATIVE_RECEIPT,JSON.stringify(record,null,2)+'\n',{flag:'wx'});}}
});

test('actual UCI preserves off-focus graph work and retires two games before a bounded aggregate quit',{skip:process.env.VECTOR_UCI_RETENTION_NATIVE!=='1'},async()=>{
 assert.equal(process.version,'v26.11.1');const uci=new NativeUci(),record={schema:'vector_uci_retention_diagnostic_v1',status:'pending',node:process.version,sourceRevision:process.env.VECTOR_UCI_SOURCE_REVISION,cases:[],neuralCacheRetentionQualified:false,timingPolicyQualified:false};
 const observation=()=>{const row=uci.all.findLast(l=>l.startsWith('info string vector_clock_phase ')&&JSON.parse(l.slice('info string vector_clock_phase '.length)).phase==='emit');assert(row,'actual bounded Output observation missing');return JSON.parse(row.slice('info string vector_clock_phase '.length)).observation;};
 try{record.identity=await uci.ready();for(const position of ['position startpos','position startpos moves e2e4','position startpos']){const move=await uci.move(position,600);record.cases.push({position,...move,observation:observation()});}const [first,,returned]=record.cases;for(const key of ['arena','root','generation'])assert.equal(returned.observation.authority[key],first.observation.authority[key]);assert(returned.observation.telemetry.completedGraphWorkAtRoot.value>=first.observation.telemetry.completedGraphWorkAtRoot.value,'retained root work regressed');assert.equal(returned.observation.telemetry.evaluationDispositionAtRoot.value&3,3,'Accepted evaluation and later ordinary traversal history must survive the same root incarnation');record.policyAcceptedEvaluationAndTraversalHistoryRetained=true;uci.send('ucinewgame');uci.send('isready');await uci.until(l=>l==='readyok',300000);const second=await uci.move('position startpos',600);record.cases.push({position:'newgame startpos',...second,observation:observation()});assert(record.cases.at(-1).observation.authority.arena>first.observation.authority.arena);uci.send('ucinewgame');record.status='pass';}
 catch(error){record.status='fail';record.failure={message:error.message,stack:error.stack};throw error;}
 finally{try{record.teardown=await uci.close();assert.equal(record.teardown.noActiveRuntime,true);assert.equal(record.teardown.closureJournal.totalJoined,2);assert.equal(record.teardown.gameTeardowns.filter(r=>r.joined).length,2);for(const r of record.teardown.gameTeardowns){assert.equal(r.cleanup.runtime.driver.resourceCounts.live,0);assert.equal(r.cleanup.runtime.driver.resourceCounts.orphaned,0);}}catch(error){record.status='fail';record.closeFailure=error.message;throw error;}finally{record.lines=uci.all;record.stderr=uci.stderr;if(process.env.VECTOR_UCI_NATIVE_RECEIPT)fs.writeFileSync(process.env.VECTOR_UCI_NATIVE_RECEIPT,JSON.stringify(record,null,2)+'\n',{flag:'wx'});}}
});
