import assert from 'node:assert/strict';
import { access } from 'node:fs/promises';
import test from 'node:test';

async function api() { const url = new URL('./latticeknight-successor-oracle.mjs', import.meta.url); try { await access(url); } catch { assert.fail('Independent oracle implementation is missing'); } return import(url); }
// Public-port fixture tests the wrapper's numerical validation and resource lifecycle.
// It is not an independent numerical oracle and never produces qualification evidence.
function port({ wrongShape = false, nonfinite = false, runFailure = false, releaseFailure = false } = {}) {
  let releases = 0;
  const session = { inputNames: ['features'], outputNames: ['policy', 'value'], async run(feeds) { if (runFailure) throw Error('provider run failure'); const n = feeds.features.dims[0]; const policy = new Float32Array(n * 4162).fill(0.25), value = new Float32Array(n).fill(-0.5); if (nonfinite) policy[0] = Infinity; return { policy: { type: 'float32', dims: [n, wrongShape ? 4096 : 4162], data: policy }, value: { type: 'float32', dims: [n, 1], data: value } }; }, async release() { releases++; if (releaseFailure) throw Error('release failure'); } };
  return { runtime: { Tensor: class { constructor(type, data, dims) { Object.assign(this, { type, data, dims }); } }, InferenceSession: { async create() { return session; } } }, releases: () => releases };
}
const adapter = { materializeFen(fen) { const features = new Float32Array(1088); features[0] = fen === 'second' ? 2 : 1; return { features }; } };
const scenarios = [{ id: 'full', capacity: 2, fens: ['first', 'second'] }, { id: 'partial', capacity: 2, fens: ['second'] }];
test('records full and partial independent features with exact output byte lengths', async () => { const { measureOracleBatches } = await api(); const p = port(); const result = await measureOracleBatches({ runtime: p.runtime, adapter, modelPath: 'public-port-fixture', scenarios }); assert.equal(result.batches[0].features.length, 8704); assert.equal(result.batches[0].policy.length, 33296); assert.equal(result.batches[1].features.length, 4352); assert.equal(result.batches[1].value.readFloatLE(), -0.5); assert.equal(result.batches[0].features.readFloatLE(4352), 2); assert.equal(result.cleanup.sessionReleased, true); assert.equal(p.releases(), 1); });
test('rejects output shape mismatch and still releases session', async () => { const { measureOracleBatches } = await api(); const p = port({ wrongShape: true }); await assert.rejects(measureOracleBatches({ runtime: p.runtime, adapter, modelPath: 'fixture', scenarios }), /shape/i); assert.equal(p.releases(), 1); });
test('rejects nonfinite ONNX output and still releases session', async () => { const { measureOracleBatches } = await api(); const p = port({ nonfinite: true }); await assert.rejects(measureOracleBatches({ runtime: p.runtime, adapter, modelPath: 'fixture', scenarios }), /nonfinite/i); assert.equal(p.releases(), 1); });
test('preserves provider run failure with successful cleanup', async () => { const { measureOracleBatches } = await api(); const p = port({ runFailure: true }); await assert.rejects(measureOracleBatches({ runtime: p.runtime, adapter, modelPath: 'fixture', scenarios }), (e) => e.message === 'provider run failure' && e.cleanup.sessionReleased); assert.equal(p.releases(), 1); });
test('reports failed release honestly and rejects success', async () => { const { measureOracleBatches } = await api(); const p = port({ releaseFailure: true }); await assert.rejects(measureOracleBatches({ runtime: p.runtime, adapter, modelPath: 'fixture', scenarios }), (e) => /release failure/.test(e.message) && e.cleanup.sessionReleased === false); assert.equal(p.releases(), 1); });
test('rejects invalid feature dimensions before calling inference', async () => { const { measureOracleBatches } = await api(); const p = port(); await assert.rejects(measureOracleBatches({ runtime: p.runtime, adapter: { materializeFen: () => ({ features: new Float32Array(17) }) }, modelPath: 'fixture', scenarios }), /feature/i); assert.equal(p.releases(), 1); });
test('accepts producer standard-array features without duplicating encoding', async () => { const { measureOracleBatches } = await api(); const p = port(); const producer = { materializeFen() { const features = Array(1088).fill(0); features[64] = 1; return { features }; } }; const result = await measureOracleBatches({ runtime: p.runtime, adapter: producer, modelPath: 'fixture', scenarios }); assert.equal(result.batches[0].features.readFloatLE(64 * 4), 1); assert.equal(p.releases(), 1); });
test('rejects runtime registry integrity mismatch before provider loading', async () => { const { validateOracleInstall } = await api(); assert.equal(typeof validateOracleInstall, 'function', 'Locked runtime validation is missing'); const pkg = { name: 'onnxruntime-node', version: '1.30.0' }; const expected = { name: pkg.name, version: pkg.version, integrity: 'verified-registry-integrity', tarball: 'verified-registry-url' }; const lock = { packages: { 'node_modules/onnxruntime-node': { version: pkg.version, integrity: 'different', resolved: expected.tarball } } }; assert.throws(() => validateOracleInstall(pkg, lock, expected), /integrity/i); });
