import assert from 'node:assert/strict';
import { access } from 'node:fs/promises';
import test from 'node:test';
async function api() { const url = new URL('./latticeknight-physical-observation.mjs', import.meta.url); try { await access(url); } catch { assert.fail('Physical observation implementation is missing'); } return import(url); }
const floats = (...values) => { const b = Buffer.alloc(values.length * 4); values.forEach((v, i) => b.writeFloatLE(v, i * 4)); return b; };
test('comparison accepts original tolerances and reports first divergence without weakening them', async () => { const { compareFp32 } = await api(); const accepted = compareFp32(floats(1, 2), floats(1.0001, 2), 0.0002); assert.equal(accepted.pass, true); const rejected = compareFp32(floats(1, 2), floats(1.001, 2.002), 0.0002); assert.equal(rejected.pass, false); assert.equal(rejected.firstDivergence.index, 0); assert.equal(rejected.tolerance, 0.0002); });
test('comparison rejects nonfinite outputs and length mismatch', async () => { const { compareFp32 } = await api(); assert.throws(() => compareFp32(floats(1), floats(NaN), 0.0002), /nonfinite/i); assert.throws(() => compareFp32(floats(1), floats(1, 2), 0.0002), /length/i); });
test('numerical comparison records relative and absolute first divergence independently', async () => { const { compareFp32 } = await api(); const result = compareFp32(floats(2, 4), floats(3, 4), 0.0002); assert.equal(result.maximumRelativeError, 0.5); assert.equal(result.maximumAbsoluteError, 1); assert.equal(result.firstDivergence.index, 0); });
test('whole unchanged model fails closed at the public prepared binding limit before compiler or GPU work', async () => { const { preflightPhysicalModel } = await api(); const report = await preflightPhysicalModel(); assert.equal(report.admitted, false); assert.equal(report.failure.code, 'TENSOR_SIMT_BINDING_LIMIT'); assert.equal(report.failure.details.maximum, 64); assert.equal(report.semanticNodeCount, 2216); assert.equal(report.materialBytes, 48914008); assert.equal(report.cleanup.sessionGraceful, true); assert.equal(report.cleanup.runtimeGraceful, true); assert.equal(report.cleanup.compilerProgramsCreated, 0); });
