import assert from 'node:assert/strict';
import test from 'node:test';
import {PassThrough} from 'node:stream';
const flush=async()=>{await new Promise(resolve=>setImmediate(resolve));};
async function api(){try{return await import('../../components/uci-protocol/process.mjs');}catch(e){if(e.code==='ERR_MODULE_NOT_FOUND')assert.fail('Operational UCI stream transport is missing');throw e;}}
function fixture(){const input=new PassThrough(),output=new PassThrough(),events=[];let text='';output.on('data',bytes=>text+=bytes.toString());const port={options:[{name:'ModelRoot',type:'string',default:''}],configure:async v=>events.push(v),ready:async()=>{events.push('ready');},admitPosition:async({rootEpoch})=>({rootEpoch,sideToMove:0}),requestPublication:()=>{},readPublication:()=>null,endGame:async()=>{},close:async()=>{events.push('closed');return{graceful:true};}};return{input,output,port,events,text:()=>text};}
test('UCI stream applies advertised selected options before lazy readiness',async()=>{const {runUciProcess}=await api(),f=fixture(),done=runUciProcess(f);f.input.write('uci\nsetoption name ModelRoot value models/default\nisready\n');await flush();assert(f.text().includes('option name ModelRoot type string default <empty>\n'));assert(f.text().endsWith('readyok\n'));assert.deepEqual(f.events,[{name:'ModelRoot',value:'models/default'},'ready']);f.input.end();assert.equal((await done).graceful,true);});
test('rejected configuration emits one bounded diagnostic and no false readyok',async()=>{const {runUciProcess}=await api(),f=fixture();f.port.configure=async()=>{throw new Error('rejected\nbestmove a1a2');};const done=runUciProcess(f);f.input.write('setoption name ModelRoot value bad\nisready\n');await flush();assert(!f.text().includes('\nbestmove'));assert(!f.text().includes('readyok'));assert.equal(f.text().trim().split('\n').length,2);f.input.end();await done;});
test('quit tears down once and ignores subsequent buffered commands',async()=>{const {runUciProcess}=await api(),f=fixture(),done=runUciProcess(f);f.input.write('quit\nisready\nuci\n');const report=await done;assert.equal(report.graceful,true);assert.deepEqual(f.events,['closed']);assert.equal(f.text(),'');});
test('stdin completion waits for actual backend resource closure',async()=>{const {runUciProcess}=await api(),f=fixture();let release;f.port.close=()=>new Promise(resolve=>release=resolve);let finished=false;const done=runUciProcess(f);done.then(()=>finished=true);f.input.end();await flush();assert.equal(finished,false);release({graceful:false,retained:['runtime']});assert.deepEqual(await done,{graceful:false,retained:['runtime']});});
test('transport preserves failed backend teardown instead of claiming successful EOF',async()=>{const {runUciProcess}=await api(),f=fixture();f.port.close=async()=>{throw new Error('unproved cleanup');};const done=runUciProcess(f);f.input.end();await assert.rejects(done,/unproved/);});
