import assert from 'node:assert/strict';
import test from 'node:test';
async function api() { try { return await import('../../components/uci-protocol/index.mjs'); } catch (error) { if (error.code === 'ERR_MODULE_NOT_FOUND') assert.fail('UCI protocol implementation is missing'); throw error; } }
const flush = async () => { for (let i = 0; i < 8; i++) await Promise.resolve(); };
function fixture() {
  let clock = 0, admission, requests = [];
  const timers = new Set(), output = [], snapshots = new Map();
  const port = { ready: async () => {}, admitPosition: async ({rootEpoch}) => { if (admission) await admission; return {rootEpoch,sideToMove:0}; }, requestPublication: request => requests.push(request), readPublication: request => snapshots.get(request.requestId) ?? null, close: async () => ({graceful:true}) };
  const advance = async ms => { clock += ms; for (const timer of [...timers]) if (timer.at <= clock) { timers.delete(timer); timer.fn(); } await flush(); };
  return { port, output, timers, requests, snapshots, advance, deferAdmission: promise => { admission = promise; }, options: {port,write: line => output.push(line),now:()=>clock,setTimer:(fn,ms)=>{ const t={fn,at:clock+ms};timers.add(t);return t; },clearTimer:t=>timers.delete(t)} };
}
test('parser admits coordinate moves and rejects malformed or ambiguous UCI position', async () => { const {parseUciCommand}=await api(); assert.deepEqual(parseUciCommand('position startpos moves e2e4 a7a8q').moves,[1804,20016]); assert.throws(()=>parseUciCommand('position fen 8/8/8/8/8/8/8/8 w - - 0'),/six|FEN/i); assert.throws(()=>parseUciCommand('position startpos moves e2e9'),/move/i); assert.throws(()=>parseUciCommand('position startpos garbage'),/position/i); });
test('parser rejects unsupported search budgets instead of using them as GPU work limits', async () => { const {parseUciCommand}=await api(); assert.throws(()=>parseUciCommand('go depth 5'),/unsupported/i); assert.throws(()=>parseUciCommand('go nodes 500'),/unsupported/i); assert.throws(()=>parseUciCommand('go movetime -1'),/time|integer/i); assert.equal(parseUciCommand('go wtime 1000 btime 2000 winc 20 binc 10').wtime,1000); });
test('clock deadline publishes a legal snapshot while active GPU work remains pending', async () => { const {createUciController}=await api(); const f=fixture(),c=createUciController(f.options); await c.handle('position startpos'); await c.handle('go movetime 30'); assert.equal(f.requests.length,0); await f.advance(30); assert.equal(f.requests.length,1); const r=f.requests[0]; f.snapshots.set(r.requestId,{...r,action:1804,legalProof:{rootEpoch:r.rootEpoch,action:1804,legal:true},terminal:false}); await f.advance(5); assert.deepEqual(f.output,['bestmove e2e4']); await c.close(); });
test('position replacement fences stale publication and does not wait for active search', async () => { const {createUciController}=await api(); const f=fixture(),c=createUciController(f.options); await c.handle('position startpos'); await c.handle('go infinite'); await c.handle('stop'); const old=f.requests[0]; await c.handle('position startpos moves e2e4'); f.snapshots.set(old.requestId,{...old,action:1804,legalProof:{rootEpoch:old.rootEpoch,action:1804,legal:true},terminal:false}); await f.advance(5); assert.deepEqual(f.output,[]); assert.equal(f.requests.length,1); await c.close(); });
test('duplicate stop publishes once and rejects a missing or mismatched legal proof', async () => { const {createUciController}=await api(); const f=fixture(),c=createUciController(f.options); await c.handle('position startpos'); await c.handle('go infinite'); await c.handle('stop'); await c.handle('stop'); const r=f.requests[0]; assert.equal(f.requests.length,1); f.snapshots.set(r.requestId,{...r,action:1804,terminal:false}); await f.advance(5); assert.equal(f.output.some(x=>x.startsWith('bestmove')),false); f.snapshots.set(r.requestId,{...r,action:1804,legalProof:{rootEpoch:r.rootEpoch,action:1805,legal:true},terminal:false}); await f.advance(5); assert.equal(f.output.some(x=>x.startsWith('bestmove')),false); await c.close(); });
test('terminal null action requires current terminal proof and maps to bestmove 0000', async () => { const {createUciController}=await api(); const f=fixture(),c=createUciController(f.options); await c.handle('position startpos'); await c.handle('go infinite'); await c.handle('stop'); const r=f.requests[0]; f.snapshots.set(r.requestId,{...r,action:null,terminal:true,legalProof:{rootEpoch:r.rootEpoch,action:null,legal:true}}); await f.advance(5); assert.deepEqual(f.output,['bestmove 0000']); await c.close(); });
test('isready and stop remain processable during pending position admission', async () => { const {createUciController}=await api(); const f=fixture(); let release; f.deferAdmission(new Promise(resolve=>release=resolve)); const c=createUciController(f.options),p=c.handle('position startpos'); await c.handle('isready'); await c.handle('stop'); assert.deepEqual(f.output,['readyok']); release(); await p; await c.close(); assert.equal(f.timers.size,0); });
test('new game never reuses a root epoch and requires a fresh position before go', async () => { const {createUciController}=await api(); const f=fixture(),c=createUciController(f.options); await c.handle('position startpos'); await c.handle('go infinite'); await c.handle('stop'); const first=f.requests[0]; await c.handle('ucinewgame'); await assert.rejects(c.handle('go infinite'),/position/i); await c.handle('position startpos'); await c.handle('go infinite'); await c.handle('stop'); assert(f.requests[1].rootEpoch>first.rootEpoch); await c.close(); });
test('stop during pending admission records intent and publishes only after legal admission', async () => { const {createUciController}=await api(); const f=fixture(); let release; f.deferAdmission(new Promise(resolve=>release=resolve)); const c=createUciController(f.options),position=c.handle('position startpos'),go=c.handle('go infinite'); await c.handle('stop'); assert.equal(f.requests.length,0); release(); await position; await go; assert.equal(f.requests.length,1); await c.close(); });
