import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash,randomBytes} from 'node:crypto';
import {setImmediate as yieldToProtocol} from 'node:timers/promises';
import {Chess} from 'chess.js';
import {piece,castling,enPassant,turn} from '@echecs/zobrist';
import {actionToUci} from '../chess-domain/admission.mjs';

export const BOOK_BOUNDS=Object.freeze({records:2000000,bookBytes:32000000,entriesBytes:67108864,statsBytes:196000130,manifestBytes:1048576,policyBytes:16512,policyLines:64,policyLineBytes:256,statsHeaderBytes:128,statsRowBytes:96});
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const fail=code=>{throw new Error(code);};
const policyKeys=['prior_games','draw_value','confidence_standard_errors','minimum_games','maximum_lcb_gap','quality_exponent','maximum_rarity_multiplier','exit_intercept','exit_depth_weight','exit_advantage_weight','exit_disadvantage_weight','exit_weakness_weight','eval_deadband_cp','eval_scale_cp','depth_start_ply','depth_span_plies'];
const checkedAction=a=>Number.isInteger(a)&&a>=0&&a<=0x4fff&&((a>>>12)&7)<=4;
const freeze=value=>{if(value&&typeof value==='object'){Object.values(value).forEach(freeze);Object.freeze(value);}return value;};
async function openBounded(file,max,optional=false){
 let handle;try{handle=await fs.open(file,'r');const stat=await handle.stat();if(!stat.isFile()||!Number.isSafeInteger(stat.size)||stat.size>max)fail('BOOK_FILE_BOUNDS');return {handle,size:stat.size};}catch(error){if(handle)await handle.close();if(optional&&error.code==='ENOENT')return null;throw error;}
}
async function exactRead(handle,buffer,position){let at=0;while(at<buffer.length){const {bytesRead}=await handle.read(buffer,at,buffer.length-at,position+at);if(!bytesRead)fail('BOOK_TRUNCATED');at+=bytesRead;}}
async function finiteBytes(open){const bytes=Buffer.alloc(open.size);await exactRead(open.handle,bytes,0);const stat=await open.handle.stat();if(stat.size!==open.size)fail('BOOK_CHANGED');return bytes;}
async function* lines(open,maxLine,maxLines){
 const hash=createHash('sha256'),chunk=Buffer.alloc(16384),decoder=new TextDecoder('utf-8',{fatal:true});let position=0,pending=Buffer.alloc(0),count=0;
 while(position<open.size){const size=Math.min(chunk.length,open.size-position),bytes=chunk.subarray(0,size);await exactRead(open.handle,bytes,position);position+=size;hash.update(bytes);
  let start=0;for(let i=0;i<size;i++)if(bytes[i]===10){const length=pending.length+i-start;if(length>maxLine||++count>maxLines)fail('BOOK_LINE_BOUNDS');const line=Buffer.concat([pending,bytes.subarray(start,i)],length);yield decoder.decode(line).replace(/\r$/,'');pending=Buffer.alloc(0);start=i+1;}
  const tail=bytes.subarray(start);if(pending.length+tail.length>maxLine)fail('BOOK_LINE_BOUNDS');pending=Buffer.concat([pending,tail]);await yieldToProtocol();
 }
 if(pending.length){if(++count>maxLines)fail('BOOK_LINE_BOUNDS');yield decoder.decode(pending).replace(/\r$/,'');}
 if((await open.handle.stat()).size!==open.size)fail('BOOK_CHANGED');return hash.digest('hex');
}
async function consumeLines(open,maxLine,maxLines,consume){const iterator=lines(open,maxLine,maxLines);let i=0;for(;;){const step=await iterator.next();if(step.done)return step.value;consume(step.value,i++);}}
function parsePolicy(rows){const policy={};for(const row of rows){const line=row.trim();if(!line||line.startsWith('#'))continue;const at=line.indexOf('='),key=line.slice(0,at).trim(),text=line.slice(at+1).trim();if(at<1||!policyKeys.includes(key)||Object.hasOwn(policy,key)||text===''||!Number.isFinite(Number(text)))fail('BOOK_POLICY');policy[key]=Number(text);}
 if(policyKeys.some(key=>!Object.hasOwn(policy,key))||policy.prior_games<0||policy.draw_value<0||policy.draw_value>1||policy.confidence_standard_errors<0||!Number.isInteger(policy.minimum_games)||policy.minimum_games<1||policy.maximum_lcb_gap<=0||policy.quality_exponent<0||policy.maximum_rarity_multiplier<1||policy.eval_scale_cp<=0||policy.depth_span_plies<=0||policy.eval_deadband_cp<0||policy.depth_start_ply<0||policy.exit_advantage_weight<0||policy.exit_disadvantage_weight>0)fail('BOOK_POLICY');for(const depth of [0,1])for(const [advantage,disadvantage]of [[0,0],[2,0],[0,2]])for(const weakness of [0,1])if(!Number.isFinite(policy.exit_intercept+policy.exit_depth_weight*depth+policy.exit_advantage_weight*advantage+policy.exit_disadvantage_weight*disadvantage+policy.exit_weakness_weight*weakness))fail('BOOK_POLICY');return Object.freeze(policy);
}
export async function admitBookSnapshot({bookFile,statsFile,policyFile,manifestFile=path.join(path.dirname(bookFile),'snapshot.manifest.json')},{entryBudget=BOOK_BOUNDS.entriesBytes}={}){
 if([bookFile,statsFile,policyFile,manifestFile].some(file=>typeof file!=='string'||!file||/[\x00-\x1f\x7f]/.test(file)))fail('BOOK_PATH');
 if(new Set([bookFile,statsFile,policyFile].map(file=>path.basename(file).toLowerCase())).size!==3)fail('BOOK_ROLE_ALIAS');
 const opened=[];try{
  const open=async(file,max,optional=false)=>{const value=await openBounded(file,max,optional);if(value)opened.push(value);return value;};
  const book=await open(bookFile,BOOK_BOUNDS.bookBytes),manifest=await open(manifestFile,BOOK_BOUNDS.manifestBytes,true);
  if(!book.size||book.size%16!==0)fail('BOOK_RECORD_COUNT');const count=book.size/16;if(count>BOOK_BOUNDS.records||count*32>BOOK_BOUNDS.entriesBytes)fail('BOOK_RECORD_COUNT');if(!Number.isSafeInteger(entryBudget)||entryBudget<0||count*32>entryBudget)fail('BOOK_TRANSACTION_CAPACITY');
  let manifestBytes,m;if(manifest){manifestBytes=await finiteBytes(manifest);try{m=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(manifestBytes));}catch{fail('BOOK_MANIFEST');}if(m.schema!=='uci_arena_book_snapshot_v2'||!Number.isInteger(m.record_count)||m.record_count<1||m.record_count>BOOK_BOUNDS.records||m.record_count!==count)fail('BOOK_RECORD_COUNT');if(!/^(integration|qualified)-[0-9a-f]{20}$/.test(m.snapshot_id??'')||!['integration','qualified'].includes(m.channel)||m.snapshot_id.split('-')[0]!==m.channel||m.qualified!==(m.channel==='qualified')||!m.artifacts||typeof m.artifacts!=='object')fail('BOOK_MANIFEST');}
  const stats=await open(statsFile,BOOK_BOUNDS.statsBytes,true),policyOpen=await open(policyFile,BOOK_BOUNDS.policyBytes,true);if(Boolean(stats)!==Boolean(policyOpen))fail('BOOK_SIDECAR_PAIR');if(m&&(!stats||!policyOpen))fail('BOOK_SIDECAR_PAIR');
  const entries=new Uint32Array(count*8),record=Buffer.alloc(16),chunk=Buffer.alloc(65536),hash=createHash('sha256');let fnv=0xcbf29ce484222325n,previousKey=-1n,previousMove=-1;
  for(let start=0;start<count;start+=4096){const records=Math.min(4096,count-start),bytes=chunk.subarray(0,records*16);await exactRead(book.handle,bytes,start*16);hash.update(bytes);
   for(let j=0;j<records;j++){const i=start+j;bytes.copy(record,0,j*16,j*16+16);for(const byte of record)fnv=BigInt.asUintN(64,(fnv^BigInt(byte))*0x100000001b3n);const key=record.readBigUInt64BE(),move=record.readUInt16BE(8);if(key<previousKey||(key===previousKey&&move<=previousMove))fail('BOOK_ORDER');if(move&0x8000||(move>>>12)>4)fail('BOOK_MOVE');entries[i*8]=record.readUInt32BE();entries[i*8+1]=record.readUInt32BE(4);entries[i*8+2]=move;entries[i*8+3]=record.readUInt16BE(10);previousKey=key;previousMove=move;}await yieldToProtocol();}
  if((await book.handle.stat()).size!==book.size)fail('BOOK_CHANGED');const digests={[path.basename(bookFile)]:hash.digest('hex')},fnvHex=fnv.toString(16).padStart(16,'0');let policy;
  if(stats){let statRows=0;digests[path.basename(statsFile)]=await consumeLines(stats,BOOK_BOUNDS.statsHeaderBytes,count+1,(line,index)=>{if(index===0){if(line!==`# uci_arena_book_stats_v1 book_fnv1a64=${fnvHex} rows=${count}`)fail('BOOK_STATS_HEADER');return;}if(Buffer.byteLength(line)>BOOK_BOUNDS.statsRowBytes)fail('BOOK_LINE_BOUNDS');const fields=line.split('\t'),i=index-1;if(fields.length!==6||!(/^[0-9a-f]{16}$/).test(fields[0])||!(/^[0-9a-f]{4}$/).test(fields[1])||fields.slice(2).some(v=>!/^\d+$/.test(v)||Number(v)>0xffffffff))fail('BOOK_STATS');const base=i*8,key=BigInt('0x'+fields[0]),move=parseInt(fields[1],16),values=fields.slice(2).map(Number);if(i>=count||key!==((BigInt(entries[base])<<32n)|BigInt(entries[base+1]))||move!==entries[base+2]||values[0]===0||values[0]!==values[1]+values[2]+values[3])fail('BOOK_STATS');entries.set(values,base+4);statRows++;});if(statRows!==count)fail('BOOK_STATS_COUNT');const rows=[];digests[path.basename(policyFile)]=await consumeLines(policyOpen,BOOK_BOUNDS.policyLineBytes,BOOK_BOUNDS.policyLines,line=>rows.push(line));policy=parsePolicy(rows);}
  if(m)for(const [name,digest]of Object.entries(digests))if(!/^[0-9a-f]{64}$/.test(m.artifacts[name]??'')||m.artifacts[name]!==digest)fail('BOOK_ARTIFACT_DIGEST');
  const status=freeze({schema:'vector_book_admission_v1',identity:manifestBytes?sha(manifestBytes):fnvHex,validationMode:m?'manifest_backed':'legacy_file_set',generation:m?.snapshot_id??null,recordCount:count,capability:policy?'statistical_selection':'polyglot_base',statisticalSelection:Boolean(policy),strengthQualified:m?.qualified===true,includesFixture:m?.includes_fixture===true,digests});
  const candidates=key=>{let lo=0,hi=count;const keyAt=i=>(BigInt(entries[i*8])<<32n)|BigInt(entries[i*8+1]);while(lo<hi){const mid=Math.floor((lo+hi)/2);if(keyAt(mid)<key)lo=mid+1;else hi=mid;}const rows=[];for(let i=lo;i<count&&keyAt(i)===key;i++){const at=i*8;rows.push({move:entries[at+2],weight:entries[at+3],games:entries[at+4],wins:entries[at+5],draws:entries[at+6],losses:entries[at+7]});}return rows;};
  return Object.freeze({status,policy,candidates});
 }finally{const results=await Promise.allSettled(opened.map(v=>v.handle.close()));const failure=results.find(r=>r.status==='rejected');if(failure)throw failure.reason;}
}
function rootBoard(context){
 if(context?.schema!=='vector_root_knowledge_context_v1'||!Number.isSafeInteger(context.rootEpoch)||context.rootEpoch<1||!Array.isArray(context.rootFence)||context.rootFence.length!==4||context.rootFence.some(x=>!Number.isInteger(x)||x<0||x>0xfffffffe)||!Array.isArray(context.legalActions)||context.legalActions.length>256||context.legalActions.some(x=>!checkedAction(x))||new Set(context.legalActions).size!==context.legalActions.length||!Array.isArray(context.input?.moves)||context.input.moves.length>4096||context.input.moves.some(x=>!checkedAction(x)))fail('BOOK_INPUT');
 try{const board=new Chess(context.input.originFen);for(const action of context.input.moves){const move=actionToUci(action);board.move({from:move.slice(0,2),to:move.slice(2,4),promotion:move[4]});}return board;}catch{fail('BOOK_INPUT');}
}
function boardKey(board){let key=0n;const names={p:'pawn',n:'knight',b:'bishop',r:'rook',q:'queen',k:'king'};for(const row of board.board())for(const token of row)if(token)key^=piece(token.square,names[token.type],token.color==='w'?'white':'black');const fields=board.fen({forceEnpassantSquare:true}).split(' '),rights=fields[2];for(const [symbol,color,side]of [['K','white','king'],['Q','white','queen'],['k','black','king'],['q','black','queen']])if(rights.includes(symbol))key^=castling(color,side);if(fields[3]!=='-'){const file=fields[3].charCodeAt(0)-97,rank=Number(fields[3][1])+(board.turn()==='w'?-1:1);if([-1,1].some(delta=>{const x=file+delta;if(x<0||x>7)return false;const p=board.get(String.fromCharCode(97+x)+rank);return p?.type==='p'&&p.color===board.turn();}))key^=enPassant(fields[3][0]);}if(board.turn()==='w')key^=turn('white');return key;}
export function bookKeyForRoot(context){return boardKey(rootBoard(context));}
export function createBookProvider(){
 let active,configuration,gameSnapshot,gameOpen=false,sequence=Promise.resolve();
 const signature=files=>JSON.stringify(['bookFile','statsFile','policyFile','manifestFile'].map(k=>files[k]===undefined?null:path.resolve(files[k])));
 const status=(reason,retained=false)=>freeze({schema:'vector_book_provider_status_v1',active:Boolean(active),retained,reason,snapshot:active?.status??null});
 return Object.freeze({
  reload(files){const op=sequence.then(async()=>{const next=signature(files),same=next===configuration;if(!same){active=undefined;configuration=next;}try{const retained=new Set([active,gameSnapshot].filter(Boolean)),used=[...retained].reduce((n,s)=>n+s.status.recordCount*32,0),candidate=await admitBookSnapshot(files,{entryBudget:134217728-used});active=candidate;return status(null);}catch(error){return status(/^BOOK_[A-Z_]+$/.test(error.message)?error.message:'BOOK_READ_FAILED',same&&Boolean(active));}});sequence=op.catch(()=>{});return op;},
  newGame(options){if(gameOpen)fail('BOOK_GAME_ALREADY_ACTIVE');if(!active)return null;const game=createBookGame({...options,snapshot:active});gameSnapshot=active;gameOpen=true;let closed=false;return Object.freeze({resolve(input){if(closed)fail('BOOK_GAME_CLOSED');return game.resolve(input);},close(){if(closed)return;closed=true;gameOpen=false;gameSnapshot=undefined;}});}
 });
}
function decodeMove(raw,board){const from=(raw>>>6)&63;let to=raw&63;if(board.get(String.fromCharCode(97+from%8)+(Math.floor(from/8)+1))?.type==='k'){if(from===4&&to===7)to=6;else if(from===4&&to===0)to=2;else if(from===60&&to===63)to=62;else if(from===60&&to===56)to=58;}return from|(to<<6)|((raw>>>12)<<12);}
function seededRandom(seed){let x=seed>>>0;return()=>{x=(x+0x6d2b79f5)>>>0;let t=Math.imul(x^(x>>>15),1|x);t^=t+Math.imul(t^(t>>>7),61|t);return((t^(t>>>14))>>>0)/4294967296;};}
export function createBookGame({snapshot,seed=0,maxPly=30,random}={}){
 if(!snapshot?.status||!Number.isInteger(seed)||seed<0||seed>2147483647||!Number.isInteger(maxPly)||maxPly<0||maxPly>80)fail('BOOK_GAME');let exited=false;const rng=random??seededRandom(seed||randomBytes(4).readUInt32LE());const roll=()=>{const r=rng();if(!Number.isFinite(r)||r<0||r>=1)fail('BOOK_RANDOM');return r;};
 return Object.freeze({resolve({context,searchmoves=[],evaluationCp,tablebaseEligible=false}){
  const unavailable=reason=>({status:'unavailable',reason,authority:null});if(exited)return unavailable('book_exited');if(context?.terminal)return unavailable('terminal');if(tablebaseEligible)return unavailable('tablebase_priority');const board=rootBoard(context),fields=board.fen().split(' '),ply=(Number(fields[5])-1)*2+(board.turn()==='b'?1:0);if(ply>=maxPly)return unavailable('maximum_ply');if(!Array.isArray(searchmoves)||searchmoves.length>256||searchmoves.some(a=>!checkedAction(a)))fail('BOOK_RESTRICTION');const legal=new Set(context.legalActions),allowed=searchmoves.length?new Set(searchmoves):legal,key=boardKey(board),rows=snapshot.candidates(key).map(row=>({...row,action:decodeMove(row.move,board)})).filter(row=>legal.has(row.action));if(new Set(rows.map(row=>row.action)).size!==rows.length)return unavailable('ambiguous_book_move');if(!rows.length)return unavailable('no_eligible_move');
  const policy=snapshot.policy;let exitProbability=null;const evaluationSource=evaluationCp===undefined?'neutral_latency_fallback':'compatible_completed_evaluation';if(evaluationCp===undefined)evaluationCp=0;else if(!Number.isFinite(evaluationCp))fail('BOOK_EVALUATION');let bestLcb=0,eligible=rows;if(policy){const games=rows.reduce((sum,r)=>sum+r.games,0),mean=rows.reduce((sum,r)=>sum+r.wins+policy.draw_value*r.draws,0)/games,maxGames=Math.max(...rows.map(r=>r.games));for(const row of rows){const meanRow=(row.wins+policy.draw_value*row.draws+policy.prior_games*mean)/(row.games+policy.prior_games);row.lcb=meanRow-policy.confidence_standard_errors*Math.sqrt(meanRow*(1-meanRow)/(row.games+policy.prior_games+1));}bestLcb=Math.max(...rows.map(r=>r.lcb));eligible=rows.filter(r=>r.games>=policy.minimum_games&&r.lcb>=bestLcb-policy.maximum_lcb_gap);for(const row of eligible){const quality=Math.min(1,Math.max(0,(row.lcb-bestLcb+policy.maximum_lcb_gap)/policy.maximum_lcb_gap));row.selectionWeight=Math.max(1e-9,quality**policy.quality_exponent)*Math.min(policy.maximum_rarity_multiplier,Math.sqrt(maxGames/(row.games+1)));}}else for(const row of rows)row.selectionWeight=Math.max(1,row.weight);
  eligible=eligible.filter(row=>allowed.has(row.action));if(!eligible.length)return unavailable('no_eligible_move');const total=eligible.reduce((sum,r)=>sum+r.selectionWeight,0);let cursor=roll()*total,selected=eligible.at(-1);for(const row of eligible){cursor-=row.selectionWeight;if(cursor<0){selected=row;break;}}
  if(policy){const clamp=(v,max=1)=>Math.min(max,Math.max(0,v)),depth=clamp((ply-policy.depth_start_ply)/policy.depth_span_plies),advantage=clamp((evaluationCp-policy.eval_deadband_cp)/policy.eval_scale_cp,2),disadvantage=clamp((-evaluationCp-policy.eval_deadband_cp)/policy.eval_scale_cp,2),weakness=clamp((bestLcb-selected.lcb)/policy.maximum_lcb_gap),logit=policy.exit_intercept+policy.exit_depth_weight*depth+policy.exit_advantage_weight*advantage+policy.exit_disadvantage_weight*disadvantage+policy.exit_weakness_weight*weakness;exitProbability=1/(1+Math.exp(-logit));if(roll()<exitProbability){exited=true;return {...unavailable('dynamic_exit'),telemetry:{evaluationSource,evaluationCp,exitProbability}};}}
  return freeze({status:'resolved',authority:'book-resolved',action:selected.action,rootEpoch:context.rootEpoch,rootFence:[...context.rootFence],snapshotIdentity:snapshot.status.identity,generation:snapshot.status.generation,telemetry:{evaluationSource:policy?evaluationSource:'not_applicable',evaluationCp:policy?evaluationCp:null,exitProbability,games:policy?selected.games:0,lcb:policy?selected.lcb:0,positionKey:key.toString(16).padStart(16,'0'),ply}});
 }});
}
