import fs from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawn} from 'node:child_process';
import {createTablebaseTicket,canonicalJson} from './tablebase.mjs';

const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const digestPattern=/^[0-9a-f]{64}$/;
async function noLinks(file){const absolute=path.resolve(file),parts=absolute.slice(path.parse(absolute).root.length).split(path.sep);let current=path.parse(absolute).root;for(const part of parts){current=path.join(current,part);const s=await fs.lstat(current);if(s.isSymbolicLink())throw new Error('Linked provider path is forbidden');}return absolute;}
async function boundedBytes(file,limit){await noLinks(file);const s=await fs.stat(file);if(!s.isFile()||s.size>limit)throw new Error('Provider document extent exceeded');return fs.readFile(file);}
export const readRootProviderDocument=boundedBytes;
const inventoryPath=(root,p)=>{if(typeof p!=='string'||!p.length||p.length>256||!/^[A-Za-z0-9._/-]+$/.test(p)||p.split('/').some(s=>!s||s==='.'||s==='..')||path.isAbsolute(p))throw new Error('Invalid provider inventory path');return path.join(root,...p.split('/'));};
export async function admitRootTablebasePackage({root,manifestSha256,contractSha256}){
 if(!digestPattern.test(manifestSha256??'')||!digestPattern.test(contractSha256??''))throw new Error('Exact public provider inventory and contract digests required');
 root=await noLinks(root);const bytes=await boundedBytes(path.join(root,'package-manifest.json'),1048576);if(sha(bytes)!==manifestSha256)throw new Error('Provider manifest digest mismatch');const manifest=JSON.parse(bytes);
 if(manifest.schema!=='uci_arena_root_provider_package_v1'||!Array.isArray(manifest.files)||!manifest.files.length||manifest.files.length>128)throw new Error('Provider inventory schema or finite count invalid');
 const seen=new Set();let total=0;for(const row of manifest.files){const file=inventoryPath(root,row.path),alias=row.path.toLowerCase();if(seen.has(alias))throw new Error('Duplicate provider inventory path');seen.add(alias);if(!Number.isSafeInteger(row.bytes)||row.bytes<0||row.bytes>33554432||!digestPattern.test(row.sha256??'')||(total+=row.bytes)>67108864)throw new Error('Provider inventory extent invalid');await noLinks(file);const s=await fs.stat(file);if(!s.isFile()||s.size!==row.bytes)throw new Error('Provider inventoried file extent mismatch');const hash=createHash('sha256');let size=0;for await(const chunk of createReadStream(file,{highWaterMark:65536})){size+=chunk.length;if(size>row.bytes)throw new Error('Provider inventory changed during admission');hash.update(chunk);}if(size!==row.bytes||hash.digest('hex')!==row.sha256)throw new Error('Provider inventory file digest mismatch');}
 const contractPath='contracts/offline-root-knowledge-v2.json',declared=manifest.files.find(r=>r.path===contractPath);if(!declared||declared.sha256!==contractSha256)throw new Error('Provider public contract lacks exact inventory authority');const contract=JSON.parse(await boundedBytes(path.join(root,contractPath),65536));
 if(contract.schema!=='uci_arena_root_knowledge_contract_v2'||!['2.0.0','2.1.0'].includes(contract.version)||contract.transport?.maximum_frame_bytes!==262208||contract.transport.maximum_output_bytes!==1048576||!contract.launch||contract.launch.working_directory!=='.'||!Array.isArray(contract.launch.arguments)||contract.launch.arguments.some(a=>typeof a!=='string'||a.length>512||/[\x00-\x1f\x7f]/.test(a)))throw new Error('Unsupported public root provider contract');
 if(contract.version==='2.1.0'){const c=contract.transport.cold_lifecycle;if(c?.schema!=='uci_arena_root_provider_cold_lifecycle_v1'||c.cancel_during_warming!==true||c.hash_chunk_bytes!==65536||c.warming_probe_disposition!=='deferred:provider_warming'||c.ready_notification!==false)throw new Error('Unsupported provider cold lifecycle capability');}
 const executable=inventoryPath(root,contract.launch.executable);if(!seen.has(contract.launch.executable.toLowerCase()))throw new Error('Provider executable is not inventoried');return Object.freeze({root,manifestSha256,contractSha256,fileCount:manifest.files.length,totalBytes:total,contract,executable});
}

export async function openRootTablebaseProvider({configPath,configSha256,onStatus,spawnProcess=spawn,...selection}){
 const admitted=await admitRootTablebasePackage(selection);configPath=await noLinks(configPath);const configBytes=await boundedBytes(configPath,65536);if(configSha256!==undefined&&sha(configBytes)!==configSha256)throw new Error('Provider cold configuration bytes changed');const configurationIdentity=sha(canonicalJson(JSON.parse(configBytes))),warmingCapable=admitted.contract.version==='2.1.0';
 const replacements={'<registered-cold-config>':configPath,'<admitted-package-sha256>':admitted.manifestSha256},args=admitted.contract.launch.arguments.map(a=>{if(a.startsWith('<')){if(!Object.hasOwn(replacements,a))throw new Error('Unknown declared provider launch binding');return replacements[a];}return a;});
 const process=spawnProcess(admitted.executable,args,{cwd:admitted.root,stdio:['pipe','pipe','pipe'],windowsHide:true});let description,providerClose,buffer=Buffer.alloc(0),failure,forced=false,closed=false,closePromise,readyResolve,readyReject,stderr='',pollTimer;const tickets=new Map(),readiness=new Promise((resolve,reject)=>{readyResolve=resolve;readyReject=reject;});
 const poison=error=>{failure??=error;clearTimeout(pollTimer);for(const t of tickets.values())t.fail();tickets.clear();readyReject(error);};
 const exited=new Promise(resolve=>process.once('close',(code,signal)=>{closed=true;clearTimeout(pollTimer);resolve({code,signal,forced});if(!description||!closePromise)poison(new Error('Provider exited outside joined close'));}));
 process.once('error',poison);process.stderr.on('data',b=>{stderr=(stderr+b.toString()).slice(-65536);});
 process.stdout.on('data',chunk=>{try{buffer=Buffer.concat([buffer,chunk]);if(buffer.length>1048576)throw new Error('Provider output framing extent exceeded');for(let n;(n=buffer.indexOf(10))>=0;){if(n>262208)throw new Error('Provider output frame extent exceeded');const line=buffer.subarray(0,n);buffer=buffer.subarray(n+1);const event=JSON.parse(line.toString('utf8'));if(event.schema==='uci_arena_syzygy_root_transport_v1'){
   if(event.operation==='describe'){
    const warming=warmingCapable&&event.status==='warming';
    if((description&&(!warmingCapable||description.status!=='warming'||event.provider_generation!==description.provider_generation))||(!warming&&event.status!=='ready')||!/^[0-9a-f]{32}$/.test(event.provider_generation??'')||event.provider_identity?.package?.manifest_sha256!==admitted.manifestSha256||event.profile?.root_only!==true||event.profile.worker_count!==1||event.profile.ticket_capacity!==(warming?0:2)||event.profile.request_schema!=='uci_arena_syzygy_root_request_v2')throw new Error('Provider actual readiness binding rejected');
    if(warmingCapable&&(event.provider_identity.configuration_sha256!==configurationIdentity||event.profile.cold_lifecycle?.schema!=='uci_arena_root_provider_cold_lifecycle_v1'||event.profile.cold_lifecycle.cancel_during_warming!==true||(warming&&(Object.hasOwn(event.provider_identity,'dataset')||event.readiness?.dataset!=='not-admitted'))||(!warming&&event.readiness?.dataset!=='admitted')))throw new Error('Provider warming/configuration readiness binding rejected');
    description=event;readyResolve(event);if(onStatus)onStatus(event);clearTimeout(pollTimer);if(warming&&!closePromise&&!closed&&!failure){pollTimer=setTimeout(()=>{if(!closePromise&&!closed&&!failure){try{send({operation:'describe'});}catch(error){poison(error);}}},1000);pollTimer.unref?.();}
   }
   else if(event.operation==='close'){if(providerClose||event.provider_generation!==description?.provider_generation)throw new Error('Provider close generation mismatch');providerClose=event;}
   else if(event.operation==='probe'){const t=tickets.get(event.request_id);if(t){t.fail();tickets.delete(event.request_id);}}
   else throw new Error('Unknown provider transport event');
  }else if(event.schema==='uci_arena_syzygy_root_result_v2'){const t=tickets.get(event.request_id);if(!t)continue;t.accept(event);if(event.sequence===1||event.authority?.raw_wdl_safety!==true)tickets.delete(event.request_id);}else throw new Error('Unknown provider output schema');}}catch(error){poison(error);}});
 const send=frame=>{if(closed||failure)throw failure??new Error('Provider process closed');const bytes=Buffer.from(JSON.stringify(frame)+'\n');if(bytes.length>262208)throw new Error('Provider input frame extent exceeded');process.stdin.write(bytes,error=>{if(error)poison(error);});};
 const waitBounded=(promise,milliseconds,message)=>{let timer;return Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(message)),milliseconds);})]).finally(()=>clearTimeout(timer));};
 const close=()=>{if(!closePromise)closePromise=(async()=>{clearTimeout(pollTimer);for(const t of tickets.values())t.abandon();tickets.clear();if(!closed&&!failure)send({operation:'close'});let exit;try{exit=await waitBounded(exited,30000,'Provider drain/EOF bound exceeded');}catch(error){forced=true;process.kill();await waitBounded(exited,5000,'Provider forced containment did not close');throw error;}if(failure)throw failure;if(buffer.length||exit.code!==0||exit.signal!==null||exit.forced||providerClose?.status!=='closed'||providerClose.drained!==true||providerClose.failed!==false)throw new Error('Actual provider joined process closure unproved');return Object.freeze({schema:'vector_root_provider_teardown_v1',provider:providerClose,process:exit,stderr});})();return closePromise;};
 try{send({operation:'describe'});await waitBounded(readiness,300000,'Provider cold readiness bound exceeded');}catch(error){if(!closed){forced=true;process.kill();}const exit=await waitBounded(exited,5000,'Provider failed startup containment did not close');error.providerFailure={process:exit,stderr};throw error;}
 return Object.freeze({describe(){return description;},
  probe(options){if(closed||closePromise||failure)throw failure??new Error('Provider is closing');if(description.status!=='ready')throw new Error('Provider is warming, dataset is not ready');if(tickets.size>=2)throw new Error('Provider ticket capacity unavailable');const ticket=createTablebaseTicket({...options,description});if(tickets.has(ticket.request.request_id))throw new Error('Provider request identity already pending');tickets.set(ticket.request.request_id,ticket);send({operation:'probe',request:ticket.request});return Object.freeze({request:ticket.request,requestSha256:ticket.requestSha256,read(current){if(failure)ticket.fail();return ticket.read(current);},abandon(){ticket.abandon();tickets.delete(ticket.request.request_id);if(!closed&&!closePromise&&!failure)send({operation:'cancel',request_id:ticket.request.request_id,root_fence:ticket.request.root_fence});}});},close});
}
